import { statisticsSkillGraph } from './StatisticsSkillGraph.js';

const SKILL_IDS = new Set(statisticsSkillGraph.skillIds);

const families = [
  {
    id: 'QF_ST001_001',
    skillId: 'ST001',
    name: 'Reading tables — Practice',
    description: 'Reading tables question.',
    difficulty: 1,
    generatorKind: 'statTableRead',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 15,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 10,
    misconceptionTags: ['stat/row-column-mix'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_ST001_002',
    skillId: 'ST001',
    name: 'Reading tables — MCQ',
    description: 'Reading tables question.',
    difficulty: 1,
    generatorKind: 'statTableReadMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 15,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 10,
    misconceptionTags: ['stat/row-column-mix'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_ST002_001',
    skillId: 'ST002',
    name: 'Picture graphs — Practice',
    description: 'Picture graphs question.',
    difficulty: 1,
    generatorKind: 'statPictureGraph',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 15,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 10,
    misconceptionTags: ['stat/ignore-key'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_ST002_002',
    skillId: 'ST002',
    name: 'Picture graphs — MCQ',
    description: 'Picture graphs question.',
    difficulty: 1,
    generatorKind: 'statPictureGraphMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 15,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 10,
    misconceptionTags: ['stat/ignore-key'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_ST003_001',
    skillId: 'ST003',
    name: 'Bar graphs — Practice',
    description: 'Bar graphs question.',
    difficulty: 2,
    generatorKind: 'statBarGraph',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 15,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['stat/scale-interval'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_ST003_002',
    skillId: 'ST003',
    name: 'Bar graphs — MCQ',
    description: 'Bar graphs question.',
    difficulty: 2,
    generatorKind: 'statBarGraphMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 15,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['stat/scale-interval'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_ST004_001',
    skillId: 'ST004',
    name: 'Line graphs — Practice',
    description: 'Line graphs question.',
    difficulty: 2,
    generatorKind: 'statLineGraph',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 15,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['stat/point-misread'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_ST004_002',
    skillId: 'ST004',
    name: 'Line graphs — MCQ',
    description: 'Line graphs question.',
    difficulty: 2,
    generatorKind: 'statLineGraphMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 15,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['stat/point-misread'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_ST005_001',
    skillId: 'ST005',
    name: 'Interpreting and comparing data — Practice',
    description: 'Interpreting and comparing data question.',
    difficulty: 3,
    generatorKind: 'statInterpret',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 20,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 12,
    misconceptionTags: ['stat/trend-overread'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_ST005_002',
    skillId: 'ST005',
    name: 'Interpreting and comparing data — MCQ',
    description: 'Interpreting and comparing data question.',
    difficulty: 3,
    generatorKind: 'statInterpretMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 20,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 12,
    misconceptionTags: ['stat/trend-overread'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_ST006_001',
    skillId: 'ST006',
    name: 'Average (mean) — concept — Practice',
    description: 'Average (mean) — concept question.',
    difficulty: 2,
    generatorKind: 'statMeanConcept',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['stat/mean-not-divide', 'stat/mean-ignore-zero'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_ST006_002',
    skillId: 'ST006',
    name: 'Average (mean) — concept — MCQ',
    description: 'Average (mean) — concept question.',
    difficulty: 2,
    generatorKind: 'statMeanConceptWord',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['stat/mean-not-divide', 'stat/mean-ignore-zero'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_ST007_001',
    skillId: 'ST007',
    name: 'Mean: finding the total or a missing value — Practice',
    description: 'Mean: finding the total or a missing value question.',
    difficulty: 3,
    generatorKind: 'statMeanApply',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 15,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 12,
    misconceptionTags: ['stat/mean-reverse'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_ST007_002',
    skillId: 'ST007',
    name: 'Mean: finding the total or a missing value — MCQ',
    description: 'Mean: finding the total or a missing value question.',
    difficulty: 3,
    generatorKind: 'statMeanApplyWord',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 15,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 12,
    misconceptionTags: ['stat/mean-reverse'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_ST008_001',
    skillId: 'ST008',
    name: 'Pie charts — Practice',
    description: 'Pie charts question.',
    difficulty: 3,
    generatorKind: 'statPieChart',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 15,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 12,
    misconceptionTags: ['stat/pie-angle-fraction'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_ST008_002',
    skillId: 'ST008',
    name: 'Pie charts — MCQ',
    description: 'Pie charts question.',
    difficulty: 3,
    generatorKind: 'statPieChartMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 15,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 12,
    misconceptionTags: ['stat/pie-angle-fraction'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
];

const familyById = new Map(families.map((family) => [family.id, family]));
const familiesBySkill = families.reduce((acc, family) => {
  if (!acc[family.skillId]) acc[family.skillId] = [];
  acc[family.skillId].push(family);
  return acc;
}, {});

export function getQuestionFamily(familyId) {
  return familyById.get(familyId) || null;
}

export function getQuestionFamiliesBySkill(skillId) {
  return familiesBySkill[skillId] ? [...familiesBySkill[skillId]] : [];
}

export function getAllQuestionFamilies() {
  return [...families];
}

export const statisticsQuestionFamilies = families;
export default statisticsQuestionFamilies;
