import { algebraSkillGraph } from './AlgebraSkillGraph.js';

const SKILL_IDS = new Set(algebraSkillGraph.skillIds);

const families = [
  {
    id: 'QF_AL001_001',
    skillId: 'AL001',
    name: 'Unknowns in arithmetic (missing numbers) — Practice',
    description: 'Unknowns in arithmetic (missing numbers) question.',
    difficulty: 2,
    generatorKind: 'algUnknownArith',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/equals-means-answer'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL001_002',
    skillId: 'AL001',
    name: 'Unknowns in arithmetic (missing numbers) — MCQ',
    description: 'Unknowns in arithmetic (missing numbers) question.',
    difficulty: 2,
    generatorKind: 'algUnknownArithMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/equals-means-answer'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL002_001',
    skillId: 'AL002',
    name: 'Using a letter for an unknown — Practice',
    description: 'Using a letter for an unknown question.',
    difficulty: 2,
    generatorKind: 'algUnknownLetter',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/letter-as-label', 'alg/letter-one-value'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL002_002',
    skillId: 'AL002',
    name: 'Using a letter for an unknown — MCQ',
    description: 'Using a letter for an unknown question.',
    difficulty: 2,
    generatorKind: 'algUnknownLetterMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/letter-as-label', 'alg/letter-one-value'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL003_001',
    skillId: 'AL003',
    name: 'Algebraic notation — Practice',
    description: 'Algebraic notation question.',
    difficulty: 2,
    generatorKind: 'algNotation',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/3n-means-3-plus-n'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL003_002',
    skillId: 'AL003',
    name: 'Algebraic notation — MCQ',
    description: 'Algebraic notation question.',
    difficulty: 2,
    generatorKind: 'algNotationMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/3n-means-3-plus-n'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL004_001',
    skillId: 'AL004',
    name: 'Forming expressions from words — Practice',
    description: 'Forming expressions from words question.',
    difficulty: 3,
    generatorKind: 'algFormExpression',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 12,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/word-order'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL004_002',
    skillId: 'AL004',
    name: 'Forming expressions from words — MCQ',
    description: 'Forming expressions from words question.',
    difficulty: 3,
    generatorKind: 'algFormExpressionMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 12,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/word-order'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL005_001',
    skillId: 'AL005',
    name: 'Substitution (evaluating expressions) — Practice',
    description: 'Substitution (evaluating expressions) question.',
    difficulty: 3,
    generatorKind: 'algSubstitute',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/sub-no-times', 'alg/sub-ignore-precedence'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL005_002',
    skillId: 'AL005',
    name: 'Substitution (evaluating expressions) — MCQ',
    description: 'Substitution (evaluating expressions) question.',
    difficulty: 3,
    generatorKind: 'algSubstituteWord',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/sub-no-times', 'alg/sub-ignore-precedence'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL006_001',
    skillId: 'AL006',
    name: 'Simplifying by collecting like terms — Practice',
    description: 'Simplifying by collecting like terms question.',
    difficulty: 3,
    generatorKind: 'algSimplifyAdd',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 7,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/combine-unlike'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL006_002',
    skillId: 'AL006',
    name: 'Simplifying by collecting like terms — MCQ',
    description: 'Simplifying by collecting like terms question.',
    difficulty: 3,
    generatorKind: 'algSimplifyAddMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 7,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/combine-unlike'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL007_001',
    skillId: 'AL007',
    name: 'Simplifying with brackets (distributive law) — Practice',
    description: 'Simplifying with brackets (distributive law) question.',
    difficulty: 4,
    generatorKind: 'algSimplifyMixed',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/distribute-partial', 'alg/sign-error'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL007_002',
    skillId: 'AL007',
    name: 'Simplifying with brackets (distributive law) — MCQ',
    description: 'Simplifying with brackets (distributive law) question.',
    difficulty: 4,
    generatorKind: 'algSimplifyMixedMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/distribute-partial', 'alg/sign-error'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL008_001',
    skillId: 'AL008',
    name: 'Solving one-step linear equations — Practice',
    description: 'Solving one-step linear equations question.',
    difficulty: 3,
    generatorKind: 'algEquation1Step',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 7,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/same-side-op'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL008_002',
    skillId: 'AL008',
    name: 'Solving one-step linear equations — MCQ',
    description: 'Solving one-step linear equations question.',
    difficulty: 3,
    generatorKind: 'algEquation1StepWord',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 7,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/same-side-op'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL009_001',
    skillId: 'AL009',
    name: 'Solving two-step linear equations — Practice',
    description: 'Solving two-step linear equations question.',
    difficulty: 4,
    generatorKind: 'algEquation2Step',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 12,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/order-of-undo'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL009_002',
    skillId: 'AL009',
    name: 'Solving two-step linear equations — MCQ',
    description: 'Solving two-step linear equations question.',
    difficulty: 4,
    generatorKind: 'algEquation2StepWord',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 12,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/order-of-undo'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL010_001',
    skillId: 'AL010',
    name: 'Forming and solving equations from word problems — Practice',
    description: 'Forming and solving equations from word problems question.',
    difficulty: 5,
    generatorKind: 'algWordToEquation',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 30,
    masteryTargetAccuracy: 80,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/wrong-relation'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL010_002',
    skillId: 'AL010',
    name: 'Forming and solving equations from word problems — MCQ',
    description: 'Forming and solving equations from word problems question.',
    difficulty: 5,
    generatorKind: 'algWordToEquationMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 30,
    masteryTargetAccuracy: 80,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/wrong-relation'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL001_003',
    skillId: 'AL001',
    name: 'Unknowns in arithmetic — Word Problem',
    description: 'Find the missing number from a real-world context.',
    difficulty: 3,
    generatorKind: 'algUnknownArithWord',
    recommendedQuestionCount: 15,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 10,
    misconceptionTags: ['alg/equals-means-answer'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL002_003',
    skillId: 'AL002',
    name: 'Using a letter for an unknown — Word Problem',
    description: 'Find the unknown length or quantity given a real-world context.',
    difficulty: 3,
    generatorKind: 'algUnknownLetterWord',
    recommendedQuestionCount: 15,
    fluencyTargetSeconds: 12,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 10,
    misconceptionTags: ['alg/letter-as-label', 'alg/letter-one-value'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL003_003',
    skillId: 'AL003',
    name: 'Algebraic notation — Word Problem',
    description: 'Evaluate an algebraic expression embedded in a real-world group context.',
    difficulty: 3,
    generatorKind: 'algNotationWord',
    recommendedQuestionCount: 15,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 10,
    misconceptionTags: ['alg/3n-means-3-plus-n'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL004_003',
    skillId: 'AL004',
    name: 'Forming expressions from words — Expression Answer',
    description: 'Write an algebraic expression for a comparison relationship.',
    difficulty: 4,
    generatorKind: 'algFormExpressionWord2',
    recommendedQuestionCount: 15,
    fluencyTargetSeconds: 15,
    masteryTargetAccuracy: 82,
    masteryQuestionCount: 10,
    misconceptionTags: ['alg/word-order'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL005_003',
    skillId: 'AL005',
    name: 'Substitution — Cost Context',
    description: 'Evaluate a linear expression in a tuition or pricing scenario.',
    difficulty: 4,
    generatorKind: 'algSubstituteContext',
    recommendedQuestionCount: 15,
    fluencyTargetSeconds: 12,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 10,
    misconceptionTags: ['alg/sub-no-times', 'alg/sub-ignore-precedence'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL006_003',
    skillId: 'AL006',
    name: 'Collecting like terms — Perimeter Expression',
    description: 'Write an expression for the perimeter of a rectangle with algebraic side lengths.',
    difficulty: 4,
    generatorKind: 'algSimplifyPerimeter',
    recommendedQuestionCount: 15,
    fluencyTargetSeconds: 12,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 10,
    misconceptionTags: ['alg/combine-unlike'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL007_003',
    skillId: 'AL007',
    name: 'Brackets — Total Count Word Problem',
    description: 'Evaluate k(n + c) in a boxes-of-apples context.',
    difficulty: 5,
    generatorKind: 'algBracketsWord',
    recommendedQuestionCount: 15,
    fluencyTargetSeconds: 15,
    masteryTargetAccuracy: 82,
    masteryQuestionCount: 10,
    misconceptionTags: ['alg/distribute-partial', 'alg/sign-error'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL008_003',
    skillId: 'AL008',
    name: 'One-step equations — Real-World Context',
    description: 'Form and solve a one-step equation from a real situation (addition or subtraction).',
    difficulty: 4,
    generatorKind: 'algEquation1StepContext',
    recommendedQuestionCount: 15,
    fluencyTargetSeconds: 15,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 10,
    misconceptionTags: ['alg/same-side-op'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL009_003',
    skillId: 'AL009',
    name: 'Two-step equations — Real-World Context',
    description: 'Form and solve a two-step equation from a bags-of-marbles scenario.',
    difficulty: 5,
    generatorKind: 'algEquation2StepContext',
    recommendedQuestionCount: 15,
    fluencyTargetSeconds: 18,
    masteryTargetAccuracy: 82,
    masteryQuestionCount: 10,
    misconceptionTags: ['alg/order-of-undo'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL010_003',
    skillId: 'AL010',
    name: 'Forming equations — Ratio Relationship Word Problem',
    description: 'Form and solve an equation from a ratio relationship between two quantities.',
    difficulty: 5,
    generatorKind: 'algWordToEquationHard',
    recommendedQuestionCount: 15,
    fluencyTargetSeconds: 35,
    masteryTargetAccuracy: 80,
    masteryQuestionCount: 10,
    misconceptionTags: ['alg/wrong-relation'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
];

const familyById = new Map(families.map((family) => [family.id, family]));
const familiesBySkill = families.reduce((acc, family) => {
  if (!acc[family.skillId]) acc[family.skillId] = [];
  acc[family.skillId].push(family);
  return acc;
}, {});

export function getQuestionFamily(familyId) {
  return familyById.get(familyId) || null;
}

export function getQuestionFamiliesBySkill(skillId) {
  return familiesBySkill[skillId] ? [...familiesBySkill[skillId]] : [];
}

export function getAllQuestionFamilies() {
  return [...families];
}

export const algebraQuestionFamilies = families;
export default algebraQuestionFamilies;
