import { algebraSkillGraph } from './AlgebraSkillGraph.js';

const SKILL_IDS = new Set(algebraSkillGraph.skillIds);

const families = [
  {
    id: 'QF_AL001_001',
    skillId: 'AL001',
    name: 'Unknowns in arithmetic (missing numbers) — Practice',
    description: 'Unknowns in arithmetic (missing numbers) question.',
    difficulty: 2,
    generatorKind: 'algUnknownArith',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/equals-means-answer'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL001_002',
    skillId: 'AL001',
    name: 'Unknowns in arithmetic (missing numbers) — MCQ',
    description: 'Unknowns in arithmetic (missing numbers) question.',
    difficulty: 2,
    generatorKind: 'algUnknownArithMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/equals-means-answer'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL002_001',
    skillId: 'AL002',
    name: 'Using a letter for an unknown — Practice',
    description: 'Using a letter for an unknown question.',
    difficulty: 2,
    generatorKind: 'algUnknownLetter',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/letter-as-label', 'alg/letter-one-value'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL002_002',
    skillId: 'AL002',
    name: 'Using a letter for an unknown — MCQ',
    description: 'Using a letter for an unknown question.',
    difficulty: 2,
    generatorKind: 'algUnknownLetterMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/letter-as-label', 'alg/letter-one-value'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL003_001',
    skillId: 'AL003',
    name: 'Algebraic notation — Practice',
    description: 'Algebraic notation question.',
    difficulty: 2,
    generatorKind: 'algNotation',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/3n-means-3-plus-n'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL003_002',
    skillId: 'AL003',
    name: 'Algebraic notation — MCQ',
    description: 'Algebraic notation question.',
    difficulty: 2,
    generatorKind: 'algNotationMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/3n-means-3-plus-n'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL004_001',
    skillId: 'AL004',
    name: 'Forming expressions from words — Practice',
    description: 'Forming expressions from words question.',
    difficulty: 3,
    generatorKind: 'algFormExpression',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 12,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/word-order'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL004_002',
    skillId: 'AL004',
    name: 'Forming expressions from words — MCQ',
    description: 'Forming expressions from words question.',
    difficulty: 3,
    generatorKind: 'algFormExpressionMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 12,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/word-order'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL005_001',
    skillId: 'AL005',
    name: 'Substitution (evaluating expressions) — Practice',
    description: 'Substitution (evaluating expressions) question.',
    difficulty: 3,
    generatorKind: 'algSubstitute',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/sub-no-times', 'alg/sub-ignore-precedence'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL005_002',
    skillId: 'AL005',
    name: 'Substitution (evaluating expressions) — MCQ',
    description: 'Substitution (evaluating expressions) question.',
    difficulty: 3,
    generatorKind: 'algSubstituteWord',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/sub-no-times', 'alg/sub-ignore-precedence'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL006_001',
    skillId: 'AL006',
    name: 'Simplifying by collecting like terms — Practice',
    description: 'Simplifying by collecting like terms question.',
    difficulty: 3,
    generatorKind: 'algSimplifyAdd',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 7,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/combine-unlike'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL006_002',
    skillId: 'AL006',
    name: 'Simplifying by collecting like terms — MCQ',
    description: 'Simplifying by collecting like terms question.',
    difficulty: 3,
    generatorKind: 'algSimplifyAddMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 7,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/combine-unlike'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL007_001',
    skillId: 'AL007',
    name: 'Simplifying with brackets (distributive law) — Practice',
    description: 'Simplifying with brackets (distributive law) question.',
    difficulty: 4,
    generatorKind: 'algSimplifyMixed',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/distribute-partial', 'alg/sign-error'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL007_002',
    skillId: 'AL007',
    name: 'Simplifying with brackets (distributive law) — MCQ',
    description: 'Simplifying with brackets (distributive law) question.',
    difficulty: 4,
    generatorKind: 'algSimplifyMixedMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/distribute-partial', 'alg/sign-error'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL008_001',
    skillId: 'AL008',
    name: 'Solving one-step linear equations — Practice',
    description: 'Solving one-step linear equations question.',
    difficulty: 3,
    generatorKind: 'algEquation1Step',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 7,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/same-side-op'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL008_002',
    skillId: 'AL008',
    name: 'Solving one-step linear equations — MCQ',
    description: 'Solving one-step linear equations question.',
    difficulty: 3,
    generatorKind: 'algEquation1StepWord',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 7,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/same-side-op'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL009_001',
    skillId: 'AL009',
    name: 'Solving two-step linear equations — Practice',
    description: 'Solving two-step linear equations question.',
    difficulty: 4,
    generatorKind: 'algEquation2Step',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 12,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/order-of-undo'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL009_002',
    skillId: 'AL009',
    name: 'Solving two-step linear equations — MCQ',
    description: 'Solving two-step linear equations question.',
    difficulty: 4,
    generatorKind: 'algEquation2StepWord',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 12,
    masteryTargetAccuracy: 85,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/order-of-undo'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL010_001',
    skillId: 'AL010',
    name: 'Forming and solving equations from word problems — Practice',
    description: 'Forming and solving equations from word problems question.',
    difficulty: 5,
    generatorKind: 'algWordToEquation',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 30,
    masteryTargetAccuracy: 80,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/wrong-relation'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_AL010_002',
    skillId: 'AL010',
    name: 'Forming and solving equations from word problems — MCQ',
    description: 'Forming and solving equations from word problems question.',
    difficulty: 5,
    generatorKind: 'algWordToEquationMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 30,
    masteryTargetAccuracy: 80,
    masteryQuestionCount: 12,
    misconceptionTags: ['alg/wrong-relation'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },

  // ── Secondary 1 (G1) — Algebra ──────────────────────────────────────────────
  { id: 'QF_AL011_001', skillId: 'AL011', name: 'Simplifying linear expressions — Practice', description: 'Collect like terms.', difficulty: 3, generatorKind: 'algSimplifyLinear', recommendedQuestionCount: 20, fluencyTargetSeconds: 12, masteryTargetAccuracy: 85, masteryQuestionCount: 12, misconceptionTags: ['alg/combine-unlike'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_AL011_002', skillId: 'AL011', name: 'Simplifying linear expressions — MCQ', description: 'Collect like terms.', difficulty: 3, generatorKind: 'algSimplifyLinearMCQ', recommendedQuestionCount: 20, fluencyTargetSeconds: 12, masteryTargetAccuracy: 85, masteryQuestionCount: 12, misconceptionTags: ['alg/combine-unlike'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_AL012_001', skillId: 'AL012', name: 'Expanding single brackets — Practice', description: 'Expand a single bracket.', difficulty: 4, generatorKind: 'algExpandBrackets', recommendedQuestionCount: 20, fluencyTargetSeconds: 14, masteryTargetAccuracy: 82, masteryQuestionCount: 12, misconceptionTags: ['alg/distribute-partial'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_AL012_002', skillId: 'AL012', name: 'Expanding single brackets — MCQ', description: 'Expand a single bracket.', difficulty: 4, generatorKind: 'algExpandBracketsMCQ', recommendedQuestionCount: 20, fluencyTargetSeconds: 14, masteryTargetAccuracy: 82, masteryQuestionCount: 12, misconceptionTags: ['alg/distribute-partial'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_AL013_001', skillId: 'AL013', name: 'Solving two-step equations — Practice', description: 'Solve ax + b = c.', difficulty: 4, generatorKind: 'algSolveTwoStep', recommendedQuestionCount: 20, fluencyTargetSeconds: 18, masteryTargetAccuracy: 82, masteryQuestionCount: 12, misconceptionTags: ['alg/order-of-undo'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_AL013_002', skillId: 'AL013', name: 'Solving two-step equations — MCQ', description: 'Solve ax + b = c.', difficulty: 4, generatorKind: 'algSolveTwoStepMCQ', recommendedQuestionCount: 20, fluencyTargetSeconds: 18, masteryTargetAccuracy: 82, masteryQuestionCount: 12, misconceptionTags: ['alg/order-of-undo'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_AL014_001', skillId: 'AL014', name: 'Solving equations with brackets — Practice', description: 'Solve a(x + b) = c.', difficulty: 4, generatorKind: 'algSolveBrackets', recommendedQuestionCount: 20, fluencyTargetSeconds: 22, masteryTargetAccuracy: 80, masteryQuestionCount: 12, misconceptionTags: ['alg/distribute-partial'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_AL014_002', skillId: 'AL014', name: 'Solving equations with brackets — MCQ', description: 'Solve a(x + b) = c.', difficulty: 4, generatorKind: 'algSolveBracketsMCQ', recommendedQuestionCount: 20, fluencyTargetSeconds: 22, masteryTargetAccuracy: 80, masteryQuestionCount: 12, misconceptionTags: ['alg/distribute-partial'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_AL015_001', skillId: 'AL015', name: 'Substitution with negative values — Practice', description: 'Evaluate with negative integers.', difficulty: 4, generatorKind: 'algSubstituteNeg', recommendedQuestionCount: 20, fluencyTargetSeconds: 16, masteryTargetAccuracy: 82, masteryQuestionCount: 12, misconceptionTags: ['alg/sign-error'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_AL015_002', skillId: 'AL015', name: 'Substitution with negative values — MCQ', description: 'Evaluate with negative integers.', difficulty: 4, generatorKind: 'algSubstituteNegMCQ', recommendedQuestionCount: 20, fluencyTargetSeconds: 16, masteryTargetAccuracy: 82, masteryQuestionCount: 12, misconceptionTags: ['alg/sign-error'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_AL016_001', skillId: 'AL016', name: 'Forming and solving equations — Practice', description: 'Form and solve a linear equation.', difficulty: 5, generatorKind: 'algFormSolve', recommendedQuestionCount: 20, fluencyTargetSeconds: 30, masteryTargetAccuracy: 80, masteryQuestionCount: 12, misconceptionTags: ['alg/wrong-relation'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_AL016_002', skillId: 'AL016', name: 'Forming and solving equations — MCQ', description: 'Form and solve a linear equation.', difficulty: 5, generatorKind: 'algFormSolveMCQ', recommendedQuestionCount: 20, fluencyTargetSeconds: 30, masteryTargetAccuracy: 80, masteryQuestionCount: 12, misconceptionTags: ['alg/wrong-relation'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
];

const familyById = new Map(families.map((family) => [family.id, family]));
const familiesBySkill = families.reduce((acc, family) => {
  if (!acc[family.skillId]) acc[family.skillId] = [];
  acc[family.skillId].push(family);
  return acc;
}, {});

export function getQuestionFamily(familyId) {
  return familyById.get(familyId) || null;
}

export function getQuestionFamiliesBySkill(skillId) {
  return familiesBySkill[skillId] ? [...familiesBySkill[skillId]] : [];
}

export function getAllQuestionFamilies() {
  return [...families];
}

export const algebraQuestionFamilies = families;
export default algebraQuestionFamilies;
