const misconceptions = [
  { tag: 'confuses_factors_and_multiples', label: 'Mixes up factors and multiples', description: 'Lists multiples when asked for factors or vice versa.', remediationExplanation: 'Factors DIVIDE INTO the number (smaller or equal). Multiples are the TIMES TABLE (bigger or equal). Factors of 6: 1, 2, 3, 6. Multiples of 6: 6, 12, 18...', visualScaffold: 'factor_vs_multiple_table', recheckPattern: 'List factors of 12, then first 5 multiples of 12.', parentNote: 'Mnemonic: Factors are Few and Finite, Multiples are Many and go on forever.', relatedSkills: ['P4-FM-01', 'P4-FM-02'] },
  { tag: 'misses_factor_pair', label: 'Misses one or more factor pairs', description: 'Lists some but not all factors, e.g. forgets 8 and 12 for 24.', remediationExplanation: 'Use systematic factor pairs: 1\u00d724, 2\u00d712, 3\u00d78, 4\u00d76. Stop when pairs meet.', visualScaffold: 'factor_rainbow', recheckPattern: 'Find ALL factors of 36 using factor pairs.', parentNote: 'Draw a factor rainbow connecting pairs that multiply to make the number.', relatedSkills: ['P4-FM-01'] },
  { tag: 'forgets_1_is_a_factor', label: 'Forgets 1 is always a factor', description: 'Starts listing from 2 instead of 1.', remediationExplanation: '1 is a factor of every number. The number itself is also always a factor.', visualScaffold: 'factor_checklist', recheckPattern: 'List all factors of 15 starting from 1.', parentNote: 'Every number has at least 2 factors: 1 and itself.', relatedSkills: ['P4-FM-01'] },
  { tag: 'multiplies_instead_of_finding_lcm', label: 'Multiplies the two numbers instead of finding LCM', description: 'For LCM of 4 and 6, writes 24 (4\u00d76) instead of 12.', remediationExplanation: 'The LCM is the SMALLEST number both divide into. List multiples until you find the first match.', visualScaffold: 'multiple_number_line', recheckPattern: 'Find LCM of 6 and 8 by listing multiples.', parentNote: 'Multiplying only gives LCM when the numbers share no common factor.', relatedSkills: ['P4-FM-02'] },
  { tag: 'stops_listing_too_early', label: 'Stops listing multiples too early', description: 'Misses common multiples further along the sequence.', remediationExplanation: 'Keep listing until the limit. Common multiples of 4 and 6 up to 36: 12, 24, 36.', visualScaffold: 'multiple_list_extended', recheckPattern: 'List all common multiples of 3 and 5 up to 60.', parentNote: 'List multiples side by side in a table and circle shared ones.', relatedSkills: ['P4-FM-02'] },
];

const byTag = new Map(misconceptions.map((m) => [m.tag, m]));
export function getMisconception(tag) { return byTag.get(tag) || null; }
export function getMisconceptionsForSkill(skillId) { return misconceptions.filter((m) => m.relatedSkills.includes(skillId)); }
export function getAllMisconceptions() { return [...misconceptions]; }
export function getRemediationForTag(tag) { const m = byTag.get(tag); if (!m) return null; return { tag: m.tag, explanation: m.remediationExplanation, visualScaffold: m.visualScaffold, recheckPattern: m.recheckPattern, parentNote: m.parentNote }; }
export default { getMisconception, getMisconceptionsForSkill, getAllMisconceptions, getRemediationForTag };
