const misconceptions = [
  { tag: 'mixed_to_improper_add_error', label: 'Adds whole and numerator without multiplying', description: 'For 2 1/3, writes 3/3 instead of 7/3.', remediationExplanation: 'Multiply whole by denominator FIRST, then add numerator. 2 1/3: 2×3=6, 6+1=7, so 7/3.', visualScaffold: 'fraction_circle_mixed', recheckPattern: 'Convert 3 2/5 to improper.', parentNote: 'Use (whole × denom) + numerator.', relatedSkills: ['P4-FR-01'] },
  { tag: 'improper_to_mixed_remainder_error', label: 'Confuses quotient and remainder', description: 'For 11/4, writes 4 3/4 instead of 2 3/4.', remediationExplanation: '11÷4 = 2 rem 3. Quotient=whole, remainder=new numerator.', visualScaffold: 'fraction_division_layout', recheckPattern: 'Convert 17/5 to mixed.', parentNote: 'Quotient = whole number, remainder over original denominator.', relatedSkills: ['P4-FR-01'] },
  { tag: 'fraction_of_set_divides_by_numerator', label: 'Divides by numerator instead of denominator', description: 'For 3/4 of 20, divides by 3 instead of 4.', remediationExplanation: 'Divide by denominator first, multiply by numerator. 20÷4=5, 5×3=15.', visualScaffold: 'bar_model_fraction', recheckPattern: 'Find 2/5 of 30.', parentNote: 'Bar model: split into denom parts, shade numer parts.', relatedSkills: ['P4-FR-02'] },
  { tag: 'fraction_of_set_forgets_multiply', label: 'Forgets to multiply by numerator', description: 'For 3/4 of 20, gives 5 instead of 15.', remediationExplanation: '1/4 of 20 = 5, so 3/4 = 5×3 = 15.', visualScaffold: 'bar_model_fraction', recheckPattern: 'Find 3/5 of 25.', parentNote: '"One part is 5. How many parts?" 3 parts = 15.', relatedSkills: ['P4-FR-02'] },
  { tag: 'adds_denominators', label: 'Adds denominators when adding fractions', description: '1/3 + 1/4 = 2/7 instead of 7/12.', remediationExplanation: 'Rewrite over LCD, then add only numerators.', visualScaffold: 'fraction_bar_lcd', recheckPattern: 'Add 1/2 + 1/3.', parentNote: 'Fraction strips show pieces must be same size.', relatedSkills: ['P4-FR-03'] },
  { tag: 'wrong_common_denominator', label: 'Wrong common denominator', description: 'Picks non-multiple of both denominators.', remediationExplanation: 'LCD is smallest number both divide into. For 3 and 4, LCD=12.', visualScaffold: 'lcd_factor_tree', recheckPattern: 'Find LCD of 4 and 6.', parentNote: 'List multiples until first match.', relatedSkills: ['P4-FR-03'] },
  { tag: 'forgets_to_simplify', label: 'Forgets to simplify', description: 'Gets 8/12 but does not simplify to 2/3.', remediationExplanation: 'Divide both by GCD. 8/12: GCD=4, 8÷4=2, 12÷4=3.', visualScaffold: 'simplification_arrows', recheckPattern: 'Simplify 6/9.', parentNote: '"Can you divide top and bottom by same number?"', relatedSkills: ['P4-FR-03'] },
];
const byTag = new Map(misconceptions.map((m) => [m.tag, m]));
export function getMisconception(tag) { return byTag.get(tag) || null; }
export function getMisconceptionsForSkill(sid) { return misconceptions.filter((m) => m.relatedSkills.includes(sid)); }
export function getAllMisconceptions() { return [...misconceptions]; }
export function getRemediationForTag(tag) { const m = byTag.get(tag); if (!m) return null; return { tag: m.tag, explanation: m.remediationExplanation, visualScaffold: m.visualScaffold, recheckPattern: m.recheckPattern, parentNote: m.parentNote }; }
export default { getMisconception, getMisconceptionsForSkill, getAllMisconceptions, getRemediationForTag };
