const misconceptions = [
  { tag: 'multiplies_whole_but_forgets_numerator', label: 'Multiplies whole but forgets to add the numerator', description: 'For 2 3/5, writes 10/5 instead of 13/5 (forgets to add the 3).', remediationExplanation: 'To convert a mixed number: multiply the whole number by the denominator, then ADD the numerator on top. 2 3/5 → 2×5=10, then 10+3=13, so 13/5.', visualScaffold: 'mixed_to_improper_steps', recheckPattern: 'Convert 3 2/7 to an improper fraction.', parentNote: 'Remind your child: multiply, then ADD the top number.', relatedSkills: ['P4-FR-01'] },
  { tag: 'divides_set_by_numerator_not_denominator', label: 'Divides the set by the numerator instead of the denominator', description: 'For 3/4 of 20, divides 20 by 3 instead of 4.', remediationExplanation: 'The denominator tells you how many equal groups. Divide the set by the denominator first, then multiply by the numerator. 3/4 of 20: 20÷4=5, then 5×3=15.', visualScaffold: 'fraction_of_set_groups', recheckPattern: 'Find 2/5 of 30.', parentNote: 'The bottom number (denominator) is the number of groups. Divide first, then multiply.', relatedSkills: ['P4-FR-02'] },
  { tag: 'adds_unlike_numerators_directly', label: 'Adds numerators without finding a common denominator', description: 'For 1/3 + 1/4, writes 2/7 instead of 7/12.', remediationExplanation: 'You cannot add fractions with different denominators directly. First find the LCD and rename both fractions. 1/3 + 1/4: LCD=12, so 4/12 + 3/12 = 7/12.', visualScaffold: 'fraction_bar_rename', recheckPattern: 'Add 1/2 + 1/5.', parentNote: 'The denominators must be the same before adding. Find the lowest common denominator first.', relatedSkills: ['P4-FR-03'] },
  { tag: 'wrong_lcd', label: 'Uses an incorrect LCD', description: 'Picks a common multiple that is not the lowest, or picks an incorrect value altogether.', remediationExplanation: 'The LCD is the smallest number both denominators divide into evenly. For 1/4 and 1/6, the LCD is 12 (not 24). List multiples of each denominator until you find the first match.', visualScaffold: 'lcd_multiple_list', recheckPattern: 'Find the LCD of 6 and 8, then add 1/6 + 3/8.', parentNote: 'List multiples of each denominator side by side and circle the smallest shared one.', relatedSkills: ['P4-FR-03'] },
  { tag: 'forgets_to_rename_both_fractions', label: 'Renames only one fraction before adding or subtracting', description: 'Converts one fraction to the LCD but leaves the other unchanged.', remediationExplanation: 'Both fractions must be renamed to have the LCD as denominator. For 1/3 + 1/4 with LCD 12: 1/3 becomes 4/12 AND 1/4 becomes 3/12.', visualScaffold: 'fraction_rename_both', recheckPattern: 'Subtract 3/4 − 1/6 using the LCD.', parentNote: 'Check that BOTH fractions have been rewritten with the new denominator.', relatedSkills: ['P4-FR-03'] },
];

const byTag = new Map(misconceptions.map((m) => [m.tag, m]));
export function getMisconception(tag) { return byTag.get(tag) || null; }
export function getMisconceptionsForSkill(skillId) { return misconceptions.filter((m) => m.relatedSkills.includes(skillId)); }
export function getAllMisconceptions() { return [...misconceptions]; }
export function getRemediationForTag(tag) { const m = byTag.get(tag); if (!m) return null; return { tag: m.tag, explanation: m.remediationExplanation, visualScaffold: m.visualScaffold, recheckPattern: m.recheckPattern, parentNote: m.parentNote }; }
export default { getMisconception, getMisconceptionsForSkill, getAllMisconceptions, getRemediationForTag };
