const misconceptions = [
  {
    tag: 'confuses_place_columns_5digit',
    label: 'Mixes up ten thousands, thousands, hundreds, tens, ones columns',
    description: 'Assigns a digit to the wrong place value in a 5-digit number, e.g. reads 34 052 as "3 thousands, 4 ten thousands".',
    remediationExplanation: 'Read from left to right: the leftmost digit in a 5-digit number is ten thousands, then thousands, then hundreds, then tens, then ones. Use a place-value chart with five columns.',
    visualScaffold: 'place_value_chart_5digit',
    recheckPattern: 'Write the value of the underlined digit in a 5-digit number.',
    parentNote: 'Draw a place-value table (TTh | Th | H | T | O) and have your child place digits into the correct columns. Practise with house numbers or distances.',
    relatedSkills: ['P4-WN-01'],
  },
  {
    tag: 'zero_placeholder_error_5digit',
    label: 'Drops or ignores zero placeholders in 5-digit numbers',
    description: 'Writes 4052 instead of 40 052 or reads 30 500 as "three thousand and five hundred" because the zero placeholder is skipped.',
    remediationExplanation: 'Zero means "none of that place value" but it still holds the place. 30 500 = 3 ten thousands, 0 thousands, 5 hundreds, 0 tens, 0 ones. Every column must be filled.',
    visualScaffold: 'place_value_blocks_with_zero_5digit',
    recheckPattern: 'Write the number: 4 ten thousands, 0 thousands, 0 hundreds, 5 tens, 2 ones.',
    parentNote: 'Emphasise that zero is a placeholder. Ask: "What happens if we remove the zero from 30 500? Does the number change?" Show with place-value discs.',
    relatedSkills: ['P4-WN-01'],
  },
  {
    tag: 'compares_digit_by_digit_wrong_order_5digit',
    label: 'Compares digits starting from the ones instead of ten thousands',
    description: 'Begins comparison at the rightmost digit, concluding that 24 899 > 31 002 because 9 > 2.',
    remediationExplanation: 'Always compare the leftmost (largest) place value first. If the ten thousands digit is bigger, the whole number is bigger.',
    visualScaffold: 'comparison_place_value_arrows_5digit',
    recheckPattern: 'Compare two 5-digit numbers and explain which place decided it.',
    parentNote: 'Line numbers up in a place-value table and compare column by column from the left. The first column that differs decides the answer.',
    relatedSkills: ['P4-WN-02'],
  },
  {
    tag: 'confuses_more_less_symbols_5digit',
    label: 'Mixes up > and < symbols',
    description: 'Uses the wrong comparison symbol, e.g. writes 34 710 > 52 100 instead of 34 710 < 52 100.',
    remediationExplanation: 'The symbol always opens toward the bigger number. Think of a hungry crocodile eating the larger number.',
    visualScaffold: 'crocodile_comparison',
    recheckPattern: 'Compare two new 5-digit numbers using > or <.',
    parentNote: 'Draw a crocodile mouth that always opens toward the bigger number. Practise with prices, distances, or population figures.',
    relatedSkills: ['P4-WN-02'],
  },
  {
    tag: 'pattern_step_error_large',
    label: 'Uses the wrong step size in a large-number pattern',
    description: 'Misidentifies the constant difference, e.g. sees 15 000, 17 500, 20 000 and thinks the step is 2 000 instead of 2 500.',
    remediationExplanation: 'Subtract any two consecutive terms to find the step. Check your step works for every pair.',
    visualScaffold: 'number_line_jumps_large',
    recheckPattern: 'Find the step and continue the pattern.',
    parentNote: 'Ask your child to subtract consecutive terms and check the difference is the same each time. Practise with steps of 100, 250, 500, 1 000, 2 500.',
    relatedSkills: ['P4-WN-03'],
  },
  {
    tag: 'pattern_direction_error_large',
    label: 'Continues a decreasing pattern by adding instead of subtracting',
    description: 'Sees a sequence going down (80 000, 75 000, 70 000) but adds the step instead of subtracting.',
    remediationExplanation: 'Check whether the numbers are getting bigger or smaller. If they are getting smaller, subtract the step to find the next term.',
    visualScaffold: 'number_line_arrows_large',
    recheckPattern: 'Continue a decreasing number pattern.',
    parentNote: 'Ask: "Are the numbers going up or down?" before finding the next number. Practise with both increasing and decreasing patterns.',
    relatedSkills: ['P4-WN-03'],
  },
  {
    tag: 'rounds_wrong_direction',
    label: 'Rounds down when the deciding digit is 5 or more, or rounds up when below 5',
    description: 'Rounds 4 385 to the nearest 10 as 4 380 instead of 4 390 because the child thinks 5 rounds down.',
    remediationExplanation: 'Look at the digit just below the rounding place. If it is 5 or more, round up. If it is less than 5, round down. 5 always rounds UP.',
    visualScaffold: 'rounding_number_line',
    recheckPattern: 'Round a number with a 5 in the deciding position.',
    parentNote: 'Use a number line to show the number is exactly halfway or past halfway when the digit is 5. Halfway rounds up.',
    relatedSkills: ['P4-WN-04'],
  },
  {
    tag: 'rounds_wrong_place',
    label: 'Looks at the wrong digit when rounding',
    description: 'When rounding to the nearest 100, looks at the ones digit instead of the tens digit.',
    remediationExplanation: 'To round to a place, look at the digit ONE PLACE TO THE RIGHT. Rounding to 100? Look at the tens digit. Rounding to 1 000? Look at the hundreds digit.',
    visualScaffold: 'rounding_place_highlight',
    recheckPattern: 'Round a number to the nearest 100 and explain which digit you checked.',
    parentNote: 'Underline the rounding place, then circle the digit to its right. That circled digit decides up or down.',
    relatedSkills: ['P4-WN-04'],
  },
  {
    tag: 'truncates_instead_of_rounding',
    label: 'Truncates (chops off digits) instead of rounding',
    description: 'Rounds 4 387 to the nearest 10 as 4 380 by simply removing the ones digit, ignoring the rounding rule.',
    remediationExplanation: 'Rounding is not just removing digits. Check the digit to the right of the rounding place: if it is 5 or more, you must add 1 to the rounding place before zeroing the rest.',
    visualScaffold: 'rounding_vs_truncating',
    recheckPattern: 'Round a number where the deciding digit is 5 or more.',
    parentNote: 'Show the difference: truncating 4 387 to tens gives 4 380, but rounding gives 4 390. Always check the digit to the right.',
    relatedSkills: ['P4-WN-04'],
  },
];

const byTag = new Map(misconceptions.map((m) => [m.tag, m]));
export function getMisconception(tag) { return byTag.get(tag) || null; }
export function getMisconceptionsForSkill(skillId) { return misconceptions.filter((m) => m.relatedSkills.includes(skillId)); }
export function getAllMisconceptions() { return [...misconceptions]; }
export function getRemediationForTag(tag) { const m = byTag.get(tag); if (!m) return null; return { tag: m.tag, explanation: m.remediationExplanation, visualScaffold: m.visualScaffold, recheckPattern: m.recheckPattern, parentNote: m.parentNote }; }
export default { getMisconception, getMisconceptionsForSkill, getAllMisconceptions, getRemediationForTag };
