const misconceptions = [
  { tag: 'forgets_half_for_triangle_area', label: 'Forgets to halve for triangle area', description: 'Calculates base × height without dividing by 2, giving double the correct area.', remediationExplanation: 'A triangle is exactly HALF of a rectangle with the same base and height. Always use: Area = 1/2 × base × height.', visualScaffold: 'triangle_in_rectangle', recheckPattern: 'Find the area of a triangle with base 10 cm and height 6 cm.', parentNote: 'Draw a rectangle around the triangle to show it fills exactly half.', relatedSkills: ['P5-AV-01', 'P5-AV-03'] },
  { tag: 'confuses_base_and_height', label: 'Confuses base and height', description: 'Uses a slant side instead of the perpendicular height, or picks the wrong pair of dimensions.', remediationExplanation: 'The HEIGHT must be perpendicular (at 90°) to the BASE. Look for the right-angle marker to identify the correct height.', visualScaffold: 'base_height_indicator', recheckPattern: 'Identify the base and height of a triangle where the height is drawn inside.', parentNote: 'The height always makes a right angle with the base — look for the small square symbol.', relatedSkills: ['P5-AV-01'] },
  { tag: 'confuses_area_and_perimeter', label: 'Confuses area and perimeter', description: 'Adds side lengths (perimeter) when asked for area, or multiplies when asked for perimeter.', remediationExplanation: 'AREA measures the space inside (multiply, use cm²). PERIMETER measures the distance around (add all sides, use cm).', visualScaffold: 'area_vs_perimeter_compare', recheckPattern: 'Find the area AND perimeter of a rectangle 8 cm by 5 cm.', parentNote: 'Area = space inside (cm²), Perimeter = fence around (cm). Different operations, different units.', relatedSkills: ['P5-AV-01', 'P5-AV-03'] },
  { tag: 'uses_wrong_volume_formula', label: 'Uses wrong volume formula', description: 'Calculates surface area or uses length × width instead of length × width × height for volume.', remediationExplanation: 'Volume counts how many unit cubes fit inside. You need THREE dimensions: Volume = length × width × height. For a cube: side × side × side.', visualScaffold: 'unit_cube_filling', recheckPattern: 'Find the volume of a cuboid 5 cm × 3 cm × 4 cm.', parentNote: 'Volume needs all three dimensions multiplied. If the child only multiplies two, they are finding an area of one face.', relatedSkills: ['P5-AV-02', 'P5-AV-03'] },
  { tag: 'adds_dimensions_instead_of_multiplying', label: 'Adds dimensions instead of multiplying', description: 'Adds length + width + height instead of multiplying them to find volume.', remediationExplanation: 'Volume uses MULTIPLICATION, not addition. Think of stacking layers: each layer has length × width unit cubes, stacked height times.', visualScaffold: 'layer_stacking', recheckPattern: 'A box is 4 cm × 3 cm × 2 cm. Is the volume 9 or 24?', parentNote: 'Adding gives perimeter-like values. Volume always multiplies the three dimensions.', relatedSkills: ['P5-AV-02', 'P5-AV-03'] },
];

const byTag = new Map(misconceptions.map((m) => [m.tag, m]));
export function getMisconception(tag) { return byTag.get(tag) || null; }
export function getMisconceptionsForSkill(skillId) { return misconceptions.filter((m) => m.relatedSkills.includes(skillId)); }
export function getAllMisconceptions() { return [...misconceptions]; }
export function getRemediationForTag(tag) { const m = byTag.get(tag); if (!m) return null; return { tag: m.tag, explanation: m.remediationExplanation, visualScaffold: m.visualScaffold, recheckPattern: m.recheckPattern, parentNote: m.parentNote }; }
export default { getMisconception, getMisconceptionsForSkill, getAllMisconceptions, getRemediationForTag };
