const misconceptions = [
  { tag: 'ignores_decimal_point_in_comparison', label: 'Ignores decimal point when comparing', description: 'Treats digits after the decimal as a whole number, e.g. thinks 3.12 > 3.9 because 12 > 9.', remediationExplanation: 'Compare digit by digit from left to right. 3.9 has 9 tenths while 3.12 has only 1 tenth, so 3.9 > 3.12.', visualScaffold: 'place_value_chart', recheckPattern: 'Which is greater: 4.8 or 4.15? Explain your reasoning.', parentNote: 'Use a place-value chart so they compare tenths with tenths, hundredths with hundredths.', relatedSkills: ['P5-DEC-01'] },
  { tag: 'misaligns_decimal_points_adding', label: 'Misaligns decimal points when adding or subtracting', description: 'Lines up numbers from the right ignoring the decimal point, e.g. 3.4 + 2.15 treated as 34 + 215.', remediationExplanation: 'Always line up the decimal points first. Fill empty places with zeros: 3.40 + 2.15.', visualScaffold: 'column_addition_grid', recheckPattern: 'Calculate 5.3 + 2.78. Show your working with decimal points aligned.', parentNote: 'Use squared paper to keep each digit in its own column with the decimal point aligned.', relatedSkills: ['P5-DEC-02'] },
  { tag: 'moves_decimal_wrong_direction_multiplying', label: 'Moves decimal point the wrong direction', description: 'When multiplying, moves the decimal left instead of right, or vice versa when dividing.', remediationExplanation: 'Multiplying makes numbers bigger, so the decimal moves right. Dividing makes numbers smaller, so the decimal moves left. Alternatively, count the total decimal places in the factors.', visualScaffold: 'decimal_shift_arrows', recheckPattern: 'Calculate 2.4 × 3 and 7.2 ÷ 4.', parentNote: 'Practise estimating first: 2.4 × 3 should be near 2 × 3 = 6.', relatedSkills: ['P5-DEC-02'] },
  { tag: 'forgets_trailing_zeros', label: 'Drops or adds trailing zeros incorrectly', description: 'Writes 0.5 as 0.50 when it changes meaning, or drops a meaningful zero like writing 0.30 as 0.3 when the context requires 2dp.', remediationExplanation: 'Trailing zeros after the last non-zero decimal digit do not change the value: 0.5 = 0.50 = 0.500. However, when a question asks to round to 2 decimal places, include both decimal places.', visualScaffold: 'number_line_zoom', recheckPattern: 'Round 3.204 to 2 decimal places and round 7.101 to 1 decimal place.', parentNote: 'Emphasise that the number of decimal places in the answer must match what the question asks for.', relatedSkills: ['P5-DEC-01', 'P5-DEC-02', 'P5-DEC-03'] },
  { tag: 'confuses_fraction_decimal_conversion', label: 'Confuses fraction-decimal conversion', description: 'Writes the numerator and denominator side by side instead of dividing, e.g. converts 3/4 to 3.4 instead of 0.75.', remediationExplanation: 'To convert a fraction to a decimal, divide the numerator by the denominator: 3 ÷ 4 = 0.75. To convert a decimal to a fraction, put the decimal digits over the matching place value (e.g. 0.75 = 75/100) and simplify.', visualScaffold: 'fraction_bar_with_decimal', recheckPattern: 'Convert 3/8 to a decimal and convert 0.6 to a fraction in simplest form.', parentNote: 'Drill the common fraction-decimal pairs: 1/2=0.5, 1/4=0.25, 3/4=0.75, 1/5=0.2, 1/8=0.125.', relatedSkills: ['P5-DEC-03'] },
];

const byTag = new Map(misconceptions.map((m) => [m.tag, m]));
export function getMisconception(tag) { return byTag.get(tag) || null; }
export function getMisconceptionsForSkill(skillId) { return misconceptions.filter((m) => m.relatedSkills.includes(skillId)); }
export function getAllMisconceptions() { return [...misconceptions]; }
export function getRemediationForTag(tag) { const m = byTag.get(tag); if (!m) return null; return { tag: m.tag, explanation: m.remediationExplanation, visualScaffold: m.visualScaffold, recheckPattern: m.recheckPattern, parentNote: m.parentNote }; }
export default { getMisconception, getMisconceptionsForSkill, getAllMisconceptions, getRemediationForTag };
