const misconceptions = [
  { tag: 'adds_numerators_and_denominators', label: 'Adds both numerators and denominators', description: 'Adds numerators and denominators separately, e.g. 1/3 + 1/4 = 2/7 instead of 7/12.', remediationExplanation: 'You cannot add denominators. Find a common denominator first, then add only the numerators. 1/3 + 1/4: LCD is 12. 4/12 + 3/12 = 7/12.', visualScaffold: 'fraction_bar_model', recheckPattern: 'Compute 1/3 + 1/5 by finding the LCD first.', parentNote: 'Use fraction bars or pizza slices to show that the pieces must be the same size before combining.', relatedSkills: ['P5-FR-01', 'P5-FR-03'] },
  { tag: 'forgets_to_find_lcd', label: 'Forgets to find the LCD', description: 'Tries to add or subtract fractions without converting to a common denominator.', remediationExplanation: 'Before adding or subtracting fractions with different denominators, convert them to equivalent fractions with the same denominator (LCD). Find the LCD by listing multiples of both denominators.', visualScaffold: 'lcd_number_line', recheckPattern: 'Convert 2/3 and 3/5 to equivalent fractions with the same denominator.', parentNote: 'Have your child list multiples of each denominator side by side to find the smallest shared one.', relatedSkills: ['P5-FR-01'] },
  { tag: 'wrong_mixed_number_conversion', label: 'Incorrectly converts mixed numbers', description: 'Makes errors converting between mixed numbers and improper fractions, e.g. 2 1/3 becomes 3/3 instead of 7/3.', remediationExplanation: 'To convert a mixed number to an improper fraction: multiply the whole number by the denominator, add the numerator. 2 1/3 = (2 × 3 + 1)/3 = 7/3.', visualScaffold: 'mixed_number_area_model', recheckPattern: 'Convert 3 2/5 to an improper fraction, then convert 11/4 to a mixed number.', parentNote: 'Practice the pattern: whole × denominator + numerator over denominator. Use objects grouped in sets to visualise.', relatedSkills: ['P5-FR-01', 'P5-FR-02'] },
  { tag: 'multiplies_whole_by_both_num_and_den', label: 'Multiplies whole by both numerator and denominator', description: 'When finding a fraction of a whole, multiplies the whole by both parts, e.g. 2/3 of 12 = (2×12)/(3×12).', remediationExplanation: 'To find a fraction of a whole: divide the whole by the denominator, then multiply by the numerator. 2/3 of 12: 12 ÷ 3 = 4, then 4 × 2 = 8.', visualScaffold: 'fraction_of_whole_groups', recheckPattern: 'Find 3/4 of 20 by dividing into 4 groups first.', parentNote: 'Use physical objects: split into groups equal to the denominator, then count groups equal to the numerator.', relatedSkills: ['P5-FR-02', 'P5-FR-03'] },
  { tag: 'inverts_wrong_fraction_in_division', label: 'Inverts the wrong fraction when dividing', description: 'Flips the dividend instead of the divisor, e.g. 6 ÷ 2/3 becomes 6 × 2/3 instead of 6 × 3/2.', remediationExplanation: 'When dividing by a fraction, flip ONLY the fraction you are dividing BY (the divisor), then multiply. 6 ÷ 2/3 = 6 × 3/2 = 9. Remember: Keep-Change-Flip.', visualScaffold: 'kcf_division_steps', recheckPattern: 'Compute 8 ÷ 2/5 using Keep-Change-Flip.', parentNote: 'Teach the Keep-Change-Flip method: Keep the first number, Change ÷ to ×, Flip the second fraction.', relatedSkills: ['P5-FR-03'] },
  { tag: 'forgets_to_simplify', label: 'Forgets to simplify the final answer', description: 'Gives a correct but unsimplified answer, e.g. writes 4/8 instead of 1/2.', remediationExplanation: 'Always check if the numerator and denominator share a common factor. Divide both by the GCD. 4/8: GCD is 4, so 4÷4 / 8÷4 = 1/2.', visualScaffold: 'simplification_factor_tree', recheckPattern: 'Simplify 6/18, 9/12, and 15/20.', parentNote: 'After every fraction answer, ask: "Can both numbers be divided by the same thing?" Make it a habit.', relatedSkills: ['P5-FR-01', 'P5-FR-02', 'P5-FR-03'] },
];

const byTag = new Map(misconceptions.map((m) => [m.tag, m]));
export function getMisconception(tag) { return byTag.get(tag) || null; }
export function getMisconceptionsForSkill(skillId) { return misconceptions.filter((m) => m.relatedSkills.includes(skillId)); }
export function getAllMisconceptions() { return [...misconceptions]; }
export function getRemediationForTag(tag) { const m = byTag.get(tag); if (!m) return null; return { tag: m.tag, explanation: m.remediationExplanation, visualScaffold: m.visualScaffold, recheckPattern: m.recheckPattern, parentNote: m.parentNote }; }
export default { getMisconception, getMisconceptionsForSkill, getAllMisconceptions, getRemediationForTag };
