const misconceptions = [
  { tag: 'forgets_angles_on_line_sum_180', label: 'Forgets angles on a straight line sum to 180°', description: 'Adds angles incorrectly or uses 360° instead of 180° for angles on a straight line.', remediationExplanation: 'Angles on a straight line always add up to 180° (a half turn). To find a missing angle, subtract the known angles from 180°.', visualScaffold: 'straight_line_protractor', recheckPattern: 'Three angles on a straight line are 55°, 70° and x°. Find x.', parentNote: 'Help your child remember: a straight line is a half-turn, so the angles add up to half of 360° = 180°.', relatedSkills: ['P5-GEO-01'] },
  { tag: 'confuses_vertically_opposite_with_adjacent', label: 'Confuses vertically opposite and adjacent angles', description: 'Subtracts from 180° instead of recognising that vertically opposite angles are equal.', remediationExplanation: 'When two straight lines cross, the angles directly across from each other (vertically opposite) are always equal. Adjacent angles (next to each other) add up to 180°.', visualScaffold: 'intersecting_lines_labelled', recheckPattern: 'Two lines cross. One angle is 130°. Find the vertically opposite angle and one adjacent angle.', parentNote: 'Draw an X shape and label the angles — the ones across from each other match.', relatedSkills: ['P5-GEO-01'] },
  { tag: 'forgets_angles_at_point_sum_360', label: 'Forgets angles at a point sum to 360°', description: 'Uses 180° instead of 360° when finding an unknown angle at a point.', remediationExplanation: 'Angles at a point make a full turn and always add up to 360°. Subtract all known angles from 360° to find the missing one.', visualScaffold: 'angles_at_point_circle', recheckPattern: 'Four angles meet at a point: 90°, 110°, 85° and x°. Find x.', parentNote: 'A full circle is 360°. If the angles all meet at one point, they form a full circle.', relatedSkills: ['P5-GEO-01'] },
  { tag: 'wrong_triangle_angle_sum', label: 'Uses wrong angle sum for triangles', description: 'Uses 360° or another incorrect total instead of 180° for the angle sum of a triangle.', remediationExplanation: 'The three angles inside any triangle always add up to 180°. This works for all triangles: scalene, isosceles, equilateral, right-angled.', visualScaffold: 'triangle_angle_tearoff', recheckPattern: 'A triangle has angles 48° and 67°. Find the third angle.', parentNote: 'Tear off the three corners of a paper triangle and arrange them — they form a straight line (180°).', relatedSkills: ['P5-GEO-02'] },
  { tag: 'forgets_isosceles_has_two_equal_angles', label: 'Forgets isosceles triangle has two equal angles', description: 'Treats the two base angles of an isosceles triangle as different values.', remediationExplanation: 'An isosceles triangle has two equal sides and the angles opposite those equal sides are also equal. If the apex is given, subtract from 180° and divide by 2 to get each base angle.', visualScaffold: 'isosceles_highlight_equal', recheckPattern: 'An isosceles triangle has an apex angle of 40°. Find each base angle.', parentNote: 'Mark the two equal sides with tick marks — the angles at the base of those sides are always equal.', relatedSkills: ['P5-GEO-02'] },
  { tag: 'assumes_all_triangles_equilateral', label: 'Assumes all triangles have 60° angles', description: 'Applies the equilateral property (60° each) to non-equilateral triangles.', remediationExplanation: 'Only equilateral triangles have all angles equal to 60°. Other triangles have different angle combinations that still add to 180°.', visualScaffold: 'triangle_comparison_chart', recheckPattern: 'A triangle has angles 50° and 70°. Is it equilateral? Find the third angle.', parentNote: 'Draw different triangles and measure the angles to show only the equal-sided one has all 60°.', relatedSkills: ['P5-GEO-02'] },
  { tag: 'confuses_parallelogram_properties', label: 'Confuses parallelogram angle properties', description: 'Mixes up opposite angles (equal) with adjacent angles (supplementary) in a parallelogram.', remediationExplanation: 'In a parallelogram: opposite angles are EQUAL, adjacent angles are SUPPLEMENTARY (add to 180°). So if one angle is 70°, the opposite is 70° and the adjacent angles are each 110°.', visualScaffold: 'parallelogram_angle_labels', recheckPattern: 'A parallelogram has one angle of 65°. Find all other angles.', parentNote: 'Colour opposite corners the same colour — they share the same angle.', relatedSkills: ['P5-GEO-03'] },
  { tag: 'forgets_quadrilateral_angle_sum_360', label: 'Forgets quadrilateral angle sum is 360°', description: 'Uses 180° or another value instead of 360° for the angle sum of a quadrilateral.', remediationExplanation: 'The interior angles of any quadrilateral always add up to 360°. This applies to parallelograms, rectangles, rhombuses, trapeziums, and irregular quadrilaterals.', visualScaffold: 'quadrilateral_diagonal_split', recheckPattern: 'A quadrilateral has angles 80°, 100° and 95°. Find the fourth angle.', parentNote: 'A quadrilateral can be split into two triangles: 2 × 180° = 360°.', relatedSkills: ['P5-GEO-03'] },
  { tag: 'wrong_co_interior_angle_sum', label: 'Uses wrong sum for co-interior angles', description: 'Thinks co-interior angles are equal or add to 360° instead of 180°.', remediationExplanation: 'Co-interior angles (also called same-side interior or allied angles) between parallel lines add up to 180°, not 360°. They form a C or U shape.', visualScaffold: 'parallel_lines_transversal', recheckPattern: 'Two parallel lines are cut by a transversal. One co-interior angle is 115°. Find the other.', parentNote: 'Co-interior angles are like a door and its frame — they make a flat 180° together.', relatedSkills: ['P5-GEO-03'] },
];

const byTag = new Map(misconceptions.map((m) => [m.tag, m]));
export function getMisconception(tag) { return byTag.get(tag) || null; }
export function getMisconceptionsForSkill(skillId) { return misconceptions.filter((m) => m.relatedSkills.includes(skillId)); }
export function getAllMisconceptions() { return [...misconceptions]; }
export function getRemediationForTag(tag) { const m = byTag.get(tag); if (!m) return null; return { tag: m.tag, explanation: m.remediationExplanation, visualScaffold: m.visualScaffold, recheckPattern: m.recheckPattern, parentNote: m.parentNote }; }
export default { getMisconception, getMisconceptionsForSkill, getAllMisconceptions, getRemediationForTag };
