const misconceptions = [
  { tag: 'divides_by_wrong_base_for_percent', label: 'Divides by wrong base when finding percent', description: 'Divides the whole by the part instead of the part by the whole, e.g. 200/50 instead of 50/200 to find what percent 50 is of 200.', remediationExplanation: 'To find "what percent A is of B", divide A (the part) by B (the whole), then multiply by 100. The whole is always the denominator.', visualScaffold: 'percent_bar_model', recheckPattern: 'What percentage of 400 is 80?', parentNote: 'Ask: "which is the WHOLE?" The whole always goes on the bottom of the fraction.', relatedSkills: ['P5-PCT-01', 'P5-PCT-02', 'P5-PCT-03'] },
  { tag: 'moves_decimal_wrong_way', label: 'Moves decimal point in wrong direction', description: 'Converts 25% to 2.5 instead of 0.25, or 0.3 to 3% instead of 30%.', remediationExplanation: 'Percent to decimal: divide by 100 (move decimal LEFT two places). Decimal to percent: multiply by 100 (move decimal RIGHT two places).', visualScaffold: 'decimal_shift_arrows', recheckPattern: 'Convert 45% to a decimal, then convert 0.6 to a percent.', parentNote: 'Remember: percent means "per hundred". 25% = 25 per 100 = 0.25 (smaller number). Decimal to percent makes a bigger number.', relatedSkills: ['P5-PCT-01', 'P5-PCT-02'] },
  { tag: 'forgets_to_simplify_percent_fraction', label: 'Forgets to simplify percent as fraction', description: 'Writes 25% as 25/100 but does not simplify to 1/4.', remediationExplanation: 'After writing the percent over 100, find the GCD of numerator and denominator and divide both. 25/100 → GCD is 25 → 1/4.', visualScaffold: 'fraction_simplification_steps', recheckPattern: 'Convert 60% to a fraction in simplest form.', parentNote: 'Practise finding HCF of common percent values and 100: 10→10, 20→20, 25→25, 50→50, 75→25.', relatedSkills: ['P5-PCT-01'] },
  { tag: 'finds_percent_of_wrong_total', label: 'Applies percentage to wrong total', description: 'In multi-step problems, takes the percentage of a subtotal instead of the original total, or vice versa.', remediationExplanation: 'Read the problem carefully: identify WHICH quantity the percentage applies to. Draw a bar model and label the whole before calculating.', visualScaffold: 'bar_model_percent', recheckPattern: 'Ali had $200. He spent 25% on books and 30% of the original amount on food. How much did he have left?', parentNote: 'Before calculating, ask: "25% of WHAT?" Circle the number the percentage refers to.', relatedSkills: ['P5-PCT-02', 'P5-PCT-03'] },
  { tag: 'confuses_percent_increase_with_percent_of', label: 'Confuses percent increase with percent of', description: 'Treats a 20% increase as "20% of the amount" rather than "original + 20% of original", giving the increase amount instead of the new total, or vice versa.', remediationExplanation: 'A 20% increase means the new amount is 120% of the original. A 20% discount means the new price is 80% of the original. Always check: does the answer ask for the CHANGE or the NEW TOTAL?', visualScaffold: 'percent_increase_bar', recheckPattern: 'A shirt costs $50. Its price increases by 10%. What is the new price?', parentNote: 'Check whether the question asks "how much more/less" (just the change) or "what is the new price/amount" (original ± change).', relatedSkills: ['P5-PCT-03'] },
];

const byTag = new Map(misconceptions.map((m) => [m.tag, m]));
export function getMisconception(tag) { return byTag.get(tag) || null; }
export function getMisconceptionsForSkill(skillId) { return misconceptions.filter((m) => m.relatedSkills.includes(skillId)); }
export function getAllMisconceptions() { return [...misconceptions]; }
export function getRemediationForTag(tag) { const m = byTag.get(tag); if (!m) return null; return { tag: m.tag, explanation: m.remediationExplanation, visualScaffold: m.visualScaffold, recheckPattern: m.recheckPattern, parentNote: m.parentNote }; }
export default { getMisconception, getMisconceptionsForSkill, getAllMisconceptions, getRemediationForTag };
