const misconceptions = [
  { tag: 'reverses_ratio_order', label: 'Reverses the order of the ratio', description: 'Writes b : a when asked for a : b, e.g. girls : boys instead of boys : girls.', remediationExplanation: 'A ratio compares quantities in a specific order. "Ratio of A to B" means A : B. Always read the question carefully to see which quantity comes first.', visualScaffold: 'ratio_order_highlight', recheckPattern: 'There are 5 cats and 3 dogs. What is the ratio of cats to dogs?', parentNote: 'Underline the first quantity mentioned and the second — the ratio follows that order.', relatedSkills: ['P5-RAT-01', 'P5-RAT-03'] },
  { tag: 'adds_instead_of_divides_for_ratio', label: 'Adds or subtracts instead of dividing to simplify', description: 'Subtracts the same number from both terms (e.g. 12 : 8 → 4 : 0) instead of dividing by the HCF.', remediationExplanation: 'To simplify a ratio, divide both terms by the same number (HCF). Do not add or subtract. 12 : 8 → divide both by 4 → 3 : 2.', visualScaffold: 'simplify_ratio_steps', recheckPattern: 'Simplify the ratio 18 : 12.', parentNote: 'Remind your child: simplifying a ratio is the same as simplifying a fraction — divide, never subtract.', relatedSkills: ['P5-RAT-01', 'P5-RAT-03'] },
  { tag: 'confuses_ratio_with_fraction', label: 'Confuses ratio with fraction', description: 'Writes a ratio a : b as the fraction a/b when asked for a fraction of the total, instead of a/(a+b).', remediationExplanation: 'A ratio a : b means there are a + b total parts. The fraction of the total for the first quantity is a/(a + b), not a/b. For ratio 2 : 3, fraction of total = 2/5, not 2/3.', visualScaffold: 'ratio_bar_model', recheckPattern: 'The ratio of boys to girls is 3 : 4. What fraction of the children are boys?', parentNote: 'Draw a bar model — the total bar has a + b parts, and each quantity takes its share of parts.', relatedSkills: ['P5-RAT-02'] },
  { tag: 'divides_total_by_one_part', label: 'Divides total by one ratio term instead of the sum', description: 'When sharing 60 in ratio 2 : 3, divides 60 by 2 or 60 by 3 instead of dividing by 5 (the total parts).', remediationExplanation: 'Total parts = sum of all ratio terms. For ratio 2 : 3, total parts = 5. One part = 60 ÷ 5 = 12. First share = 2 × 12 = 24. Second share = 3 × 12 = 36.', visualScaffold: 'ratio_bar_sharing', recheckPattern: 'Share 40 stickers in the ratio 3 : 5. How many does each person get?', parentNote: 'Step 1: add ratio terms. Step 2: divide total by that sum. Step 3: multiply each term by the value of one part.', relatedSkills: ['P5-RAT-02', 'P5-RAT-03'] },
  { tag: 'forgets_to_simplify_ratio', label: 'Does not simplify the ratio fully', description: 'Gives a correct but unsimplified ratio, e.g. 6 : 4 instead of 3 : 2.', remediationExplanation: 'Always check if both terms can still be divided by a common factor. Keep dividing until the HCF is 1. 6 : 4 → ÷ 2 → 3 : 2.', visualScaffold: 'simplify_ratio_checklist', recheckPattern: 'Express 20 : 30 in simplest form.', parentNote: 'A good check: can both numbers still be divided by 2, 3, or 5? If yes, it is not fully simplified.', relatedSkills: ['P5-RAT-01', 'P5-RAT-02'] },
];

const byTag = new Map(misconceptions.map((m) => [m.tag, m]));
export function getMisconception(tag) { return byTag.get(tag) || null; }
export function getMisconceptionsForSkill(skillId) { return misconceptions.filter((m) => m.relatedSkills.includes(skillId)); }
export function getAllMisconceptions() { return [...misconceptions]; }
export function getRemediationForTag(tag) { const m = byTag.get(tag); if (!m) return null; return { tag: m.tag, explanation: m.remediationExplanation, visualScaffold: m.visualScaffold, recheckPattern: m.recheckPattern, parentNote: m.parentNote }; }
export default { getMisconception, getMisconceptionsForSkill, getAllMisconceptions, getRemediationForTag };
