const misconceptions = [
  { tag: 'confuses_place_value_names', label: 'Confuses place value names', description: 'Mixes up tens/hundreds/thousands place names, especially above ten thousands.', remediationExplanation: 'Use a place value chart: ones, tens, hundreds, thousands, ten thousands, hundred thousands, millions. Each column is ×10 of the one to its right.', visualScaffold: 'place_value_chart', recheckPattern: 'What is the value of 5 in 3 507 200?', parentNote: 'Draw a place value chart with columns labelled for each place.', relatedSkills: ['P5-WN-01'] },
  { tag: 'omits_zeros_in_word_form', label: 'Omits zeros when writing numerals from words', description: 'Writes 602 instead of 60 002 for "sixty thousand and two".', remediationExplanation: 'Write each part in its column. Sixty thousand = 60 000. And two = 2. Fill zeros for empty places.', visualScaffold: 'place_value_chart', recheckPattern: 'Write "four hundred thousand and fifty" in numerals.', parentNote: 'Use a place-value chart to ensure zeros are placed for empty positions.', relatedSkills: ['P5-WN-01'] },
  { tag: 'wrong_digit_value', label: 'Gives the digit instead of its value', description: 'Says 3 instead of 3000 for digit 3 in the thousands place.', remediationExplanation: 'The VALUE of a digit = digit × place value. 3 in the thousands place = 3 × 1000 = 3000.', visualScaffold: 'place_value_chart', recheckPattern: 'What is the value of 7 in 275 300?', parentNote: 'Digit tells you "how many", value tells you "how much".', relatedSkills: ['P5-WN-01'] },
  { tag: 'rounds_wrong_direction', label: 'Rounds the wrong way at 5', description: 'Rounds down when the deciding digit is 5 (should round up).', remediationExplanation: 'When the deciding digit is exactly 5, we round UP. E.g. 4500 rounded to nearest 1000 = 5000.', visualScaffold: 'number_line_rounding', recheckPattern: 'Round 35 500 to the nearest thousand.', parentNote: 'The rule: 0-4 round down, 5-9 round up.', relatedSkills: ['P5-WN-02'] },
  { tag: 'rounds_to_wrong_place', label: 'Rounds to the wrong place value', description: 'Rounds to the nearest hundred when asked for nearest thousand.', remediationExplanation: 'Check the question carefully. "Nearest thousand" means the answer ends in 000.', visualScaffold: 'place_value_chart', recheckPattern: 'Round 47 832 to the nearest ten thousand.', parentNote: 'Underline the digit in the target place, look at the digit to its right.', relatedSkills: ['P5-WN-02'] },
  { tag: 'truncates_instead_of_rounding', label: 'Truncates instead of rounding', description: 'Simply removes digits instead of rounding (e.g. 4789 → 4000 instead of 5000).', remediationExplanation: 'Rounding means finding the CLOSEST multiple. Check the digit to the right to decide up or down.', visualScaffold: 'number_line_rounding', recheckPattern: 'Round 6500 to the nearest thousand.', parentNote: 'Truncation chops; rounding adjusts to the nearest value.', relatedSkills: ['P5-WN-02'] },
  { tag: 'left_to_right_ignoring_precedence', label: 'Computes left to right ignoring ×/÷ priority', description: 'In 5 + 3 × 2, adds first to get 16 instead of 11.', remediationExplanation: 'Always do × and ÷ BEFORE + and −. Think of it as: multiplication/division are "stronger" operations.', visualScaffold: 'bodmas_steps', recheckPattern: 'Find the value of 10 − 2 × 3.', parentNote: 'Mnemonic: BODMAS / Order of Operations — Brackets, Orders, Division/Multiplication, Addition/Subtraction.', relatedSkills: ['P5-WN-03'] },
  { tag: 'forgets_brackets_first', label: 'Ignores brackets', description: 'Does not evaluate the expression inside brackets first.', remediationExplanation: 'Brackets are ALWAYS first. Solve what is inside () before anything else.', visualScaffold: 'bodmas_steps', recheckPattern: 'Find the value of 4 × (3 + 5).', parentNote: 'Brackets = "Do me first!" Circle them and solve before moving on.', relatedSkills: ['P5-WN-03'] },
  { tag: 'wrong_division_in_chain', label: 'Misapplies division in a chain of operations', description: 'Divides the final result instead of dividing only the adjacent term.', remediationExplanation: 'In a chain like a + b ÷ c × d, first do b ÷ c, then multiply by d, then add a.', visualScaffold: 'bodmas_steps', recheckPattern: 'Find the value of 20 + 12 ÷ 4 × 3.', parentNote: 'Underline ×/÷ operations first, solve them in order, then do +/−.', relatedSkills: ['P5-WN-03'] },
];

const byTag = new Map(misconceptions.map((m) => [m.tag, m]));
export function getMisconception(tag) { return byTag.get(tag) || null; }
export function getMisconceptionsForSkill(skillId) { return misconceptions.filter((m) => m.relatedSkills.includes(skillId)); }
export function getAllMisconceptions() { return [...misconceptions]; }
export function getRemediationForTag(tag) { const m = byTag.get(tag); if (!m) return null; return { tag: m.tag, explanation: m.remediationExplanation, visualScaffold: m.visualScaffold, recheckPattern: m.recheckPattern, parentNote: m.parentNote }; }
export default { getMisconception, getMisconceptionsForSkill, getAllMisconceptions, getRemediationForTag };
