const misconceptions = [
  { tag: 'confuses_variable_with_label', label: 'Treats variable as a label, not a quantity', description: 'Thinks "x" is a short name for the object (e.g. x = xylophone) rather than a number to find.', remediationExplanation: 'A letter in algebra stands for an unknown NUMBER, not the name of the thing. If we write 3x, it means 3 times a number, not 3 x-things.', visualScaffold: 'variable_vs_label_comparison', recheckPattern: 'If a pencil costs $p, what does 5p mean? Is it 5 pencils or 5 times p dollars?', parentNote: 'Ask your child: "What number could x be?" to reinforce that letters represent values.', relatedSkills: ['P6-ALG-01'] },
  { tag: 'adds_unlike_terms', label: 'Combines unlike terms', description: 'Adds variable terms and constants together, e.g. writes 2x + 3 = 5x.', remediationExplanation: '2x + 3 cannot be simplified further because 2x and 3 are UNLIKE terms. Like terms have the same variable part: 2x + 4x = 6x. But 2x + 3 stays as 2x + 3.', visualScaffold: 'like_unlike_terms_sorting', recheckPattern: 'Simplify 4y + 7 + 2y. Which terms can be combined?', parentNote: 'Use an analogy: 2 apples + 3 oranges cannot become 5 apple-oranges. Letters work the same way.', relatedSkills: ['P6-ALG-01'] },
  { tag: 'forgets_inverse_operation', label: 'Forgets to use the inverse operation', description: 'Tries to solve x + 5 = 12 by adding 5 instead of subtracting, or divides when should multiply.', remediationExplanation: 'To undo addition, subtract. To undo subtraction, add. To undo multiplication, divide. To undo division, multiply. Always do the OPPOSITE operation.', visualScaffold: 'inverse_operation_pairs', recheckPattern: 'Solve x + 8 = 20. What operation undoes the + 8?', parentNote: 'Think of a balance scale: whatever you do to one side, do the same to the other.', relatedSkills: ['P6-ALG-02'] },
  { tag: 'wrong_order_of_inverse', label: 'Applies inverse operations in wrong order', description: 'In 2x + 5 = 17, divides by 2 first instead of subtracting 5 first.', remediationExplanation: 'For two-step equations, undo in REVERSE order. If the equation is 2x + 5 = 17, the x was first multiplied by 2 then had 5 added. Undo: subtract 5 first, then divide by 2.', visualScaffold: 'equation_unwinding_steps', recheckPattern: 'Solve 3x + 4 = 19. Which step comes first: ÷ 3 or - 4?', parentNote: 'Like peeling layers of wrapping — undo the outermost step first.', relatedSkills: ['P6-ALG-02'] },
  { tag: 'sign_error_in_equation', label: 'Makes a sign error when solving', description: 'Subtracts when should add or vice versa when moving terms across the equals sign.', remediationExplanation: 'When you move a term to the other side of the equation, its sign changes: + becomes - and - becomes +. Check by substituting your answer back into the original equation.', visualScaffold: 'sign_change_highlight', recheckPattern: 'Solve 4x - 3 = 21. After moving -3, what happens to the sign?', parentNote: 'Always verify the answer by plugging it back in. This catches sign mistakes quickly.', relatedSkills: ['P6-ALG-02'] },
  { tag: 'writes_equation_backwards', label: 'Writes the equation backwards', description: 'Sets up the equation with sides reversed, e.g. writes 12 = x + 5 as x + 5 = 12 (harmless) but more often misidentifies which quantity is which.', remediationExplanation: 'Read the word problem carefully. Identify WHAT is unknown and WHAT is given. The equation should match the situation: left side describes one quantity, right side describes what it equals.', visualScaffold: 'equation_setup_from_words', recheckPattern: 'Ali has x books. He buys 4 more and now has 15. Write the equation.', parentNote: 'Have your child underline the unknown and circle the total before writing the equation.', relatedSkills: ['P6-ALG-03'] },
  { tag: 'confuses_expression_and_equation', label: 'Confuses expressions and equations', description: 'Writes an equation (with =) when asked for an expression, or vice versa.', remediationExplanation: 'An EXPRESSION has no equals sign: it represents a value (like 3x + 2). An EQUATION has an equals sign and says two things are equal (like 3x + 2 = 14). Expression = phrase, Equation = sentence.', visualScaffold: 'expression_vs_equation_card', recheckPattern: 'Is "5n + 3" an expression or an equation? Is "5n + 3 = 18" an expression or an equation?', parentNote: 'Expression = no equals sign. Equation = has an equals sign. A simple but important distinction.', relatedSkills: ['P6-ALG-01', 'P6-ALG-03'] },
  { tag: 'ignores_units_in_algebra', label: 'Ignores or muddles units in algebraic context', description: 'Solves the equation correctly but gives the answer in the wrong units or forgets units entirely.', remediationExplanation: 'Always check what the question asks for. If it asks "how many cm", your answer must be in cm. If it asks "how much money", include the $ sign. The variable represents a number WITH a unit.', visualScaffold: 'unit_label_reminder', recheckPattern: 'A ribbon is x cm long. 3 such ribbons are 45 cm. What is x, and what is its unit?', parentNote: 'Remind your child to re-read the question after solving: did they answer what was asked?', relatedSkills: ['P6-ALG-03'] },
];

const byTag = new Map(misconceptions.map((m) => [m.tag, m]));
export function getMisconception(tag) { return byTag.get(tag) || null; }
export function getMisconceptionsForSkill(skillId) { return misconceptions.filter((m) => m.relatedSkills.includes(skillId)); }
export function getAllMisconceptions() { return [...misconceptions]; }
export function getRemediationForTag(tag) { const m = byTag.get(tag); if (!m) return null; return { tag: m.tag, explanation: m.remediationExplanation, visualScaffold: m.visualScaffold, recheckPattern: m.recheckPattern, parentNote: m.parentNote }; }
export default { getMisconception, getMisconceptionsForSkill, getAllMisconceptions, getRemediationForTag };
