const misconceptions = [
  { tag: 'uses_diameter_as_radius', label: 'Uses diameter when radius is needed (or vice versa)', description: 'For a circle with diameter 14 cm, uses 14 as the radius in C = 2πr, getting double the correct circumference.', remediationExplanation: 'The diameter is the full distance across the circle. The radius is half the diameter. When a formula uses r (radius), you must halve the diameter first. Radius = diameter ÷ 2.', visualScaffold: 'circle_diameter_radius_label', recheckPattern: 'A circle has diameter 28 cm. Find its circumference. (Take π = 22/7)', parentNote: 'Remind your child: diameter goes all the way across, radius is only halfway. Radius = diameter ÷ 2.', relatedSkills: ['P6-CIR-01'] },
  { tag: 'forgets_straight_edge_in_semicircle', label: 'Forgets the straight edge when finding semicircle perimeter', description: 'Finds the curved part of the semicircle but forgets to add the straight diameter edge.', remediationExplanation: 'The perimeter of a semicircle has two parts: the curved arc (half the circumference) AND the straight edge (the diameter). Perimeter = πd/2 + d.', visualScaffold: 'semicircle_perimeter_parts', recheckPattern: 'Find the perimeter of a semicircle with diameter 14 cm. (Take π = 22/7)', parentNote: 'Ask your child to trace around the semicircle with their finger — they will feel both the curved part and the flat bottom.', relatedSkills: ['P6-CIR-03'] },
  { tag: 'area_uses_diameter_not_radius', label: 'Substitutes the diameter into the area formula instead of the radius', description: 'Given diameter 14 cm, uses A = π × 14 × 14 instead of A = π × 7 × 7.', remediationExplanation: 'The area formula is A = π × r × r, where r is the RADIUS. If you are given the diameter, divide by 2 first to get the radius. For diameter 14: radius = 7, area = π × 7 × 7.', visualScaffold: 'area_formula_radius_highlight', recheckPattern: 'The diameter of a circle is 28 cm. Find its area. (Take π = 22/7)', parentNote: 'The area formula uses r (radius), not d (diameter). Always halve the diameter before squaring.', relatedSkills: ['P6-CIR-02'] },
  { tag: 'confuses_circumference_area_formulas', label: 'Mixes up circumference and area formulas', description: 'Uses C = πr² (area formula) for circumference, or A = 2πr (circumference formula) for area.', remediationExplanation: 'Circumference (distance around) = π × d = 2 × π × r. Area (space inside) = π × r × r. Remember: circumference has just one r (or d), area has r squared (r × r).', visualScaffold: 'circumference_vs_area_comparison', recheckPattern: 'A circle has radius 7 cm. Find (a) its circumference and (b) its area. (Take π = 22/7)', parentNote: 'Circumference is a length (cm), area is a space (cm²). Circumference uses πd, area uses πr².', relatedSkills: ['P6-CIR-01', 'P6-CIR-02'] },
  { tag: 'wrong_fraction_for_quadrant', label: 'Divides by 2 instead of 4 for a quadrant', description: 'When finding the area of a quadrant (quarter-circle), divides the full circle area by 2 instead of 4.', remediationExplanation: 'A quadrant is a QUARTER of a circle (90° out of 360°). Divide the full circle area by 4, not by 2. A semicircle is half (÷2), a quadrant is a quarter (÷4).', visualScaffold: 'circle_fractions_diagram', recheckPattern: 'Find the area of a quadrant with radius 14 cm. (Take π = 22/7)', parentNote: 'Semi = half (÷2), quad = quarter (÷4). Ask your child how many quadrants make a full circle (answer: 4).', relatedSkills: ['P6-CIR-03'] },
  { tag: 'forgets_to_halve_for_semicircle', label: 'Uses full circumference or full area instead of halving for a semicircle', description: 'Computes the full circle circumference/area but forgets to divide by 2 for a semicircle.', remediationExplanation: 'A semicircle is HALF a circle. For area: take half the circle area. For the curved edge: take half the circumference. Then add the straight diameter edge for perimeter.', visualScaffold: 'semicircle_half_highlight', recheckPattern: 'Find the area of a semicircle with diameter 14 cm. (Take π = 22/7)', parentNote: 'Semi means half. The curved part of a semicircle is half the full circumference.', relatedSkills: ['P6-CIR-03'] },
  { tag: 'pi_approximation_error', label: 'Uses wrong value for π', description: 'Uses 3.14 when the question says 22/7, or vice versa, or uses an incorrect approximation like 3.41 or 22/8.', remediationExplanation: 'Always read the question carefully for which π value to use. If it says "Take π = 22/7", use 22/7. If it says "Take π = 3.14", use 3.14. These give slightly different answers.', visualScaffold: 'pi_value_check', recheckPattern: 'Find the circumference of a circle with diameter 7 cm. (Take π = 22/7). Then find it again using π = 3.14.', parentNote: 'The question always tells your child which value of π to use. Underline it before starting the calculation.', relatedSkills: ['P6-CIR-01', 'P6-CIR-02'] },
  { tag: 'adds_full_circumference_to_semicircle', label: 'Adds a full circumference when only a semicircle curve is needed', description: 'In a composite figure, adds πd (full circumference) for a semicircle edge instead of πd/2.', remediationExplanation: 'A semicircle has only half the curved edge of a full circle. The curved part = πd/2 (or πr). For two semicircles on opposite sides, the two curved parts together equal one full circumference (πd).', visualScaffold: 'composite_semicircle_edges', recheckPattern: 'A figure is made of a square of side 14 cm with a semicircle on one side. Find the perimeter. (Take π = 22/7)', parentNote: 'Count the semicircle edges carefully. Each semicircle contributes half the circumference as its curved part.', relatedSkills: ['P6-CIR-03'] },
];

const byTag = new Map(misconceptions.map((m) => [m.tag, m]));
export function getMisconception(tag) { return byTag.get(tag) || null; }
export function getMisconceptionsForSkill(skillId) { return misconceptions.filter((m) => m.relatedSkills.includes(skillId)); }
export function getAllMisconceptions() { return [...misconceptions]; }
export function getRemediationForTag(tag) { const m = byTag.get(tag); if (!m) return null; return { tag: m.tag, explanation: m.remediationExplanation, visualScaffold: m.visualScaffold, recheckPattern: m.recheckPattern, parentNote: m.parentNote }; }
export default { getMisconception, getMisconceptionsForSkill, getAllMisconceptions, getRemediationForTag };
