import React, { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { CheckCircle2, KeyRound } from 'lucide-react';
import { joinAPI } from '../../services/api';
import { Alert, Button, Card, PageHeader } from '../../components/ui';

// Student-facing "enter a class code" screen. Codes are generated by the school
// admin console; redeeming enrols the student into that class.
export default function JoinClassPage() {
  const { code: codeParam } = useParams();
  const navigate = useNavigate();
  const [code, setCode] = useState((codeParam || '').toUpperCase());
  const [preview, setPreview] = useState(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [joined, setJoined] = useState(null);

  const check = async () => {
    if (!code.trim()) return;
    setBusy(true); setError(''); setPreview(null);
    try {
      const res = await joinAPI.preview(code.trim());
      setPreview(res.data);
    } catch (e) {
      setError(e?.response?.data?.error || 'That code is not valid.');
    } finally { setBusy(false); }
  };

  const join = async () => {
    setBusy(true); setError('');
    try {
      const res = await joinAPI.redeem(code.trim());
      setJoined(res.data);
    } catch (e) {
      setError(e?.response?.data?.error || 'Could not join the class.');
    } finally { setBusy(false); }
  };

  return (
    <div className="mx-auto max-w-md">
      <PageHeader title="Join a class" subtitle="Enter the code your teacher gave you." />
      <Card className="p-5">
        {joined ? (
          <div className="space-y-3">
            <Alert tone="success" icon={CheckCircle2}>
              {joined.alreadyEnrolled ? `You're already in ${joined.className}.` : `You've joined ${joined.className}.`}
            </Alert>
            <Button onClick={() => navigate('/student')}>Go to my learning</Button>
          </div>
        ) : (
          <div className="space-y-3">
            {error ? <Alert tone="error">{error}</Alert> : null}
            <div className="flex items-center gap-2 rounded-lg border border-line-soft px-3 py-2">
              <KeyRound className="h-4 w-4 text-ink-400" />
              <input
                value={code}
                onChange={(e) => { setCode(e.target.value.toUpperCase()); setPreview(null); }}
                placeholder="e.g. 7KQ2MP"
                maxLength={8}
                className="w-full bg-transparent font-mono text-lg tracking-widest text-ink-700 outline-none placeholder:text-ink-300"
              />
            </div>

            {preview ? (
              <div className="rounded-lg border border-line-soft bg-surface-raised p-3 text-sm">
                <p className="font-medium text-ink-700">{preview.className}</p>
                <p className="text-ink-500">{preview.schoolName}{preview.level ? ` · ${preview.level}` : ''}</p>
                <Button className="mt-3" onClick={join} disabled={busy}>{busy ? 'Joining…' : `Join ${preview.className}`}</Button>
              </div>
            ) : (
              <Button onClick={check} disabled={busy || !code.trim()}>{busy ? 'Checking…' : 'Check code'}</Button>
            )}
          </div>
        )}
      </Card>
    </div>
  );
}
