import { operationsSkillGraph } from './OperationsSkillGraph.js';

const SKILL_IDS = new Set(operationsSkillGraph.skillIds);

const families = [
  {
    id: 'QF_OP001_001',
    skillId: 'OP001',
    name: 'Addition facts within 20 (number bonds) — Practice',
    description: 'Addition facts within 20 (number bonds) question.',
    difficulty: 3,
    generatorKind: 'opsOpAddFacts',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 3,
    masteryTargetAccuracy: 90,
    masteryQuestionCount: 10,
    misconceptionTags: ['add/count-all', 'add/off-by-one'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_OP001_002',
    skillId: 'OP001',
    name: 'Addition facts within 20 (number bonds) — MCQ',
    description: 'Addition facts within 20 (number bonds) question.',
    difficulty: 3,
    generatorKind: 'opsOpAddFactsMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 3,
    masteryTargetAccuracy: 90,
    masteryQuestionCount: 10,
    misconceptionTags: ['add/count-all', 'add/off-by-one'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_OP002_001',
    skillId: 'OP002',
    name: 'Adding 2-digit numbers (no regrouping) — Practice',
    description: 'Adding 2-digit numbers (no regrouping) question.',
    difficulty: 3,
    generatorKind: 'opsOpAdd2digit',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 6,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['add/place-misalign'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP002_002',
    skillId: 'OP002',
    name: 'Adding 2-digit numbers (no regrouping) — MCQ',
    description: 'Adding 2-digit numbers (no regrouping) question.',
    difficulty: 3,
    generatorKind: 'opsOpAdd2digitMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 6,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['add/place-misalign'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP003_001',
    skillId: 'OP003',
    name: 'Adding with regrouping (carrying) — Practice',
    description: 'Adding with regrouping (carrying) question.',
    difficulty: 3,
    generatorKind: 'opsOpAddRegroup',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['add/forgot-carry'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP003_002',
    skillId: 'OP003',
    name: 'Adding with regrouping (carrying) — MCQ',
    description: 'Adding with regrouping (carrying) question.',
    difficulty: 3,
    generatorKind: 'opsOpAddRegroupMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['add/forgot-carry'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP004_001',
    skillId: 'OP004',
    name: 'Adding 3–4 digit numbers — Practice',
    description: 'Adding 3–4 digit numbers question.',
    difficulty: 3,
    generatorKind: 'opsOpAddLarge',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['add/carry-cascade'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP004_002',
    skillId: 'OP004',
    name: 'Adding 3–4 digit numbers — MCQ',
    description: 'Adding 3–4 digit numbers question.',
    difficulty: 3,
    generatorKind: 'opsOpAddLargeMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['add/carry-cascade'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP005_001',
    skillId: 'OP005',
    name: 'Subtraction facts within 20 — Practice',
    description: 'Subtraction facts within 20 question.',
    difficulty: 3,
    generatorKind: 'opsOpSubFacts',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 3,
    masteryTargetAccuracy: 90,
    masteryQuestionCount: 10,
    misconceptionTags: ['sub/count-back-error'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_OP005_002',
    skillId: 'OP005',
    name: 'Subtraction facts within 20 — MCQ',
    description: 'Subtraction facts within 20 question.',
    difficulty: 3,
    generatorKind: 'opsOpSubFactsMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 3,
    masteryTargetAccuracy: 90,
    masteryQuestionCount: 10,
    misconceptionTags: ['sub/count-back-error'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_OP006_001',
    skillId: 'OP006',
    name: 'Subtracting 2-digit numbers (no regrouping) — Practice',
    description: 'Subtracting 2-digit numbers (no regrouping) question.',
    difficulty: 3,
    generatorKind: 'opsOpSub2digit',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 6,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['sub/smaller-from-larger'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP006_002',
    skillId: 'OP006',
    name: 'Subtracting 2-digit numbers (no regrouping) — MCQ',
    description: 'Subtracting 2-digit numbers (no regrouping) question.',
    difficulty: 3,
    generatorKind: 'opsOpSub2digitMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 6,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['sub/smaller-from-larger'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP007_001',
    skillId: 'OP007',
    name: 'Subtracting with regrouping (borrowing) — Practice',
    description: 'Subtracting with regrouping (borrowing) question.',
    difficulty: 3,
    generatorKind: 'opsOpSubRegroup',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 9,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['sub/smaller-from-larger', 'sub/borrow-no-reduce'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP007_002',
    skillId: 'OP007',
    name: 'Subtracting with regrouping (borrowing) — MCQ',
    description: 'Subtracting with regrouping (borrowing) question.',
    difficulty: 3,
    generatorKind: 'opsOpSubRegroupMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 9,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['sub/smaller-from-larger', 'sub/borrow-no-reduce'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP008_001',
    skillId: 'OP008',
    name: 'Subtracting 3–4 digit numbers (incl. across zeros) — Practice',
    description: 'Subtracting 3–4 digit numbers (incl. across zeros) question.',
    difficulty: 3,
    generatorKind: 'opsOpSubLarge',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['sub/across-zeros'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP008_002',
    skillId: 'OP008',
    name: 'Subtracting 3–4 digit numbers (incl. across zeros) — MCQ',
    description: 'Subtracting 3–4 digit numbers (incl. across zeros) question.',
    difficulty: 3,
    generatorKind: 'opsOpSubLargeMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['sub/across-zeros'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP009_001',
    skillId: 'OP009',
    name: 'Multiplication facts (times tables to 12) — Practice',
    description: 'Multiplication facts (times tables to 12) question.',
    difficulty: 3,
    generatorKind: 'opsOpMultFacts',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 3,
    masteryTargetAccuracy: 90,
    masteryQuestionCount: 10,
    misconceptionTags: ['mult/repeated-add-slow', 'mult/adjacent-fact'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_OP009_002',
    skillId: 'OP009',
    name: 'Multiplication facts (times tables to 12) — MCQ',
    description: 'Multiplication facts (times tables to 12) question.',
    difficulty: 3,
    generatorKind: 'opsOpMultFactsMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 3,
    masteryTargetAccuracy: 90,
    masteryQuestionCount: 10,
    misconceptionTags: ['mult/repeated-add-slow', 'mult/adjacent-fact'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_OP010_001',
    skillId: 'OP010',
    name: 'Multiplying by 10, 100 and 1000 — Practice',
    description: 'Multiplying by 10, 100 and 1000 question.',
    difficulty: 3,
    generatorKind: 'opsOpMultBy10100',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 4,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mult/append-zeros-decimal'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP010_002',
    skillId: 'OP010',
    name: 'Multiplying by 10, 100 and 1000 — MCQ',
    description: 'Multiplying by 10, 100 and 1000 question.',
    difficulty: 3,
    generatorKind: 'opsOpMultBy10100MCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 4,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mult/append-zeros-decimal'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP011_001',
    skillId: 'OP011',
    name: 'Multiplying 2–3 digit by 1 digit — Practice',
    description: 'Multiplying 2–3 digit by 1 digit question.',
    difficulty: 3,
    generatorKind: 'opsOpMult2x1',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 12,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mult/forgot-carry'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP011_002',
    skillId: 'OP011',
    name: 'Multiplying 2–3 digit by 1 digit — MCQ',
    description: 'Multiplying 2–3 digit by 1 digit question.',
    difficulty: 3,
    generatorKind: 'opsOpMult2x1MCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 12,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mult/forgot-carry'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP012_001',
    skillId: 'OP012',
    name: 'Long multiplication (2 digit × 2 digit) — Practice',
    description: 'Long multiplication (2 digit × 2 digit) question.',
    difficulty: 3,
    generatorKind: 'opsOpMultLong',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mult/missing-placeholder', 'mult/partial-add'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP012_002',
    skillId: 'OP012',
    name: 'Long multiplication (2 digit × 2 digit) — MCQ',
    description: 'Long multiplication (2 digit × 2 digit) question.',
    difficulty: 3,
    generatorKind: 'opsOpMultLongMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mult/missing-placeholder', 'mult/partial-add'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP013_001',
    skillId: 'OP013',
    name: 'Division facts (inverse of times tables) — Practice',
    description: 'Division facts (inverse of times tables) question.',
    difficulty: 3,
    generatorKind: 'opsOpDivFacts',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 4,
    masteryTargetAccuracy: 90,
    masteryQuestionCount: 10,
    misconceptionTags: ['div/order-reversal'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_OP013_002',
    skillId: 'OP013',
    name: 'Division facts (inverse of times tables) — MCQ',
    description: 'Division facts (inverse of times tables) question.',
    difficulty: 3,
    generatorKind: 'opsOpDivFactsMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 4,
    masteryTargetAccuracy: 90,
    masteryQuestionCount: 10,
    misconceptionTags: ['div/order-reversal'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_OP014_001',
    skillId: 'OP014',
    name: 'Short division by a 1-digit number — Practice',
    description: 'Short division by a 1-digit number question.',
    difficulty: 3,
    generatorKind: 'opsOpDivShort',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 14,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['div/drop-zero'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP014_002',
    skillId: 'OP014',
    name: 'Short division by a 1-digit number — MCQ',
    description: 'Short division by a 1-digit number question.',
    difficulty: 3,
    generatorKind: 'opsOpDivShortMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 14,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['div/drop-zero'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP015_001',
    skillId: 'OP015',
    name: 'Division with remainders (interpreting) — Practice',
    description: 'Division with remainders (interpreting) question.',
    difficulty: 3,
    generatorKind: 'opsOpDivRemainder',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['div/ignore-remainder'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP015_002',
    skillId: 'OP015',
    name: 'Division with remainders (interpreting) — MCQ',
    description: 'Division with remainders (interpreting) question.',
    difficulty: 3,
    generatorKind: 'opsOpDivRemainderMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['div/ignore-remainder'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP016_001',
    skillId: 'OP016',
    name: 'Long division by a 2-digit number — Practice',
    description: 'Long division by a 2-digit number question.',
    difficulty: 3,
    generatorKind: 'opsOpDivLong',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['div/bad-estimate', 'div/bring-down'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP016_002',
    skillId: 'OP016',
    name: 'Long division by a 2-digit number — MCQ',
    description: 'Long division by a 2-digit number question.',
    difficulty: 3,
    generatorKind: 'opsOpDivLongMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['div/bad-estimate', 'div/bring-down'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP017_001',
    skillId: 'OP017',
    name: 'Mental addition & subtraction strategies — Practice',
    description: 'Mental addition & subtraction strategies question.',
    difficulty: 3,
    generatorKind: 'opsOpMentalAddSub',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 6,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mental/no-compensation'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP017_002',
    skillId: 'OP017',
    name: 'Mental addition & subtraction strategies — MCQ',
    description: 'Mental addition & subtraction strategies question.',
    difficulty: 3,
    generatorKind: 'opsOpMentalAddSubMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 6,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mental/no-compensation'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP018_001',
    skillId: 'OP018',
    name: 'Mental multiplication & division strategies — Practice',
    description: 'Mental multiplication & division strategies question.',
    difficulty: 3,
    generatorKind: 'opsOpMentalMultDiv',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 7,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mental/no-factoring'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP018_002',
    skillId: 'OP018',
    name: 'Mental multiplication & division strategies — MCQ',
    description: 'Mental multiplication & division strategies question.',
    difficulty: 3,
    generatorKind: 'opsOpMentalMultDivMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 7,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mental/no-factoring'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP019_001',
    skillId: 'OP019',
    name: 'Order of operations (× ÷ before + −) — Practice',
    description: 'Order of operations (× ÷ before + −) question.',
    difficulty: 3,
    generatorKind: 'opsOpOrderOfOps',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['order/left-to-right'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP019_002',
    skillId: 'OP019',
    name: 'Order of operations (× ÷ before + −) — MCQ',
    description: 'Order of operations (× ÷ before + −) question.',
    difficulty: 3,
    generatorKind: 'opsOpOrderOfOpsMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['order/left-to-right'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP020_001',
    skillId: 'OP020',
    name: 'Order of operations with brackets — Practice',
    description: 'Order of operations with brackets question.',
    difficulty: 3,
    generatorKind: 'opsOpOrderOfOpsBrackets',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['order/ignore-brackets'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP020_002',
    skillId: 'OP020',
    name: 'Order of operations with brackets — MCQ',
    description: 'Order of operations with brackets question.',
    difficulty: 3,
    generatorKind: 'opsOpOrderOfOpsBracketsMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['order/ignore-brackets'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP021_001',
    skillId: 'OP021',
    name: 'Factors and multiples — Practice',
    description: 'Factors and multiples question.',
    difficulty: 3,
    generatorKind: 'opsOpFactorsMultiples',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['op/factor-multiple-confuse'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_OP021_002',
    skillId: 'OP021',
    name: 'Factors and multiples — MCQ',
    description: 'Factors and multiples question.',
    difficulty: 3,
    generatorKind: 'opsOpFactorsMultiplesMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['op/factor-multiple-confuse'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_OP022_001',
    skillId: 'OP022',
    name: 'HCF and LCM (incl. word problems) — Practice',
    description: 'HCF and LCM (incl. word problems) question.',
    difficulty: 3,
    generatorKind: 'opsOpHcfLcm',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['op/hcf-lcm-confuse'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP022_002',
    skillId: 'OP022',
    name: 'HCF and LCM (incl. word problems) — MCQ',
    description: 'HCF and LCM (incl. word problems) question.',
    difficulty: 3,
    generatorKind: 'opsOpHcfLcmMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['op/hcf-lcm-confuse'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP023_001',
    skillId: 'OP023',
    name: 'Model drawing (bar models) — Practice',
    description: 'Model drawing (bar models) question.',
    difficulty: 3,
    generatorKind: 'opsOpModelDrawing',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['op/model-wrong-parts'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_OP023_002',
    skillId: 'OP023',
    name: 'Model drawing (bar models) — MCQ',
    description: 'Model drawing (bar models) question.',
    difficulty: 3,
    generatorKind: 'opsOpModelDrawingMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['op/model-wrong-parts'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_OP024_001',
    skillId: 'OP024',
    name: 'Multi-step word problems — Practice',
    description: 'Multi-step word problems question.',
    difficulty: 3,
    generatorKind: 'opsOpWordMultiStep',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['op/wrong-operation-choice'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_OP024_002',
    skillId: 'OP024',
    name: 'Multi-step word problems — MCQ',
    description: 'Multi-step word problems question.',
    difficulty: 3,
    generatorKind: 'opsOpWordMultiStepMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['op/wrong-operation-choice'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
];

const familyById = new Map(families.map((family) => [family.id, family]));
const familiesBySkill = families.reduce((acc, family) => {
  if (!acc[family.skillId]) acc[family.skillId] = [];
  acc[family.skillId].push(family);
  return acc;
}, {});

export function getQuestionFamily(familyId) {
  return familyById.get(familyId) || null;
}

export function getQuestionFamiliesBySkill(skillId) {
  return familiesBySkill[skillId] ? [...familiesBySkill[skillId]] : [];
}

export function getAllQuestionFamilies() {
  return [...families];
}

export const operationsQuestionFamilies = families;
export default operationsQuestionFamilies;
