// MathPath domain: Fractions (Primary 2 → 6). Conceptual-first: meaning before
// procedures. KaTeX is the render target for all fraction notation (stems use
// \frac{a}{b}); skills declare the visual models that best build intuition
// (bar / area / set / number-line). Operations sit on equivalent-fractions and
// the Operations facts; remediation routes a struggling student back to meaning
// or to the specific prerequisite, never straight to "try again".
//
// extra metadata used here:
//   render: 'katex'                 — stems contain KaTeX (\frac, \times, \div)
//   visualModels: ['bar','area','set','number-line']
//   remediation: { onRepeatedFail, reinforce:[slugs], strategy }

export default {
  domain: 'Fractions',
  topic: 'Fractions',
  topicOrder: 2,
  level: 'Primary 2',
  skills: [
    // ── Fraction meaning ──
    { slug: 'fr.meaning.unit', name: 'Understanding unit fractions', level: 'Primary 2',
      prerequisites: ['ns.count.to-20'], masteryType: 'conceptual', fluencyType: 'untimed-reasoning',
      render: 'katex', visualModels: ['area', 'bar'],
      misconceptions: [
        { tag: 'frac/bigger-denom-bigger', label: 'Thinks \\frac{1}{4} > \\frac{1}{2} because 4 > 2' },
        { tag: 'frac/unequal-parts', label: 'Counts unequal parts as valid fractional parts' }],
      practiceModes: ['visual_model', 'mcq', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: [], strategy: 'show equal-area partition, then name the unit fraction' },
      questionStructures: [{ mode: 'visual_model', type: 'mcq', difficulty: 'easy', stem: 'Which diagram shows \\frac{1}{{d}} shaded?', answerRule: 'one of d equal parts shaded', misconceptionTag: 'frac/unequal-parts' }] },
    { slug: 'fr.meaning.parts', name: 'Fractions as parts of a whole', level: 'Primary 2',
      prerequisites: ['fr.meaning.unit'], masteryType: 'conceptual', fluencyType: 'accuracy',
      render: 'katex', visualModels: ['area', 'bar'],
      misconceptions: [{ tag: 'frac/count-shaded-whole', label: 'Reports shaded count as a whole number, not a fraction' }],
      practiceModes: ['visual_model', 'short_answer', 'mcq'],
      remediation: { onRepeatedFail: 'reinforce-prerequisite', reinforce: ['fr.meaning.unit'] },
      questionStructures: [{ mode: 'visual_model', type: 'short_answer', difficulty: 'easy', stem: 'What fraction of the shape is shaded?', answerRule: 'shaded/total as \\frac{n}{d}', misconceptionTag: 'frac/count-shaded-whole' }] },
    { slug: 'fr.meaning.number-line', name: 'Fractions on a number line', level: 'Primary 3',
      prerequisites: ['fr.meaning.parts', 'ns.count.to-100'], masteryType: 'conceptual', fluencyType: 'accuracy',
      render: 'katex', visualModels: ['number-line'],
      misconceptions: [{ tag: 'frac/nl-count-marks', label: 'Counts tick marks instead of intervals' }],
      practiceModes: ['number_line', 'mcq', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['fr.meaning.parts'], strategy: 'count equal intervals from 0' },
      questionStructures: [{ mode: 'number_line', type: 'short_answer', difficulty: 'medium', stem: 'What fraction does point A mark on a number line from 0 to 1 split into {d} equal parts?', answerRule: 'position/d', misconceptionTag: 'frac/nl-count-marks' }] },

    // ── Fraction of a set ──
    { slug: 'fr.of-set', name: 'Fraction of a set', level: 'Primary 3',
      prerequisites: ['fr.meaning.parts', 'op.div.facts'], masteryType: 'application', fluencyType: 'accuracy',
      render: 'katex', visualModels: ['set'],
      misconceptions: [{ tag: 'frac/set-numerator-only', label: 'Gives the numerator count instead of computing the fraction of the set' }],
      practiceModes: ['visual_model', 'short_answer', 'mcq'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['op.div.facts'], strategy: 'divide the set into d equal groups, take n groups' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: 'What is \\frac{{n}}{{d}} of {total}?', answerRule: 'total/d*n', misconceptionTag: 'frac/set-numerator-only' }] },

    // ── Equivalent & simplifying ──
    { slug: 'fr.equivalent', name: 'Equivalent fractions', level: 'Primary 3',
      prerequisites: ['fr.meaning.parts', 'op.mult.facts'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 6, targetAccuracy: 90 },
      render: 'katex', visualModels: ['bar', 'area'],
      misconceptions: [{ tag: 'frac/add-not-multiply', label: 'Adds the same number to top and bottom instead of multiplying' }],
      practiceModes: ['visual_model', 'fluency_drill', 'mcq'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['op.mult.facts'], strategy: 'show same area split into more equal parts' },
      questionStructures: [{ mode: 'fluency_drill', type: 'short_answer', difficulty: 'medium', stem: 'Fill in: \\frac{{a}}{{b}} = \\frac{?}{{bk}}', answerRule: 'a*k', misconceptionTag: 'frac/add-not-multiply' }] },
    { slug: 'fr.simplify', name: 'Simplifying fractions to lowest terms', level: 'Primary 4',
      prerequisites: ['fr.equivalent', 'op.div.facts'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 7, targetAccuracy: 90 },
      render: 'katex', visualModels: ['bar'],
      misconceptions: [{ tag: 'frac/incomplete-simplify', label: 'Stops before lowest terms (divides by a common factor, not the HCF)' }],
      practiceModes: ['fluency_drill', 'mcq', 'diagnostic'],
      remediation: { onRepeatedFail: 'reinforce-prerequisite', reinforce: ['fr.equivalent', 'op.div.facts'] },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: 'Simplify \\frac{{num}}{{den}} to its lowest terms.', answerRule: 'divide by HCF', misconceptionTag: 'frac/incomplete-simplify' }] },

    // ── Comparing & ordering ──
    { slug: 'fr.compare.same-denom', name: 'Comparing fractions (same denominator)', level: 'Primary 3',
      prerequisites: ['fr.meaning.parts'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 4, targetAccuracy: 92 },
      render: 'katex', visualModels: ['bar'],
      misconceptions: [{ tag: 'frac/compare-denom', label: 'Compares denominators when they are already equal' }],
      practiceModes: ['fluency_drill', 'mcq'],
      remediation: { onRepeatedFail: 'reinforce-prerequisite', reinforce: ['fr.meaning.parts'] },
      questionStructures: [{ mode: 'mcq', type: 'mcq', difficulty: 'easy', stem: 'Which is larger: \\frac{{a}}{{d}} or \\frac{{b}}{{d}}?', answerRule: 'larger numerator', misconceptionTag: 'frac/compare-denom' }] },
    { slug: 'fr.compare.same-num', name: 'Comparing fractions (same numerator)', level: 'Primary 4',
      prerequisites: ['fr.meaning.unit'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 5, targetAccuracy: 90 },
      render: 'katex', visualModels: ['bar', 'area'],
      misconceptions: [{ tag: 'frac/same-num-bigger-denom', label: 'Thinks the larger denominator gives the larger fraction' }],
      practiceModes: ['visual_model', 'fluency_drill', 'mcq'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['fr.meaning.unit'], strategy: 'same number of larger vs smaller parts' },
      questionStructures: [{ mode: 'mcq', type: 'mcq', difficulty: 'medium', stem: 'Which is larger: \\frac{{n}}{{a}} or \\frac{{n}}{{b}}?', answerRule: 'smaller denominator', misconceptionTag: 'frac/same-num-bigger-denom' }] },
    { slug: 'fr.compare.unlike', name: 'Comparing unlike fractions', level: 'Primary 5',
      prerequisites: ['fr.equivalent', 'fr.compare.same-denom', 'fr.compare.same-num'], masteryType: 'procedural', fluencyType: 'accuracy',
      render: 'katex', visualModels: ['bar'],
      misconceptions: [{ tag: 'frac/cross-error', label: 'Cross-multiplies in the wrong direction / forgets to compare products' }],
      practiceModes: ['mcq', 'short_answer', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['fr.equivalent'], strategy: 'convert to a common denominator first' },
      questionStructures: [{ mode: 'mcq', type: 'mcq', difficulty: 'hard', stem: 'Which is larger: \\frac{{a}}{{b}} or \\frac{{c}}{{d}}?', answerRule: 'common denominator then compare', misconceptionTag: 'frac/cross-error' }] },
    { slug: 'fr.order', name: 'Ordering fractions', level: 'Primary 5',
      prerequisites: ['fr.compare.unlike', 'ns.order.to-100'], masteryType: 'procedural', fluencyType: 'accuracy',
      render: 'katex', visualModels: ['number-line'],
      misconceptions: [{ tag: 'frac/order-by-num', label: 'Orders by numerator (or denominator) alone' }],
      practiceModes: ['order_sort', 'mcq'],
      remediation: { onRepeatedFail: 'reinforce-prerequisite', reinforce: ['fr.compare.unlike'] },
      questionStructures: [{ mode: 'order_sort', type: 'short_answer', difficulty: 'hard', stem: 'Arrange from smallest to largest: {set of fractions}', answerRule: 'common denominator then sort', misconceptionTag: 'frac/order-by-num' }] },

    // ── Mixed numbers & improper fractions ──
    { slug: 'fr.mixed-improper', name: 'Mixed numbers and improper fractions', level: 'Primary 4',
      prerequisites: ['fr.meaning.parts', 'op.mult.facts', 'op.add.facts'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 6, targetAccuracy: 90 },
      render: 'katex', visualModels: ['bar', 'number-line'],
      misconceptions: [{ tag: 'frac/mixed-add-error', label: 'Converts a\\frac{b}{c} as \\frac{a+b}{c} instead of \\frac{ac+b}{c}' }],
      practiceModes: ['fluency_drill', 'mcq', 'visual_model'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['op.mult.facts'], strategy: 'wholes × denominator, then add the parts' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: 'Write {w}\\frac{{n}}{{d}} as an improper fraction.', answerRule: '(w*d+n)/d', misconceptionTag: 'frac/mixed-add-error' }] },

    // ── Fraction operations ──
    { slug: 'fr.add.like', name: 'Adding and subtracting like fractions', level: 'Primary 3',
      prerequisites: ['fr.meaning.parts', 'op.add.facts'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 5, targetAccuracy: 92 },
      render: 'katex', visualModels: ['bar'],
      misconceptions: [{ tag: 'frac/add-denominators', label: 'Adds denominators as well as numerators' }],
      practiceModes: ['fluency_drill', 'visual_model', 'mcq'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['fr.meaning.parts'], strategy: 'same-size parts: count the parts, keep the denominator' },
      questionStructures: [{ mode: 'fluency_drill', type: 'short_answer', difficulty: 'easy', stem: '\\frac{{a}}{{d}} + \\frac{{b}}{{d}} = ?', answerRule: '(a+b)/d', misconceptionTag: 'frac/add-denominators' }] },
    { slug: 'fr.add.unlike', name: 'Adding and subtracting unlike fractions', level: 'Primary 5',
      prerequisites: ['fr.add.like', 'fr.equivalent'], masteryType: 'procedural', fluencyType: 'accuracy',
      render: 'katex', visualModels: ['bar'],
      misconceptions: [{ tag: 'frac/add-without-common', label: 'Adds numerators/denominators without a common denominator' }],
      practiceModes: ['short_answer', 'worked_example', 'diagnostic'],
      remediation: { onRepeatedFail: 'reinforce-prerequisite', reinforce: ['fr.equivalent', 'fr.add.like'] },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: '\\frac{{a}}{{b}} + \\frac{{c}}{{e}} = ?', answerRule: 'common denominator then add', misconceptionTag: 'frac/add-without-common' }] },
    { slug: 'fr.add.mixed', name: 'Adding and subtracting mixed numbers', level: 'Primary 5',
      prerequisites: ['fr.add.unlike', 'fr.mixed-improper'], masteryType: 'procedural', fluencyType: 'accuracy',
      render: 'katex', visualModels: ['bar'],
      misconceptions: [{ tag: 'frac/forgot-regroup', label: 'Fails to regroup when the fraction parts sum past 1' }],
      practiceModes: ['short_answer', 'worked_example'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['fr.add.unlike', 'fr.mixed-improper'] },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'hard', stem: '{w1}\\frac{{a}}{{b}} + {w2}\\frac{{c}}{{e}} = ?', answerRule: 'add wholes and parts, regroup', misconceptionTag: 'frac/forgot-regroup' }] },
    { slug: 'fr.mult.whole', name: 'Multiplying a fraction by a whole number', level: 'Primary 4',
      prerequisites: ['fr.meaning.parts', 'op.mult.facts'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 6, targetAccuracy: 90 },
      render: 'katex', visualModels: ['bar', 'area'],
      misconceptions: [{ tag: 'frac/mult-both', label: 'Multiplies the denominator by the whole number too' }],
      practiceModes: ['fluency_drill', 'mcq', 'visual_model'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['fr.meaning.parts'], strategy: 'repeated addition of the fraction' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: '\\frac{{n}}{{d}} \\times {w} = ?', answerRule: '(n*w)/d simplified', misconceptionTag: 'frac/mult-both' }] },
    { slug: 'fr.mult.fraction', name: 'Multiplying a fraction by a fraction', level: 'Primary 6',
      prerequisites: ['fr.mult.whole', 'fr.simplify'], masteryType: 'procedural', fluencyType: 'accuracy',
      render: 'katex', visualModels: ['area'],
      misconceptions: [{ tag: 'frac/mult-cross', label: 'Cross-multiplies instead of multiplying straight across' }],
      practiceModes: ['short_answer', 'worked_example', 'visual_model'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['fr.mult.whole'], strategy: 'area model: fraction of a fraction' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: '\\frac{{a}}{{b}} \\times \\frac{{c}}{{d}} = ?', answerRule: '(a*c)/(b*d) simplified', misconceptionTag: 'frac/mult-cross' }] },
    { slug: 'fr.div.whole', name: 'Dividing a fraction by a whole number', level: 'Primary 6',
      prerequisites: ['fr.mult.fraction', 'op.div.facts'], masteryType: 'procedural', fluencyType: 'accuracy',
      render: 'katex', visualModels: ['bar'],
      misconceptions: [{ tag: 'frac/div-numerator-only', label: 'Divides only the numerator regardless of divisibility' }],
      practiceModes: ['short_answer', 'worked_example'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['fr.mult.fraction'], strategy: 'split each part into equal pieces' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: '\\frac{{n}}{{d}} \\div {w} = ?', answerRule: 'n/(d*w) simplified', misconceptionTag: 'frac/div-numerator-only' }] },
    { slug: 'fr.div.fraction', name: 'Dividing by a fraction', level: 'Primary 6',
      prerequisites: ['fr.div.whole'], masteryType: 'procedural', fluencyType: 'accuracy',
      render: 'katex', visualModels: ['bar', 'number-line'],
      misconceptions: [{ tag: 'frac/no-invert', label: 'Does not invert-and-multiply (divides numerators/denominators)' }],
      practiceModes: ['short_answer', 'worked_example', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['fr.div.whole'], strategy: 'how many \\frac{c}{d} fit into the dividend' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'hard', stem: '\\frac{{a}}{{b}} \\div \\frac{{c}}{{d}} = ?', answerRule: 'multiply by reciprocal', misconceptionTag: 'frac/no-invert' }] },

    // ── Fraction word problems (application) ──
    { slug: 'fr.word-problems', name: 'Fraction word problems', level: 'Primary 5',
      prerequisites: ['fr.add.unlike', 'fr.of-set'], masteryType: 'application', fluencyType: 'untimed-reasoning',
      render: 'katex', visualModels: ['bar'],
      misconceptions: [{ tag: 'frac/word-whole-confuse', label: 'Loses track of what "the whole" refers to across steps' }],
      practiceModes: ['short_answer', 'worked_example', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['fr.of-set'], strategy: 'draw a bar for the whole; mark each fraction of it' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: '{fraction word problem}', answerRule: 'fraction of the whole', misconceptionTag: 'frac/word-whole-confuse' }] },
    { slug: 'fr.word-remainder', name: 'Fraction word problems (remainder concept)', level: 'Primary 6',
      prerequisites: ['fr.word-problems'], masteryType: 'application', fluencyType: 'untimed-reasoning',
      render: 'katex', visualModels: ['bar'],
      misconceptions: [{ tag: 'frac/remainder-of-original', label: 'Takes the later fraction of the original total, not of the remainder' }],
      practiceModes: ['short_answer', 'worked_example', 'diagnostic'],
      remediation: { onRepeatedFail: 'guided-replication', reinforce: ['fr.word-problems'], strategy: 'each step works on what is LEFT; redraw the bar after each step' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'hard', stem: 'After using some, then \\frac{1}{{f}} of the remainder, {left} are left of {total}. How many were used first?', answerRule: 'work back from the remainder', misconceptionTag: 'frac/remainder-of-original' }] },
    { slug: 'fr.word-equal-units', name: 'Fraction word problems (equal units / comparison)', level: 'Primary 6',
      prerequisites: ['fr.word-problems'], masteryType: 'application', fluencyType: 'untimed-reasoning',
      render: 'katex', visualModels: ['bar'],
      misconceptions: [{ tag: 'frac/unequal-units', label: 'Compares fractions of different wholes as if the units were equal' }],
      practiceModes: ['short_answer', 'worked_example', 'diagnostic'],
      remediation: { onRepeatedFail: 'guided-replication', reinforce: ['fr.word-problems'], strategy: 'make the units equal first, then compare or combine' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'hard', stem: '{two-quantity fraction comparison word problem}', answerRule: 'equalise units, then solve', misconceptionTag: 'frac/unequal-units' }] },
  ],
};
