// MathPath domain: Fractions (Primary 2 → 6)
// Canonical F001–F026 alignment for MathPath.
// We keep stable slug keys for seed/reconcile compatibility while ensuring the
// frameworkCode + skill sequence matches the F001–F026 specification exactly.

const FRACTIONS_FRAMEWORK_CODES = {
  'fr.meaning.parts': 'F001',
  'fr.meaning.num-den': 'F002',
  'fr.meaning.whole': 'F003',
  'fr.meaning.unit': 'F004',
  'fr.meaning.number-line': 'F005',
  'fr.compare.unit': 'F006',
  'fr.compare.same-denom': 'F007',
  'fr.compare.same-num': 'F008',
  'fr.order': 'F009',
  'fr.equivalent': 'F010',
  'fr.equivalent.generate': 'F011',
  'fr.simplify': 'F012',
  'fr.mixed-improper': 'F013',
  'fr.mixed-proper': 'F014',
  'fr.mixed-convert': 'F015',
  'fr.add.same-denom': 'F016',
  'fr.sub.like': 'F017',
  'fr.add.unlike': 'F018',
  'fr.sub.unlike': 'F019',
  'fr.of-quantity': 'F020',
  'fr.mult.fraction': 'F021',
  'fr.div.fraction': 'F022',
  'fr.word-problems': 'F023',
  'fr.word-multi-step': 'F024',
  'fr.exam-applications': 'F025',
  'fr.mastery-challenge': 'F026',
};

const FRACTIONS_MATHPATH_SKILL_NAMES = {
  F001: 'Recognise Fractions',
  F002: 'Numerator and Denominator',
  F003: 'Fraction of a Whole',
  F004: 'Unit Fractions',
  F005: 'Fractions on Number Line',
  F006: 'Compare Unit Fractions',
  F007: 'Compare Same Denominator',
  F008: 'Compare Same Numerator',
  F009: 'Order Fractions',
  F010: 'Equivalent Fractions',
  F011: 'Generate Equivalent Fractions',
  F012: 'Simplify Fractions',
  F013: 'Improper Fractions',
  F014: 'Mixed Numbers',
  F015: 'Convert Mixed to/from Improper',
  F016: 'Add Same Denominator',
  F017: 'Subtract Same Denominator',
  F018: 'Add Different Denominators',
  F019: 'Subtract Different Denominators',
  F020: 'Fraction of Quantity',
  F021: 'Multiply Fractions',
  F022: 'Divide Fractions',
  F023: 'Fraction Word Problems',
  F024: 'Multi-Step Fraction Problems',
  F025: 'Exam-Style Fraction Applications',
  F026: 'Fractions Mastery Challenge',
};

const skills = [
  { slug: 'fr.meaning.parts', name: 'Recognise Fractions', level: 'Primary 2', prerequisites: ['ns.count.to-20'] },
  { slug: 'fr.meaning.num-den', name: 'Numerator and denominator', level: 'Primary 2', prerequisites: ['fr.meaning.parts'] },
  { slug: 'fr.meaning.whole', name: 'Fraction of a whole', level: 'Primary 2', prerequisites: ['fr.meaning.num-den'] },
  { slug: 'fr.meaning.unit', name: 'Unit fractions', level: 'Primary 2', prerequisites: ['fr.meaning.whole'] },
  { slug: 'fr.meaning.number-line', name: 'Fractions on a number line', level: 'Primary 3', prerequisites: ['fr.meaning.parts', 'ns.count.to-100'] },
  { slug: 'fr.compare.unit', name: 'Comparing unit fractions', level: 'Primary 3', prerequisites: ['fr.meaning.unit', 'fr.meaning.number-line'] },
  { slug: 'fr.compare.same-denom', name: 'Comparing fractions (same denominator)', level: 'Primary 3', prerequisites: ['fr.meaning.parts'] },
  { slug: 'fr.compare.same-num', name: 'Comparing fractions (same numerator)', level: 'Primary 4', prerequisites: ['fr.meaning.unit'] },
  { slug: 'fr.order', name: 'Ordering fractions', level: 'Primary 5', prerequisites: ['fr.compare.same-denom', 'fr.compare.same-num', 'fr.equivalent', 'ns.order.to-100'] },
  { slug: 'fr.equivalent', name: 'Equivalent fractions', level: 'Primary 3', prerequisites: ['fr.meaning.parts', 'op.mult.facts'] },
  { slug: 'fr.equivalent.generate', name: 'Generate equivalent fractions', level: 'Primary 4', prerequisites: ['fr.equivalent', 'op.mult.facts'] },
  { slug: 'fr.simplify', name: 'Simplifying fractions to lowest terms', level: 'Primary 4', prerequisites: ['fr.equivalent.generate', 'op.div.facts'] },
  { slug: 'fr.mixed-improper', name: 'Improper fractions', level: 'Primary 4', prerequisites: ['fr.meaning.parts', 'op.mult.facts', 'op.add.facts'] },
  { slug: 'fr.mixed-proper', name: 'Mixed numbers', level: 'Primary 4', prerequisites: ['fr.mixed-improper'] },
  { slug: 'fr.mixed-convert', name: 'Convert Mixed to/from Improper', level: 'Primary 4', prerequisites: ['fr.mixed-improper', 'fr.mixed-proper'] },
  { slug: 'fr.add.same-denom', name: 'Add fractions with same denominator', level: 'Primary 3', prerequisites: ['fr.meaning.parts', 'op.add.facts'] },
  { slug: 'fr.sub.like', name: 'Subtracting like fractions', level: 'Primary 3', prerequisites: ['fr.add.same-denom'] },
  { slug: 'fr.add.unlike', name: 'Adding and subtracting unlike fractions', level: 'Primary 5', prerequisites: ['fr.add.same-denom', 'fr.equivalent'] },
  { slug: 'fr.sub.unlike', name: 'Subtracting unlike fractions', level: 'Primary 5', prerequisites: ['fr.add.unlike', 'fr.sub.like'] },
  { slug: 'fr.of-quantity', name: 'Fraction of a quantity', level: 'Primary 3', prerequisites: ['fr.meaning.parts', 'op.div.facts'] },
  { slug: 'fr.mult.fraction', name: 'Multiplying a fraction by a fraction', level: 'Primary 6', prerequisites: ['fr.of-quantity', 'fr.simplify'] },
  { slug: 'fr.div.fraction', name: 'Dividing by a fraction', level: 'Primary 6', prerequisites: ['fr.mult.fraction'] },
  { slug: 'fr.word-problems', name: 'Fraction word problems', level: 'Primary 5', prerequisites: ['fr.add.unlike', 'fr.of-quantity'] },
  { slug: 'fr.word-multi-step', name: 'Multi-step fraction problems', level: 'Primary 6', prerequisites: ['fr.word-problems'] },
  { slug: 'fr.exam-applications', name: 'Exam-style fraction applications', level: 'Primary 6', prerequisites: ['fr.word-multi-step'] },
  { slug: 'fr.mastery-challenge', name: 'Fractions mastery challenge', level: 'Primary 6', prerequisites: ['fr.exam-applications'] },
];

export default {
  domain: 'Fractions',
  topic: 'Fractions',
  topicOrder: 2,
  level: 'Primary 2',
  skills: skills.map((skill) => ({
    ...skill,
    frameworkCode: FRACTIONS_FRAMEWORK_CODES[skill.slug] || '',
    mathPathSkillId: FRACTIONS_FRAMEWORK_CODES[skill.slug] || '',
    mathPathSkillName: FRACTIONS_MATHPATH_SKILL_NAMES[FRACTIONS_FRAMEWORK_CODES[skill.slug]] || '',
  })),
};
