// MathPath domain: Geometry (Primary 1 → 6). Shape & space, authored diagram-
// first: most skills are inherently visual, so each declares `figureDependent`
// (the item needs a diagram to make sense) and the `visualModels` that suit a
// small mobile screen. Practice modes lean on `diagram` / `visual_model`. Flows
// go concrete→abstract: see/identify shapes → describe properties → reason about
// angles → measure (perimeter/area). Perimeter & area FOUNDATIONS live here;
// the Measurement domain adds units, conversions and volume of solids on top.
//
// Mobile/diagram guidance carried per skill:
//   figureDependent: true   — render a clear, labelled figure; keep it the focus
//   visualModels: ['shape','grid','angle','net','symmetry-line','number-figure']
//
// extra metadata: render:'katex' (formulae), figureDependent, visualModels

export default {
  domain: 'Geometry',
  topic: 'Geometry',
  topicOrder: 8,             // Measurement reserves order 7
  level: 'Primary 1',
  skills: [
    // ── 2D shapes ──
    { slug: 'geo.2d-shapes', name: 'Identifying 2D shapes', level: 'Primary 1',
      prerequisites: [], masteryType: 'conceptual', fluencyType: 'timed',
      fluency: { targetSeconds: 3, targetAccuracy: 95 }, figureDependent: true, visualModels: ['shape'],
      misconceptions: [{ tag: 'geo/orientation-changes-shape', label: 'Does not recognise a shape when rotated (a tilted square looks like a "diamond")' }],
      practiceModes: ['visual_model', 'mcq'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: [], strategy: 'rotate the shape; the name does not change' },
      questionStructures: [{ mode: 'visual_model', type: 'mcq', difficulty: 'easy', stem: 'Which of these shapes is a {shape}?', answerRule: 'match by sides/vertices', misconceptionTag: 'geo/orientation-changes-shape' }] },
    { slug: 'geo.2d-properties', name: 'Properties of 2D shapes (sides and vertices)', level: 'Primary 3',
      prerequisites: ['geo.2d-shapes'], masteryType: 'conceptual', fluencyType: 'accuracy',
      figureDependent: true, visualModels: ['shape'],
      misconceptions: [{ tag: 'geo/side-vertex-count', label: 'Miscounts sides vs vertices / corners' }],
      practiceModes: ['visual_model', 'short_answer', 'mcq'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['geo.2d-shapes'], strategy: 'trace each side, then mark each corner' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'easy', stem: 'How many sides does a {polygon} have?', answerRule: 'side count', misconceptionTag: 'geo/side-vertex-count' }] },
    { slug: 'geo.lines', name: 'Parallel and perpendicular lines', level: 'Primary 4',
      prerequisites: ['geo.2d-properties'], masteryType: 'conceptual', fluencyType: 'accuracy',
      figureDependent: true, visualModels: ['grid'],
      misconceptions: [{ tag: 'geo/parallel-perp-confuse', label: 'Confuses parallel with perpendicular' }],
      practiceModes: ['visual_model', 'mcq', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['geo.2d-properties'], strategy: 'parallel never meet; perpendicular meet at a right angle' },
      questionStructures: [{ mode: 'visual_model', type: 'mcq', difficulty: 'medium', stem: 'On the grid, which two lines are perpendicular?', answerRule: 'pair meeting at 90°', misconceptionTag: 'geo/parallel-perp-confuse' }] },

    // ── Angles ──
    { slug: 'geo.angle-intro', name: 'Angle types (right, acute, obtuse)', level: 'Primary 3',
      prerequisites: ['geo.lines'], masteryType: 'conceptual', fluencyType: 'timed',
      fluency: { targetSeconds: 3, targetAccuracy: 92 }, figureDependent: true, visualModels: ['angle'],
      misconceptions: [{ tag: 'geo/angle-by-arm-length', label: 'Thinks a longer arm makes a bigger angle' }],
      practiceModes: ['visual_model', 'mcq'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['geo.lines'], strategy: 'angle is the turn between arms, not their length' },
      questionStructures: [{ mode: 'visual_model', type: 'mcq', difficulty: 'easy', stem: 'Is the marked angle acute, right or obtuse?', answerRule: 'compare to 90°', misconceptionTag: 'geo/angle-by-arm-length' }] },
    { slug: 'geo.angle-measure', name: 'Measuring and drawing angles', level: 'Primary 4',
      prerequisites: ['geo.angle-intro'], masteryType: 'procedural', fluencyType: 'accuracy',
      figureDependent: true, visualModels: ['angle'],
      misconceptions: [{ tag: 'geo/protractor-scale', label: 'Reads the wrong protractor scale (inner vs outer)' }],
      practiceModes: ['visual_model', 'short_answer', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['geo.angle-intro'], strategy: 'start from 0 on the arm; check the angle type first' },
      questionStructures: [{ mode: 'visual_model', type: 'short_answer', difficulty: 'medium', stem: 'Measure the marked angle (degrees).', answerRule: 'protractor reading', misconceptionTag: 'geo/protractor-scale' }] },
    { slug: 'geo.angle-line-point', name: 'Angles on a line and at a point', level: 'Primary 5',
      prerequisites: ['geo.angle-measure'], masteryType: 'procedural', fluencyType: 'accuracy',
      render: 'katex', figureDependent: true, visualModels: ['angle'],
      misconceptions: [{ tag: 'geo/angle-relationship', label: 'Uses the wrong total (180° on a line, 360° at a point)' }],
      practiceModes: ['visual_model', 'short_answer', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['geo.angle-measure'], strategy: 'angles on a line add to 180°, at a point to 360°' },
      questionStructures: [{ mode: 'visual_model', type: 'short_answer', difficulty: 'medium', stem: 'Find the marked angle (angles on a straight line).', answerRule: '180 − known', misconceptionTag: 'geo/angle-relationship' }] },

    // ── Triangle properties ──
    { slug: 'geo.triangle-types', name: 'Types of triangles', level: 'Primary 5',
      prerequisites: ['geo.2d-properties'], masteryType: 'conceptual', fluencyType: 'accuracy',
      figureDependent: true, visualModels: ['shape'],
      misconceptions: [{ tag: 'geo/triangle-by-look', label: 'Classifies by appearance, ignoring side/angle marks' }],
      practiceModes: ['visual_model', 'mcq'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['geo.2d-properties'], strategy: 'check equal-side and right-angle marks' },
      questionStructures: [{ mode: 'visual_model', type: 'mcq', difficulty: 'easy', stem: 'What type of triangle is shown?', answerRule: 'by sides/angles', misconceptionTag: 'geo/triangle-by-look' }] },
    { slug: 'geo.triangle-angles', name: 'Angle properties of triangles', level: 'Primary 6',
      prerequisites: ['geo.triangle-types', 'geo.angle-line-point'], masteryType: 'procedural', fluencyType: 'accuracy',
      render: 'katex', figureDependent: true, visualModels: ['angle', 'shape'],
      misconceptions: [{ tag: 'geo/angle-sum-wrong', label: 'Does not use the 180° angle sum (or misuses isosceles equal angles)' }],
      practiceModes: ['visual_model', 'short_answer', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['geo.angle-line-point'], strategy: 'the three angles of a triangle add to 180°' },
      questionStructures: [{ mode: 'visual_model', type: 'short_answer', difficulty: 'medium', stem: 'Find the unknown angle in the triangle.', answerRule: '180 − sum of known', misconceptionTag: 'geo/angle-sum-wrong' }] },

    // ── Quadrilateral properties ──
    { slug: 'geo.quad-types', name: 'Types of quadrilaterals and their properties', level: 'Primary 5',
      prerequisites: ['geo.2d-properties'], masteryType: 'conceptual', fluencyType: 'accuracy',
      figureDependent: true, visualModels: ['shape'],
      misconceptions: [{ tag: 'geo/square-not-rectangle', label: 'Thinks a square is not a rectangle (misses the inclusive hierarchy)' }],
      practiceModes: ['visual_model', 'mcq', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['geo.2d-properties'], strategy: 'sort by parallel sides and equal angles' },
      questionStructures: [{ mode: 'visual_model', type: 'mcq', difficulty: 'medium', stem: 'Which property is true for a {quad}?', answerRule: 'property match', misconceptionTag: 'geo/square-not-rectangle' }] },
    { slug: 'geo.angle-quad', name: 'Angles in special quadrilaterals', level: 'Primary 6',
      prerequisites: ['geo.quad-types', 'geo.angle-line-point'], masteryType: 'procedural', fluencyType: 'accuracy',
      render: 'katex', figureDependent: true, visualModels: ['angle', 'shape'],
      misconceptions: [{ tag: 'geo/quad-angle-relationship', label: 'Misapplies parallelogram/rhombus angle properties' }],
      practiceModes: ['visual_model', 'short_answer', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['geo.quad-types', 'geo.angle-line-point'], strategy: 'opposite angles equal; co-interior add to 180°' },
      questionStructures: [{ mode: 'visual_model', type: 'short_answer', difficulty: 'hard', stem: 'ABCD is a parallelogram. Find the marked angle.', answerRule: 'apply quad angle properties', misconceptionTag: 'geo/quad-angle-relationship' }] },

    // ── Symmetry ──
    { slug: 'geo.symmetry', name: 'Line symmetry', level: 'Primary 4',
      prerequisites: ['geo.2d-properties'], masteryType: 'conceptual', fluencyType: 'accuracy',
      figureDependent: true, visualModels: ['symmetry-line'],
      misconceptions: [{ tag: 'geo/diagonal-symmetry-miss', label: 'Misses diagonal lines of symmetry / confuses symmetry with translation' }],
      practiceModes: ['visual_model', 'mcq'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['geo.2d-properties'], strategy: 'fold along the line; the halves must match' },
      questionStructures: [{ mode: 'visual_model', type: 'mcq', difficulty: 'easy', stem: 'How many lines of symmetry does the figure have?', answerRule: 'count axes', misconceptionTag: 'geo/diagonal-symmetry-miss' }] },
    { slug: 'geo.symmetry-complete', name: 'Completing symmetric figures', level: 'Primary 5',
      prerequisites: ['geo.symmetry'], masteryType: 'application', fluencyType: 'accuracy',
      figureDependent: true, visualModels: ['grid', 'symmetry-line'],
      misconceptions: [{ tag: 'geo/reflect-not-translate', label: 'Translates the shape instead of reflecting it across the line' }],
      practiceModes: ['visual_model', 'diagnostic'],
      remediation: { onRepeatedFail: 'guided-replication', reinforce: ['geo.symmetry'], strategy: 'reflect each marked cell to the equal distance on the other side' },
      questionStructures: [{ mode: 'visual_model', type: 'open_ended', difficulty: 'medium', stem: 'Shade cells to make the figure symmetric about line AB.', answerRule: 'mirror the shaded cells', misconceptionTag: 'geo/reflect-not-translate' }] },

    // ── 3D shapes ──
    { slug: 'geo.3d-shapes', name: 'Identifying 3D solids (faces, edges, vertices)', level: 'Primary 3',
      prerequisites: ['geo.2d-shapes'], masteryType: 'conceptual', fluencyType: 'accuracy',
      figureDependent: true, visualModels: ['shape'],
      misconceptions: [{ tag: 'geo/faces-edges-confuse', label: 'Confuses faces, edges and vertices' }],
      practiceModes: ['visual_model', 'short_answer', 'mcq'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['geo.2d-shapes'], strategy: 'faces are flat surfaces; edges are lines; vertices are corners' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'easy', stem: 'How many faces does a {solid} have?', answerRule: 'face count', misconceptionTag: 'geo/faces-edges-confuse' }] },
    { slug: 'geo.nets-views', name: 'Nets and views of solids', level: 'Primary 6',
      prerequisites: ['geo.3d-shapes'], masteryType: 'application', fluencyType: 'untimed-reasoning',
      figureDependent: true, visualModels: ['net'],
      misconceptions: [{ tag: 'geo/net-folding', label: 'Cannot mentally fold a net / mismatches a view to the solid' }],
      practiceModes: ['visual_model', 'mcq', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['geo.3d-shapes'], strategy: 'fold the net face by face; track top / front / side views' },
      questionStructures: [{ mode: 'visual_model', type: 'open_ended', difficulty: 'hard', stem: 'Draw the top view of the solid shown.', answerRule: 'footprint of the solid', misconceptionTag: 'geo/net-folding' }] },

    // ── Position & construction ──
    { slug: 'geo.position', name: 'Position and compass directions', level: 'Primary 5',
      prerequisites: ['geo.lines'], masteryType: 'application', fluencyType: 'accuracy',
      figureDependent: true, visualModels: ['grid'],
      misconceptions: [{ tag: 'geo/compass-confuse', label: 'Mixes up the compass directions (N/S/E/W)' }],
      practiceModes: ['visual_model', 'short_answer'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['geo.lines'], strategy: 'fix North first, then read relative positions' },
      questionStructures: [{ mode: 'visual_model', type: 'short_answer', difficulty: 'medium', stem: 'On the grid, in which direction is A from B?', answerRule: 'compass direction', misconceptionTag: 'geo/compass-confuse' }] },
    { slug: 'geo.construct', name: 'Drawing and constructing figures', level: 'Primary 6',
      prerequisites: ['geo.angle-measure', 'geo.lines'], masteryType: 'application', fluencyType: 'untimed-reasoning',
      figureDependent: true, visualModels: ['grid'],
      misconceptions: [{ tag: 'geo/construction-precision', label: 'Imprecise construction (wrong angle / length) breaks the figure' }],
      practiceModes: ['visual_model', 'diagnostic'],
      remediation: { onRepeatedFail: 'guided-replication', reinforce: ['geo.angle-measure'], strategy: 'mark the given parts first, then build the required angle/side' },
      questionStructures: [{ mode: 'visual_model', type: 'open_ended', difficulty: 'hard', stem: 'Given two sides on the grid, complete the figure with ∠TSV = 90°.', answerRule: 'construct the missing vertex', misconceptionTag: 'geo/construction-precision' }] },

    // ── Perimeter & area foundations ──
    { slug: 'geo.perimeter', name: 'Perimeter foundations (distance around)', level: 'Primary 4',
      prerequisites: ['geo.2d-properties', 'op.add.regroup'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 6, targetAccuracy: 90 }, render: 'katex', figureDependent: true, visualModels: ['shape', 'grid'],
      misconceptions: [{ tag: 'geo/perimeter-vs-area', label: 'Confuses perimeter (distance around) with area (covering)' }],
      practiceModes: ['visual_model', 'short_answer', 'fluency_drill'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['op.add.regroup'], strategy: 'add the lengths of all sides' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'easy', stem: 'A rectangle is {l} cm by {w} cm. Find its perimeter.', answerRule: '2(l+w)', misconceptionTag: 'geo/perimeter-vs-area' }] },
    { slug: 'geo.area-rect', name: 'Area foundations (covering; rectangles)', level: 'Primary 4',
      prerequisites: ['geo.perimeter', 'op.mult.2x1'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 6, targetAccuracy: 90 }, render: 'katex', figureDependent: true, visualModels: ['grid'],
      misconceptions: [{ tag: 'geo/area-add-sides', label: 'Adds the sides instead of multiplying for area' }],
      practiceModes: ['visual_model', 'short_answer', 'fluency_drill'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['op.mult.2x1'], strategy: 'count unit squares: rows × columns' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'easy', stem: 'A rectangle is {l} cm by {w} cm. Find its area.', answerRule: 'l*w', misconceptionTag: 'geo/area-add-sides' }] },
    { slug: 'geo.area-triangle', name: 'Area of triangles', level: 'Primary 5',
      prerequisites: ['geo.area-rect', 'geo.triangle-types'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 7, targetAccuracy: 90 }, render: 'katex', figureDependent: true, visualModels: ['shape'],
      misconceptions: [
        { tag: 'geo/triangle-no-half', label: 'Forgets the ½ (uses base × height)' },
        { tag: 'geo/wrong-height', label: 'Uses a slant side instead of the perpendicular height' }],
      practiceModes: ['visual_model', 'short_answer', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['geo.area-rect'], strategy: 'a triangle is half a rectangle: ½ × base × height' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: 'A triangle has base {b} cm and height {h} cm. Find its area.', answerRule: 'b*h/2', misconceptionTag: 'geo/triangle-no-half' }] },
    { slug: 'geo.circle', name: 'Circumference and area of a circle', level: 'Primary 6',
      prerequisites: ['geo.area-rect', 'dec.mult-whole'], masteryType: 'procedural', fluencyType: 'accuracy',
      render: 'katex', figureDependent: true, visualModels: ['shape'],
      misconceptions: [
        { tag: 'geo/radius-diameter-confuse', label: 'Confuses radius and diameter' },
        { tag: 'geo/circumference-area-formula', label: 'Swaps the circumference and area formulae' }],
      practiceModes: ['short_answer', 'mcq', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['geo.area-rect'], strategy: 'C = πd; Area = πr² — identify r vs d first' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: 'Find the area of a circle of radius {r} cm. (π = 22/7)', answerRule: '22/7*r*r', misconceptionTag: 'geo/circumference-area-formula' }] },
    { slug: 'geo.circle-parts', name: 'Perimeter and area of circle parts', level: 'Primary 6',
      prerequisites: ['geo.circle'], masteryType: 'procedural', fluencyType: 'accuracy',
      render: 'katex', figureDependent: true, visualModels: ['shape'],
      misconceptions: [{ tag: 'geo/forgot-straight-edges', label: 'Computes a quarter-circle perimeter from the arc only, forgetting the two radii' }],
      practiceModes: ['short_answer', 'worked_example', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['geo.circle'], strategy: 'perimeter of a part = arc + straight edges' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'hard', stem: 'Find the perimeter of a quarter circle of radius {r} cm. (π = 22/7)', answerRule: 'arc + 2r', misconceptionTag: 'geo/forgot-straight-edges' }] },
    { slug: 'geo.composite', name: 'Composite figures: area and perimeter', level: 'Primary 6',
      prerequisites: ['geo.area-triangle', 'geo.circle-parts', 'geo.perimeter'], masteryType: 'application', fluencyType: 'untimed-reasoning',
      render: 'katex', figureDependent: true, visualModels: ['shape', 'grid'],
      misconceptions: [
        { tag: 'geo/double-count-edges', label: 'Counts internal edges in the perimeter' },
        { tag: 'geo/missing-region', label: 'Misses a region when adding/subtracting areas' }],
      practiceModes: ['visual_model', 'short_answer', 'worked_example'],
      remediation: { onRepeatedFail: 'guided-replication', reinforce: ['geo.area-triangle', 'geo.circle-parts'], strategy: 'split into known shapes; add or subtract their areas' },
      questionStructures: [{ mode: 'visual_model', type: 'short_answer', difficulty: 'hard', stem: 'Find the shaded area of the composite figure.', answerRule: 'sum/difference of parts', misconceptionTag: 'geo/missing-region' }] },
  ],
};
