// MathPath domain: Operations (Primary 1 → 6). The most fluency-critical domain:
// the "facts" skills target AUTOMATICITY (fast, accurate recall), so they carry
// fluency thresholds (targetSeconds per item + targetAccuracy) and are surfaced
// by the Fluency feature. Procedural skills (regrouping, long mult/div) build on
// the facts; remediation routes a struggling student back to the prerequisite
// facts before re-attempting the procedure.
//
// fluency.targetSeconds = median per-item time for "fluent"; the placement/
// fluency engine compares median response time + accuracy against these.
// remediation = { onRepeatedFail: strategy, reinforce: [prereq slugs] }
//   strategies: 'reinforce-prerequisite' | 'worked-example' | 'guided-replication' | 'slow-accuracy-first'

export default {
  domain: 'Operations',
  topic: 'Operations',
  topicOrder: 1,
  level: 'Primary 1',
  skills: [
    // ── Addition ──
    { slug: 'op.add.facts', name: 'Addition facts within 20 (number bonds)', level: 'Primary 1',
      prerequisites: ['ns.count.to-20'], masteryType: 'factual', fluencyType: 'timed',
      fluency: { targetSeconds: 3, targetAccuracy: 95 },
      misconceptions: [
        { tag: 'add/count-all', label: 'Counts all from 1 instead of counting on / recalling' },
        { tag: 'add/off-by-one', label: 'Off-by-one from miscounting on fingers' }],
      practiceModes: ['fluency_drill', 'mcq'],
      remediation: { onRepeatedFail: 'reinforce-prerequisite', reinforce: ['ns.count.to-20'] },
      questionStructures: [{ mode: 'fluency_drill', type: 'short_answer', difficulty: 'easy', stem: '{a} + {b} = ?', answerRule: 'a+b (a,b≤10)', misconceptionTag: 'add/count-all' }] },
    { slug: 'op.add.2digit', name: 'Adding 2-digit numbers (no regrouping)', level: 'Primary 1',
      prerequisites: ['op.add.facts', 'ns.pv.tens-ones'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 6, targetAccuracy: 90 },
      misconceptions: [{ tag: 'add/place-misalign', label: 'Adds tens to ones (misaligns columns)' }],
      practiceModes: ['fluency_drill', 'short_answer'],
      remediation: { onRepeatedFail: 'reinforce-prerequisite', reinforce: ['ns.pv.tens-ones'] },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'easy', stem: '{a} + {b} = ?', answerRule: 'a+b (no carry)', misconceptionTag: 'add/place-misalign' }] },
    { slug: 'op.add.regroup', name: 'Adding with regrouping (carrying)', level: 'Primary 2',
      prerequisites: ['op.add.2digit'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 8, targetAccuracy: 90 },
      misconceptions: [{ tag: 'add/forgot-carry', label: 'Writes the full column sum, forgetting to carry' }],
      practiceModes: ['short_answer', 'worked_example', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['op.add.facts', 'ns.pv.3-digit'] },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: '{a} + {b} = ?', answerRule: 'a+b (with carry)', misconceptionTag: 'add/forgot-carry' }] },
    { slug: 'op.add.large', name: 'Adding 3–4 digit numbers', level: 'Primary 3',
      prerequisites: ['op.add.regroup', 'ns.pv.4-5-digit'], masteryType: 'procedural', fluencyType: 'accuracy',
      misconceptions: [{ tag: 'add/carry-cascade', label: 'Fails to cascade carries across several columns' }],
      practiceModes: ['short_answer'],
      remediation: { onRepeatedFail: 'reinforce-prerequisite', reinforce: ['op.add.regroup'] },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: '{a} + {b} = ?', answerRule: 'a+b', misconceptionTag: 'add/carry-cascade' }] },

    // ── Subtraction ──
    { slug: 'op.sub.facts', name: 'Subtraction facts within 20', level: 'Primary 1',
      prerequisites: ['op.add.facts'], masteryType: 'factual', fluencyType: 'timed',
      fluency: { targetSeconds: 3, targetAccuracy: 95 },
      misconceptions: [{ tag: 'sub/count-back-error', label: 'Miscounts when counting back' }],
      practiceModes: ['fluency_drill', 'mcq'],
      remediation: { onRepeatedFail: 'reinforce-prerequisite', reinforce: ['op.add.facts'] },
      questionStructures: [{ mode: 'fluency_drill', type: 'short_answer', difficulty: 'easy', stem: '{a} − {b} = ?', answerRule: 'a-b (a≤20)', misconceptionTag: 'sub/count-back-error' }] },
    { slug: 'op.sub.2digit', name: 'Subtracting 2-digit numbers (no regrouping)', level: 'Primary 1',
      prerequisites: ['op.sub.facts', 'ns.pv.tens-ones'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 6, targetAccuracy: 90 },
      misconceptions: [{ tag: 'sub/smaller-from-larger', label: 'Always subtracts the smaller digit from the larger in each column' }],
      practiceModes: ['fluency_drill', 'short_answer'],
      remediation: { onRepeatedFail: 'reinforce-prerequisite', reinforce: ['op.sub.facts'] },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'easy', stem: '{a} − {b} = ?', answerRule: 'a-b (no borrow)', misconceptionTag: 'sub/smaller-from-larger' }] },
    { slug: 'op.sub.regroup', name: 'Subtracting with regrouping (borrowing)', level: 'Primary 2',
      prerequisites: ['op.sub.2digit'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 9, targetAccuracy: 88 },
      misconceptions: [
        { tag: 'sub/smaller-from-larger', label: 'Subtracts smaller-from-larger instead of borrowing' },
        { tag: 'sub/borrow-no-reduce', label: 'Borrows but forgets to reduce the next column' }],
      practiceModes: ['short_answer', 'worked_example', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['op.sub.facts', 'ns.pv.3-digit'] },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: '{a} − {b} = ?', answerRule: 'a-b (with borrow)', misconceptionTag: 'sub/borrow-no-reduce' }] },
    { slug: 'op.sub.large', name: 'Subtracting 3–4 digit numbers (incl. across zeros)', level: 'Primary 3',
      prerequisites: ['op.sub.regroup', 'ns.pv.4-5-digit'], masteryType: 'procedural', fluencyType: 'accuracy',
      misconceptions: [{ tag: 'sub/across-zeros', label: 'Mishandles borrowing across zeros (e.g. 1000 − 47)' }],
      practiceModes: ['short_answer', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['op.sub.regroup'] },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: '{a} − {b} = ?', answerRule: 'a-b across zeros', misconceptionTag: 'sub/across-zeros' }] },

    // ── Multiplication ──
    { slug: 'op.mult.facts', name: 'Multiplication facts (times tables to 12)', level: 'Primary 3',
      prerequisites: ['ns.count.skip', 'op.add.facts'], masteryType: 'factual', fluencyType: 'timed',
      fluency: { targetSeconds: 3, targetAccuracy: 95 },
      misconceptions: [
        { tag: 'mult/repeated-add-slow', label: 'Repeatedly adds instead of recalling the fact' },
        { tag: 'mult/adjacent-fact', label: 'Returns an adjacent fact (7×8 → 54)' }],
      practiceModes: ['fluency_drill', 'mcq'],
      remediation: { onRepeatedFail: 'slow-accuracy-first', reinforce: ['ns.count.skip'] },
      questionStructures: [{ mode: 'fluency_drill', type: 'short_answer', difficulty: 'easy', stem: '{a} × {b} = ?', answerRule: 'a*b (a,b≤12)', misconceptionTag: 'mult/adjacent-fact' }] },
    { slug: 'op.mult.by-10-100', name: 'Multiplying by 10, 100 and 1000', level: 'Primary 3',
      prerequisites: ['op.mult.facts', 'ns.pv.4-5-digit'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 4, targetAccuracy: 92 },
      misconceptions: [{ tag: 'mult/append-zeros-decimal', label: 'Appends zeros even to decimals (3.5 × 10 → 3.50)' }],
      practiceModes: ['fluency_drill', 'mcq'],
      remediation: { onRepeatedFail: 'reinforce-prerequisite', reinforce: ['ns.pv.4-5-digit'] },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'easy', stem: '{a} × {p} = ?', answerRule: 'a*p (p∈{10,100,1000})', misconceptionTag: 'mult/append-zeros-decimal' }] },
    { slug: 'op.mult.2x1', name: 'Multiplying 2–3 digit by 1 digit', level: 'Primary 3',
      prerequisites: ['op.mult.facts', 'op.add.regroup'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 12, targetAccuracy: 88 },
      misconceptions: [{ tag: 'mult/forgot-carry', label: 'Forgets to carry into the next product column' }],
      practiceModes: ['short_answer', 'worked_example'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['op.mult.facts'] },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: '{a} × {b} = ?', answerRule: 'a*b (b<10)', misconceptionTag: 'mult/forgot-carry' }] },
    { slug: 'op.mult.long', name: 'Long multiplication (2 digit × 2 digit)', level: 'Primary 4',
      prerequisites: ['op.mult.2x1', 'op.mult.by-10-100', 'op.add.large'], masteryType: 'procedural', fluencyType: 'accuracy',
      misconceptions: [
        { tag: 'mult/missing-placeholder', label: 'Omits the zero placeholder on the second partial product' },
        { tag: 'mult/partial-add', label: 'Adds the partial products incorrectly' }],
      practiceModes: ['short_answer', 'worked_example', 'diagnostic'],
      remediation: { onRepeatedFail: 'guided-replication', reinforce: ['op.mult.2x1', 'op.mult.by-10-100'] },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'hard', stem: '{a} × {b} = ?', answerRule: 'a*b (both 2-digit)', misconceptionTag: 'mult/missing-placeholder' }] },

    // ── Division ──
    { slug: 'op.div.facts', name: 'Division facts (inverse of times tables)', level: 'Primary 3',
      prerequisites: ['op.mult.facts'], masteryType: 'factual', fluencyType: 'timed',
      fluency: { targetSeconds: 4, targetAccuracy: 92 },
      misconceptions: [{ tag: 'div/order-reversal', label: 'Reverses the dividend and divisor' }],
      practiceModes: ['fluency_drill', 'mcq'],
      remediation: { onRepeatedFail: 'reinforce-prerequisite', reinforce: ['op.mult.facts'] },
      questionStructures: [{ mode: 'fluency_drill', type: 'short_answer', difficulty: 'easy', stem: '{ab} ÷ {b} = ?', answerRule: 'a (exact)', misconceptionTag: 'div/order-reversal' }] },
    { slug: 'op.div.short', name: 'Short division by a 1-digit number', level: 'Primary 3',
      prerequisites: ['op.div.facts', 'ns.pv.4-5-digit'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 14, targetAccuracy: 85 },
      misconceptions: [{ tag: 'div/drop-zero', label: 'Drops a zero in the quotient when a place divides evenly to 0' }],
      practiceModes: ['short_answer', 'worked_example'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['op.div.facts'] },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: '{a} ÷ {b} = ?', answerRule: 'a/b (b<10, exact)', misconceptionTag: 'div/drop-zero' }] },
    { slug: 'op.div.remainder', name: 'Division with remainders (interpreting)', level: 'Primary 4',
      prerequisites: ['op.div.short'], masteryType: 'application', fluencyType: 'accuracy',
      misconceptions: [{ tag: 'div/ignore-remainder', label: 'Ignores the remainder or always rounds the same way regardless of context' }],
      practiceModes: ['short_answer', 'mcq', 'worked_example'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['op.div.short'] },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: '{a} ÷ {b} = ? remainder ?', answerRule: 'quotient & remainder', misconceptionTag: 'div/ignore-remainder' }] },
    { slug: 'op.div.long', name: 'Long division by a 2-digit number', level: 'Primary 5',
      prerequisites: ['op.div.short', 'op.mult.2x1', 'ns.estimate.products'], masteryType: 'procedural', fluencyType: 'accuracy',
      misconceptions: [
        { tag: 'div/bad-estimate', label: 'Poor estimate for each quotient digit (too big / too small)' },
        { tag: 'div/bring-down', label: 'Forgets to bring down the next digit' }],
      practiceModes: ['short_answer', 'worked_example', 'diagnostic'],
      remediation: { onRepeatedFail: 'guided-replication', reinforce: ['op.div.short', 'ns.estimate.products'] },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'hard', stem: '{a} ÷ {b} = ?', answerRule: 'a/b (b 2-digit)', misconceptionTag: 'div/bad-estimate' }] },

    // ── Mental arithmetic ──
    { slug: 'op.mental.add-sub', name: 'Mental addition & subtraction strategies', level: 'Primary 3',
      prerequisites: ['op.add.regroup', 'op.sub.regroup'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 6, targetAccuracy: 88 },
      misconceptions: [{ tag: 'mental/no-compensation', label: 'Does not use rounding/compensation (e.g. +99 as +100−1)' }],
      practiceModes: ['fluency_drill', 'mcq'],
      remediation: { onRepeatedFail: 'guided-replication', reinforce: ['op.add.facts', 'op.sub.facts'] },
      questionStructures: [{ mode: 'fluency_drill', type: 'short_answer', difficulty: 'medium', stem: '{a} + {b} = ?  (mentally)', answerRule: 'a+b', misconceptionTag: 'mental/no-compensation' }] },
    { slug: 'op.mental.mult-div', name: 'Mental multiplication & division strategies', level: 'Primary 4',
      prerequisites: ['op.mult.by-10-100', 'op.div.facts'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 7, targetAccuracy: 88 },
      misconceptions: [{ tag: 'mental/no-factoring', label: 'Does not factor/decompose (×25 as ×100÷4)' }],
      practiceModes: ['fluency_drill', 'mcq'],
      remediation: { onRepeatedFail: 'guided-replication', reinforce: ['op.mult.facts', 'op.mult.by-10-100'] },
      questionStructures: [{ mode: 'fluency_drill', type: 'short_answer', difficulty: 'medium', stem: '{a} × {b} = ?  (mentally)', answerRule: 'a*b', misconceptionTag: 'mental/no-factoring' }] },

    // ── Order of operations ──
    { slug: 'op.order-of-ops', name: 'Order of operations (× ÷ before + −)', level: 'Primary 5',
      prerequisites: ['op.mult.2x1', 'op.add.large', 'op.sub.large'], masteryType: 'procedural', fluencyType: 'timed',
      fluency: { targetSeconds: 10, targetAccuracy: 88 },
      misconceptions: [{ tag: 'order/left-to-right', label: 'Evaluates strictly left-to-right, ignoring precedence' }],
      practiceModes: ['short_answer', 'mcq', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['op.mult.facts'] },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: '{a} + {b} × {c} = ?', answerRule: 'a + b*c', misconceptionTag: 'order/left-to-right' }] },
    { slug: 'op.order-of-ops.brackets', name: 'Order of operations with brackets', level: 'Primary 6',
      prerequisites: ['op.order-of-ops'], masteryType: 'procedural', fluencyType: 'accuracy',
      misconceptions: [{ tag: 'order/ignore-brackets', label: 'Ignores brackets or resolves them last' }],
      practiceModes: ['short_answer', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['op.order-of-ops'] },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'hard', stem: '{a} − {b} × ({c} − {d} ÷ {e}) = ?', answerRule: 'BODMAS', misconceptionTag: 'order/ignore-brackets' }] },

    // ── Number theory (factors & multiples) ──
    { slug: 'op.factors-multiples', name: 'Factors and multiples', level: 'Primary 4',
      prerequisites: ['op.mult.facts', 'op.div.facts'], masteryType: 'conceptual', fluencyType: 'timed',
      fluency: { targetSeconds: 5, targetAccuracy: 90 },
      misconceptions: [{ tag: 'op/factor-multiple-confuse', label: 'Confuses factors (divide into) with multiples (times of)' }],
      practiceModes: ['fluency_drill', 'mcq', 'short_answer'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['op.mult.facts'], strategy: 'factors fit INTO a number; multiples are the times-table OF it' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'easy', stem: 'List all the factors of {n}.', answerRule: 'divisors of n', misconceptionTag: 'op/factor-multiple-confuse' }] },
    { slug: 'op.hcf-lcm', name: 'HCF and LCM (incl. word problems)', level: 'Primary 6',
      prerequisites: ['op.factors-multiples'], masteryType: 'application', fluencyType: 'accuracy',
      misconceptions: [{ tag: 'op/hcf-lcm-confuse', label: 'Uses HCF when the problem needs LCM (or vice-versa)' }],
      practiceModes: ['short_answer', 'mcq', 'worked_example'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['op.factors-multiples'], strategy: 'sharing/grouping equally → HCF; events repeating together → LCM' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: 'Find the highest common factor (HCF) of {x} and {y}.', answerRule: 'gcd(x,y)', misconceptionTag: 'op/hcf-lcm-confuse' }] },

    // ── Problem-solving heuristics ──
    { slug: 'op.model-drawing', name: 'Model drawing (bar models)', level: 'Primary 3',
      prerequisites: ['op.add.regroup', 'op.sub.regroup'], masteryType: 'conceptual', fluencyType: 'untimed-reasoning',
      visualModels: ['bar'],
      misconceptions: [{ tag: 'op/model-wrong-parts', label: 'Draws the parts/whole in the wrong relationship' }],
      practiceModes: ['visual_model', 'worked_example', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['op.sub.regroup'], strategy: 'draw the whole, then the parts; label what is known and unknown' },
      questionStructures: [{ mode: 'visual_model', type: 'short_answer', difficulty: 'medium', stem: 'Draw a bar model and solve: {part-whole word problem}.', answerRule: 'whole − part / sum of parts', misconceptionTag: 'op/model-wrong-parts' }] },
    { slug: 'op.word-multi-step', name: 'Multi-step word problems', level: 'Primary 5',
      prerequisites: ['op.model-drawing', 'op.mult.2x1', 'op.div.short'], masteryType: 'application', fluencyType: 'untimed-reasoning',
      visualModels: ['bar'],
      misconceptions: [{ tag: 'op/wrong-operation-choice', label: 'Chooses the wrong operation / order of steps' }],
      practiceModes: ['short_answer', 'worked_example', 'diagnostic'],
      remediation: { onRepeatedFail: 'guided-replication', reinforce: ['op.model-drawing'], strategy: 'break into steps; solve one part, then use it in the next' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'hard', stem: '{multi-step word problem}', answerRule: 'sequence of operations', misconceptionTag: 'op/wrong-operation-choice' }] },
  ],
};
