// MathPath domain: Statistics (Primary 2 → 6). Data representation and
// interpretation: tables, picture/bar/line graphs, pie charts, and average
// (mean). Authored for low cognitive load — one chart, one question; every
// reading skill is figureDependent with a clear visual model. The progression
// builds interpretation accuracy (read a value → compare values → draw a
// conclusion) before computation (mean).
//
// extra metadata: render:'katex', figureDependent,
//   visualModels:['table','picture-graph','bar-graph','line-graph','pie-chart']

export default {
  domain: 'Statistics',
  topic: 'Statistics',
  topicOrder: 9,
  level: 'Primary 2',
  skills: [
    { slug: 'stat.tables', name: 'Reading tables', level: 'Primary 2',
      prerequisites: ['ns.pv.3-digit'], masteryType: 'application', fluencyType: 'accuracy',
      figureDependent: true, visualModels: ['table'],
      misconceptions: [{ tag: 'stat/row-column-mix', label: 'Reads the wrong row/column intersection' }],
      practiceModes: ['visual_model', 'mcq', 'short_answer'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['ns.pv.3-digit'], strategy: 'trace the row and column to where they meet' },
      questionStructures: [{ mode: 'visual_model', type: 'short_answer', difficulty: 'easy', stem: 'From the table, how many {x} were there in {category}?', answerRule: 'cell value', misconceptionTag: 'stat/row-column-mix' }] },
    { slug: 'stat.picture-graphs', name: 'Picture graphs', level: 'Primary 2',
      prerequisites: ['stat.tables', 'ns.count.skip'], masteryType: 'application', fluencyType: 'accuracy',
      figureDependent: true, visualModels: ['picture-graph'],
      misconceptions: [{ tag: 'stat/ignore-key', label: 'Counts pictures without using the key (1 picture = many)' }],
      practiceModes: ['visual_model', 'short_answer', 'mcq'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['ns.count.skip'], strategy: 'read the key first, then multiply by the number of pictures' },
      questionStructures: [{ mode: 'visual_model', type: 'short_answer', difficulty: 'easy', stem: 'Each picture stands for {k}. How many does {category} represent?', answerRule: 'pictures × k', misconceptionTag: 'stat/ignore-key' }] },
    { slug: 'stat.bar-graphs', name: 'Bar graphs', level: 'Primary 3',
      prerequisites: ['stat.tables'], masteryType: 'application', fluencyType: 'accuracy',
      figureDependent: true, visualModels: ['bar-graph'],
      misconceptions: [{ tag: 'stat/scale-interval', label: 'Misreads the axis scale / reads between gridlines wrongly' }],
      practiceModes: ['visual_model', 'short_answer', 'mcq'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['stat.tables'], strategy: 'work out the value of one gridline first' },
      questionStructures: [{ mode: 'visual_model', type: 'short_answer', difficulty: 'medium', stem: 'From the bar graph, how many books were borrowed on {day}?', answerRule: 'bar height', misconceptionTag: 'stat/scale-interval' }] },
    { slug: 'stat.line-graphs', name: 'Line graphs', level: 'Primary 4',
      prerequisites: ['stat.bar-graphs'], masteryType: 'application', fluencyType: 'accuracy',
      figureDependent: true, visualModels: ['line-graph'],
      misconceptions: [{ tag: 'stat/point-misread', label: 'Reads a point off the wrong axis value' }],
      practiceModes: ['visual_model', 'short_answer', 'mcq'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['stat.bar-graphs'], strategy: 'drop a line from the point to each axis' },
      questionStructures: [{ mode: 'visual_model', type: 'short_answer', difficulty: 'medium', stem: 'From the line graph, what was the value in {month}?', answerRule: 'point value', misconceptionTag: 'stat/point-misread' }] },
    { slug: 'stat.interpret', name: 'Interpreting and comparing data', level: 'Primary 5',
      prerequisites: ['stat.bar-graphs', 'stat.line-graphs'], masteryType: 'application', fluencyType: 'untimed-reasoning',
      figureDependent: true, visualModels: ['bar-graph', 'line-graph', 'table'],
      misconceptions: [{ tag: 'stat/trend-overread', label: 'Over-reads the data (claims a trend/cause the graph does not show)' }],
      practiceModes: ['visual_model', 'mcq', 'short_answer'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['stat.line-graphs'], strategy: 'answer only what the data shows; compare values directly' },
      questionStructures: [{ mode: 'visual_model', type: 'mcq', difficulty: 'medium', stem: 'Between which two periods did the value increase the most?', answerRule: 'largest positive difference', misconceptionTag: 'stat/trend-overread' }] },
    { slug: 'stat.average-intro', name: 'Average (mean) — concept', level: 'Primary 5',
      prerequisites: ['op.div.short', 'stat.tables'], masteryType: 'conceptual', fluencyType: 'timed',
      fluency: { targetSeconds: 8, targetAccuracy: 90 }, render: 'katex', visualModels: ['bar-graph'],
      misconceptions: [
        { tag: 'stat/mean-not-divide', label: 'Adds the values but forgets to divide by how many' },
        { tag: 'stat/mean-ignore-zero', label: 'Ignores zero values when counting how many' }],
      practiceModes: ['fluency_drill', 'short_answer', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['op.div.short'], strategy: 'mean = total ÷ number of values (count every value, including zeros)' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'medium', stem: 'Find the average of: {set}.', answerRule: 'sum ÷ count', misconceptionTag: 'stat/mean-not-divide' }] },
    { slug: 'stat.average-apply', name: 'Mean: finding the total or a missing value', level: 'Primary 6',
      prerequisites: ['stat.average-intro'], masteryType: 'application', fluencyType: 'untimed-reasoning',
      render: 'katex', visualModels: ['bar-graph'],
      misconceptions: [{ tag: 'stat/mean-reverse', label: 'Cannot work backwards from the mean to the total (or a missing value)' }],
      practiceModes: ['short_answer', 'worked_example', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['stat.average-intro'], strategy: 'total = mean × number of values; then find the missing one' },
      questionStructures: [{ mode: 'short_answer', type: 'short_answer', difficulty: 'hard', stem: 'The mean of {n} numbers is {m}. {k} of them total {t}. Find the last value.', answerRule: 'm*n - t', misconceptionTag: 'stat/mean-reverse' }] },
    { slug: 'stat.pie-charts', name: 'Pie charts', level: 'Primary 6',
      prerequisites: ['stat.bar-graphs', 'pct.of-quantity', 'fr.of-quantity'], masteryType: 'application', fluencyType: 'accuracy',
      figureDependent: true, render: 'katex', visualModels: ['pie-chart'],
      misconceptions: [{ tag: 'stat/pie-angle-fraction', label: 'Reads a sector as a count, not a fraction/angle of the whole' }],
      practiceModes: ['visual_model', 'short_answer', 'diagnostic'],
      remediation: { onRepeatedFail: 'worked-example', reinforce: ['fr.of-quantity', 'pct.of-quantity'], strategy: 'a sector is a fraction of 360° (or 100%) of the total' },
      questionStructures: [{ mode: 'visual_model', type: 'short_answer', difficulty: 'hard', stem: 'A sector is {p}% of the pie chart. If the total is {total}, how many does it represent?', answerRule: 'p/100*total', misconceptionTag: 'stat/pie-angle-fraction' }] },
  ],
};
