import { measurementSkillGraph } from './MeasurementSkillGraph.js';

const SKILL_IDS = new Set(measurementSkillGraph.skillIds);

const families = [
  {
    id: 'QF_ME001_001',
    skillId: 'ME001',
    name: 'Length and its units (cm, m, km) — Practice',
    description: 'Length and its units (cm, m, km) question.',
    difficulty: 3,
    generatorKind: 'meaMeaLength',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/wrong-unit'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_ME001_002',
    skillId: 'ME001',
    name: 'Length and its units (cm, m, km) — MCQ',
    description: 'Length and its units (cm, m, km) question.',
    difficulty: 3,
    generatorKind: 'meaMeaLengthMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/wrong-unit'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_ME002_001',
    skillId: 'ME002',
    name: 'Mass and its units (g, kg) — Practice',
    description: 'Mass and its units (g, kg) question.',
    difficulty: 3,
    generatorKind: 'meaMeaMass',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/wrong-unit'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_ME002_002',
    skillId: 'ME002',
    name: 'Mass and its units (g, kg) — MCQ',
    description: 'Mass and its units (g, kg) question.',
    difficulty: 3,
    generatorKind: 'meaMeaMassMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/wrong-unit'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_ME003_001',
    skillId: 'ME003',
    name: 'Volume and capacity (ml, L) — Practice',
    description: 'Volume and capacity (ml, L) question.',
    difficulty: 3,
    generatorKind: 'meaMeaVolumeCapacity',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/capacity-volume-confuse'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_ME003_002',
    skillId: 'ME003',
    name: 'Volume and capacity (ml, L) — MCQ',
    description: 'Volume and capacity (ml, L) question.',
    difficulty: 3,
    generatorKind: 'meaMeaVolumeCapacityMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/capacity-volume-confuse'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_ME004_001',
    skillId: 'ME004',
    name: 'Reading measuring scales — Practice',
    description: 'Reading measuring scales question.',
    difficulty: 3,
    generatorKind: 'meaMeaReadScales',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/scale-interval'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME004_002',
    skillId: 'ME004',
    name: 'Reading measuring scales — MCQ',
    description: 'Reading measuring scales question.',
    difficulty: 3,
    generatorKind: 'meaMeaReadScalesMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/scale-interval'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME005_001',
    skillId: 'ME005',
    name: 'Telling time and the 24-hour clock — Practice',
    description: 'Telling time and the 24-hour clock question.',
    difficulty: 3,
    generatorKind: 'meaMeaTimeTell',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/24hr-convert'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME005_002',
    skillId: 'ME005',
    name: 'Telling time and the 24-hour clock — MCQ',
    description: 'Telling time and the 24-hour clock question.',
    difficulty: 3,
    generatorKind: 'meaMeaTimeTellMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/24hr-convert'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME006_001',
    skillId: 'ME006',
    name: 'Duration and time intervals — Practice',
    description: 'Duration and time intervals question.',
    difficulty: 3,
    generatorKind: 'meaMeaTimeDuration',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/time-base-60'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME006_002',
    skillId: 'ME006',
    name: 'Duration and time intervals — MCQ',
    description: 'Duration and time intervals question.',
    difficulty: 3,
    generatorKind: 'meaMeaTimeDurationMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/time-base-60'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME007_001',
    skillId: 'ME007',
    name: 'Unit conversions (length, mass, volume) — Practice',
    description: 'Unit conversions (length, mass, volume) question.',
    difficulty: 3,
    generatorKind: 'meaMeaUnitConvert',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 6,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/convert-direction'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME007_002',
    skillId: 'ME007',
    name: 'Unit conversions (length, mass, volume) — MCQ',
    description: 'Unit conversions (length, mass, volume) question.',
    difficulty: 3,
    generatorKind: 'meaMeaUnitConvertMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 6,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/convert-direction'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME008_001',
    skillId: 'ME008',
    name: 'Comparing and converting measurements — Practice',
    description: 'Comparing and converting measurements question.',
    difficulty: 3,
    generatorKind: 'meaMeaCompareMeasures',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/compare-mixed-units'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME008_002',
    skillId: 'ME008',
    name: 'Comparing and converting measurements — MCQ',
    description: 'Comparing and converting measurements question.',
    difficulty: 3,
    generatorKind: 'meaMeaCompareMeasuresMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/compare-mixed-units'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME009_001',
    skillId: 'ME009',
    name: 'Perimeter in measurement contexts — Practice',
    description: 'Perimeter in measurement contexts question.',
    difficulty: 3,
    generatorKind: 'meaMeaPerimeterApply',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/perimeter-units'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME009_002',
    skillId: 'ME009',
    name: 'Perimeter in measurement contexts — MCQ',
    description: 'Perimeter in measurement contexts question.',
    difficulty: 3,
    generatorKind: 'meaMeaPerimeterApplyMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/perimeter-units'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME010_001',
    skillId: 'ME010',
    name: 'Area in measurement contexts — Practice',
    description: 'Area in measurement contexts question.',
    difficulty: 3,
    generatorKind: 'meaMeaAreaApply',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/area-units'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME010_002',
    skillId: 'ME010',
    name: 'Area in measurement contexts — MCQ',
    description: 'Area in measurement contexts question.',
    difficulty: 3,
    generatorKind: 'meaMeaAreaApplyMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/area-units'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME011_001',
    skillId: 'ME011',
    name: 'Volume of cubes and cuboids — Practice',
    description: 'Volume of cubes and cuboids question.',
    difficulty: 3,
    generatorKind: 'meaMeaVolumeCuboid',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/volume-add-edges'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME011_002',
    skillId: 'ME011',
    name: 'Volume of cubes and cuboids — MCQ',
    description: 'Volume of cubes and cuboids question.',
    difficulty: 3,
    generatorKind: 'meaMeaVolumeCuboidMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 8,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/volume-add-edges'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME012_001',
    skillId: 'ME012',
    name: 'Nets and volume of cuboids — Practice',
    description: 'Nets and volume of cuboids question.',
    difficulty: 3,
    generatorKind: 'meaMeaNetsVolume',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/net-dimensions'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME012_002',
    skillId: 'ME012',
    name: 'Nets and volume of cuboids — MCQ',
    description: 'Nets and volume of cuboids question.',
    difficulty: 3,
    generatorKind: 'meaMeaNetsVolumeMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/net-dimensions'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME013_001',
    skillId: 'ME013',
    name: 'Volume, water level and rate — Practice',
    description: 'Volume, water level and rate question.',
    difficulty: 3,
    generatorKind: 'meaMeaVolumeRate',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/rate-volume-confuse'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME013_002',
    skillId: 'ME013',
    name: 'Volume, water level and rate — MCQ',
    description: 'Volume, water level and rate question.',
    difficulty: 3,
    generatorKind: 'meaMeaVolumeRateMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/rate-volume-confuse'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME014_001',
    skillId: 'ME014',
    name: 'Money word problems and reasoning — Practice',
    description: 'Money word problems and reasoning question.',
    difficulty: 3,
    generatorKind: 'meaMeaMoney',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/money-decimal-place'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_ME014_002',
    skillId: 'ME014',
    name: 'Money word problems and reasoning — MCQ',
    description: 'Money word problems and reasoning question.',
    difficulty: 3,
    generatorKind: 'meaMeaMoneyMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['mea/money-decimal-place'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
];

const familyById = new Map(families.map((family) => [family.id, family]));
const familiesBySkill = families.reduce((acc, family) => {
  if (!acc[family.skillId]) acc[family.skillId] = [];
  acc[family.skillId].push(family);
  return acc;
}, {});

export function getQuestionFamily(familyId) {
  return familyById.get(familyId) || null;
}

export function getQuestionFamiliesBySkill(skillId) {
  return familiesBySkill[skillId] ? [...familiesBySkill[skillId]] : [];
}

export function getAllQuestionFamilies() {
  return [...families];
}

export const measurementQuestionFamilies = families;
export default measurementQuestionFamilies;
