import { numberSenseSkillGraph } from './NumberSenseSkillGraph.js';

const SKILL_IDS = new Set(numberSenseSkillGraph.skillIds);

const families = [
  {
    id: 'QF_NS001_001',
    skillId: 'NS001',
    name: 'Counting to 20 — Practice',
    description: 'Counting to 20 question.',
    difficulty: 2,
    generatorKind: 'nsNsCountTo20',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 2,
    masteryTargetAccuracy: 92,
    masteryQuestionCount: 10,
    misconceptionTags: ['count/teen-ty', 'count/skip-number'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_NS001_002',
    skillId: 'NS001',
    name: 'Counting to 20 — MCQ',
    description: 'Counting to 20 question.',
    difficulty: 2,
    generatorKind: 'nsNsCountTo20MCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 2,
    masteryTargetAccuracy: 92,
    masteryQuestionCount: 10,
    misconceptionTags: ['count/teen-ty', 'count/skip-number'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_NS002_001',
    skillId: 'NS002',
    name: 'Counting to 100 — Practice',
    description: 'Counting to 100 question.',
    difficulty: 2,
    generatorKind: 'nsNsCountTo100',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 2,
    masteryTargetAccuracy: 92,
    masteryQuestionCount: 10,
    misconceptionTags: ['count/decade-boundary'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_NS002_002',
    skillId: 'NS002',
    name: 'Counting to 100 — MCQ',
    description: 'Counting to 100 question.',
    difficulty: 2,
    generatorKind: 'nsNsCountTo100MCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 2,
    masteryTargetAccuracy: 92,
    masteryQuestionCount: 10,
    misconceptionTags: ['count/decade-boundary'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_NS003_001',
    skillId: 'NS003',
    name: 'Skip counting (2s, 5s, 10s) — Practice',
    description: 'Skip counting (2s, 5s, 10s) question.',
    difficulty: 2,
    generatorKind: 'nsNsCountSkip',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 2,
    masteryTargetAccuracy: 92,
    masteryQuestionCount: 10,
    misconceptionTags: ['count/lose-step'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_NS003_002',
    skillId: 'NS003',
    name: 'Skip counting (2s, 5s, 10s) — MCQ',
    description: 'Skip counting (2s, 5s, 10s) question.',
    difficulty: 2,
    generatorKind: 'nsNsCountSkipMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 2,
    masteryTargetAccuracy: 92,
    masteryQuestionCount: 10,
    misconceptionTags: ['count/lose-step'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_NS004_001',
    skillId: 'NS004',
    name: 'Counting to 1000 — Practice',
    description: 'Counting to 1000 question.',
    difficulty: 2,
    generatorKind: 'nsNsCountTo1000',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 3,
    masteryTargetAccuracy: 92,
    masteryQuestionCount: 10,
    misconceptionTags: ['count/hundred-boundary'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_NS004_002',
    skillId: 'NS004',
    name: 'Counting to 1000 — MCQ',
    description: 'Counting to 1000 question.',
    difficulty: 2,
    generatorKind: 'nsNsCountTo1000MCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 3,
    masteryTargetAccuracy: 92,
    masteryQuestionCount: 10,
    misconceptionTags: ['count/hundred-boundary'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_NS005_001',
    skillId: 'NS005',
    name: 'Place value: tens and ones — Practice',
    description: 'Place value: tens and ones question.',
    difficulty: 2,
    generatorKind: 'nsNsPvTensOnes',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['pv/digit-vs-value', 'pv/teen-reversal'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_NS005_002',
    skillId: 'NS005',
    name: 'Place value: tens and ones — MCQ',
    description: 'Place value: tens and ones question.',
    difficulty: 2,
    generatorKind: 'nsNsPvTensOnesMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['pv/digit-vs-value', 'pv/teen-reversal'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_NS006_001',
    skillId: 'NS006',
    name: 'Place value to 1000 — Practice',
    description: 'Place value to 1000 question.',
    difficulty: 2,
    generatorKind: 'nsNsPv3Digit',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['pv/zero-placeholder'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_NS006_002',
    skillId: 'NS006',
    name: 'Place value to 1000 — MCQ',
    description: 'Place value to 1000 question.',
    difficulty: 2,
    generatorKind: 'nsNsPv3DigitMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['pv/zero-placeholder'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_NS007_001',
    skillId: 'NS007',
    name: 'Place value to 100 000 — Practice',
    description: 'Place value to 100 000 question.',
    difficulty: 2,
    generatorKind: 'nsNsPv45Digit',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['pv/grouping'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_NS007_002',
    skillId: 'NS007',
    name: 'Place value to 100 000 — MCQ',
    description: 'Place value to 100 000 question.',
    difficulty: 2,
    generatorKind: 'nsNsPv45DigitMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['pv/grouping'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_NS008_001',
    skillId: 'NS008',
    name: 'Place value to 1 000 000 — Practice',
    description: 'Place value to 1 000 000 question.',
    difficulty: 2,
    generatorKind: 'nsNsPv6Digit',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['pv/place-name'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_NS008_002',
    skillId: 'NS008',
    name: 'Place value to 1 000 000 — MCQ',
    description: 'Place value to 1 000 000 question.',
    difficulty: 2,
    generatorKind: 'nsNsPv6DigitMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['pv/place-name'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_NS009_001',
    skillId: 'NS009',
    name: 'Comparing numbers to 100 — Practice',
    description: 'Comparing numbers to 100 question.',
    difficulty: 2,
    generatorKind: 'nsNsCompareTo100',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 3,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['compare/leading-digit'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS009_002',
    skillId: 'NS009',
    name: 'Comparing numbers to 100 — MCQ',
    description: 'Comparing numbers to 100 question.',
    difficulty: 2,
    generatorKind: 'nsNsCompareTo100MCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 3,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['compare/leading-digit'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS010_001',
    skillId: 'NS010',
    name: 'Comparing numbers to 100 000 — Practice',
    description: 'Comparing numbers to 100 000 question.',
    difficulty: 2,
    generatorKind: 'nsNsCompareLarge',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 4,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['compare/length-not-value'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS010_002',
    skillId: 'NS010',
    name: 'Comparing numbers to 100 000 — MCQ',
    description: 'Comparing numbers to 100 000 question.',
    difficulty: 2,
    generatorKind: 'nsNsCompareLargeMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 4,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['compare/length-not-value'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS011_001',
    skillId: 'NS011',
    name: 'Ordering numbers to 100 — Practice',
    description: 'Ordering numbers to 100 question.',
    difficulty: 2,
    generatorKind: 'nsNsOrderTo100',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['order/local-not-global'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS011_002',
    skillId: 'NS011',
    name: 'Ordering numbers to 100 — MCQ',
    description: 'Ordering numbers to 100 question.',
    difficulty: 2,
    generatorKind: 'nsNsOrderTo100MCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['order/local-not-global'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS012_001',
    skillId: 'NS012',
    name: 'Ordering numbers to 100 000 — Practice',
    description: 'Ordering numbers to 100 000 question.',
    difficulty: 2,
    generatorKind: 'nsNsOrderLarge',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['order/by-length'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS012_002',
    skillId: 'NS012',
    name: 'Ordering numbers to 100 000 — MCQ',
    description: 'Ordering numbers to 100 000 question.',
    difficulty: 2,
    generatorKind: 'nsNsOrderLargeMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['order/by-length'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS013_001',
    skillId: 'NS013',
    name: 'Number patterns: skip-count sequences — Practice',
    description: 'Number patterns: skip-count sequences question.',
    difficulty: 2,
    generatorKind: 'nsNsPatternSkip',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['pattern/step-drift'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS013_002',
    skillId: 'NS013',
    name: 'Number patterns: skip-count sequences — MCQ',
    description: 'Number patterns: skip-count sequences question.',
    difficulty: 2,
    generatorKind: 'nsNsPatternSkipMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['pattern/step-drift'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS014_001',
    skillId: 'NS014',
    name: 'Number patterns: constant difference — Practice',
    description: 'Number patterns: constant difference question.',
    difficulty: 2,
    generatorKind: 'nsNsPatternArithmetic',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['pattern/op-confusion'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS014_002',
    skillId: 'NS014',
    name: 'Number patterns: constant difference — MCQ',
    description: 'Number patterns: constant difference question.',
    difficulty: 2,
    generatorKind: 'nsNsPatternArithmeticMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['pattern/op-confusion'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS015_001',
    skillId: 'NS015',
    name: 'Number patterns: position rules — Practice',
    description: 'Number patterns: position rules question.',
    difficulty: 2,
    generatorKind: 'nsNsPatternComplex',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['pattern/assume-linear'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS015_002',
    skillId: 'NS015',
    name: 'Number patterns: position rules — MCQ',
    description: 'Number patterns: position rules question.',
    difficulty: 2,
    generatorKind: 'nsNsPatternComplexMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['pattern/assume-linear'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS016_001',
    skillId: 'NS016',
    name: 'Rounding to the nearest 10 and 100 — Practice',
    description: 'Rounding to the nearest 10 and 100 question.',
    difficulty: 2,
    generatorKind: 'nsNsRound10100',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 4,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['round/always-up', 'round/wrong-digit'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS016_002',
    skillId: 'NS016',
    name: 'Rounding to the nearest 10 and 100 — MCQ',
    description: 'Rounding to the nearest 10 and 100 question.',
    difficulty: 2,
    generatorKind: 'nsNsRound10100MCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 4,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['round/always-up', 'round/wrong-digit'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS017_001',
    skillId: 'NS017',
    name: 'Rounding to the nearest 1000 — Practice',
    description: 'Rounding to the nearest 1000 question.',
    difficulty: 2,
    generatorKind: 'nsNsRound1000',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['round/no-cascade'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS017_002',
    skillId: 'NS017',
    name: 'Rounding to the nearest 1000 — MCQ',
    description: 'Rounding to the nearest 1000 question.',
    difficulty: 2,
    generatorKind: 'nsNsRound1000MCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['round/no-cascade'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS018_001',
    skillId: 'NS018',
    name: 'Estimating sums and differences — Practice',
    description: 'Estimating sums and differences question.',
    difficulty: 2,
    generatorKind: 'nsNsEstimateSums',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['estimate/exact-not-estimate'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS018_002',
    skillId: 'NS018',
    name: 'Estimating sums and differences — MCQ',
    description: 'Estimating sums and differences question.',
    difficulty: 2,
    generatorKind: 'nsNsEstimateSumsMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['estimate/exact-not-estimate'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS019_001',
    skillId: 'NS019',
    name: 'Estimating products and quotients — Practice',
    description: 'Estimating products and quotients question.',
    difficulty: 2,
    generatorKind: 'nsNsEstimateProducts',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['estimate/round-one'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS019_002',
    skillId: 'NS019',
    name: 'Estimating products and quotients — MCQ',
    description: 'Estimating products and quotients question.',
    difficulty: 2,
    generatorKind: 'nsNsEstimateProductsMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['estimate/round-one'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS020_001',
    skillId: 'NS020',
    name: 'Estimation to check reasonableness — Practice',
    description: 'Estimation to check reasonableness question.',
    difficulty: 2,
    generatorKind: 'nsNsEstimateCheck',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['estimate/ignore-check'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS020_002',
    skillId: 'NS020',
    name: 'Estimation to check reasonableness — MCQ',
    description: 'Estimation to check reasonableness question.',
    difficulty: 2,
    generatorKind: 'nsNsEstimateCheckMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['estimate/ignore-check'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS021_001',
    skillId: 'NS021',
    name: 'Negative numbers on a number line — Practice',
    description: 'Negative numbers on a number line question.',
    difficulty: 2,
    generatorKind: 'nsNsNegIntro',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['neg/magnitude-order'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_NS021_002',
    skillId: 'NS021',
    name: 'Negative numbers on a number line — MCQ',
    description: 'Negative numbers on a number line question.',
    difficulty: 2,
    generatorKind: 'nsNsNegIntroMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['neg/magnitude-order'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  }
  {
    id: 'QF_NS022_001',
    skillId: 'NS022',
    name: 'Comparing and ordering integers — Practice',
    description: 'Comparing and ordering integers question.',
    difficulty: 2,
    generatorKind: 'nsNsNegCompareOrder',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['neg/order-like-positive'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS022_002',
    skillId: 'NS022',
    name: 'Comparing and ordering integers — MCQ',
    description: 'Comparing and ordering integers question.',
    difficulty: 2,
    generatorKind: 'nsNsNegCompareOrderMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['neg/order-like-positive'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS023_001',
    skillId: 'NS023',
    name: 'Negative numbers in context (temperature, levels) — Practice',
    description: 'Negative numbers in context (temperature, levels) question.',
    difficulty: 2,
    generatorKind: 'nsNsNegContext',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['neg/direction'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  }
  {
    id: 'QF_NS023_002',
    skillId: 'NS023',
    name: 'Negative numbers in context (temperature, levels) — MCQ',
    description: 'Negative numbers in context (temperature, levels) question.',
    difficulty: 2,
    generatorKind: 'nsNsNegContextMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 5,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['neg/direction'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
];

const familyById = new Map(families.map((family) => [family.id, family]));
const familiesBySkill = families.reduce((acc, family) => {
  if (!acc[family.skillId]) acc[family.skillId] = [];
  acc[family.skillId].push(family);
  return acc;
}, {});

export function getQuestionFamily(familyId) {
  return familyById.get(familyId) || null;
}

export function getQuestionFamiliesBySkill(skillId) {
  return familiesBySkill[skillId] ? [...familiesBySkill[skillId]] : [];
}

export function getAllQuestionFamilies() {
  return [...families];
}

export const numberSenseQuestionFamilies = families;
export default numberSenseQuestionFamilies;
