import { geometrySkillGraph } from './GeometrySkillGraph.js';

const SKILL_IDS = new Set(geometrySkillGraph.skillIds);

const families = [
  {
    id: 'QF_GE001_001',
    skillId: 'GE001',
    name: 'Identifying 2D shapes — Practice',
    description: 'Identifying 2D shapes question.',
    difficulty: 3,
    generatorKind: 'geoGeo2dShapes',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 3,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/orientation-changes-shape'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  },
  {
    id: 'QF_GE001_002',
    skillId: 'GE001',
    name: 'Identifying 2D shapes — MCQ',
    description: 'Identifying 2D shapes question.',
    difficulty: 3,
    generatorKind: 'geoGeo2dShapesMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 3,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/orientation-changes-shape'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  },
  {
    id: 'QF_GE002_001',
    skillId: 'GE002',
    name: 'Properties of 2D shapes (sides and vertices) — Practice',
    description: 'Properties of 2D shapes (sides and vertices) question.',
    difficulty: 3,
    generatorKind: 'geoGeo2dProperties',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/side-vertex-count'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  },
  {
    id: 'QF_GE002_002',
    skillId: 'GE002',
    name: 'Properties of 2D shapes (sides and vertices) — MCQ',
    description: 'Properties of 2D shapes (sides and vertices) question.',
    difficulty: 3,
    generatorKind: 'geoGeo2dPropertiesMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/side-vertex-count'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  },
  {
    id: 'QF_GE003_001',
    skillId: 'GE003',
    name: 'Parallel and perpendicular lines — Practice',
    description: 'Parallel and perpendicular lines question.',
    difficulty: 3,
    generatorKind: 'geoGeoLines',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/parallel-perp-confuse'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  },
  {
    id: 'QF_GE003_002',
    skillId: 'GE003',
    name: 'Parallel and perpendicular lines — MCQ',
    description: 'Parallel and perpendicular lines question.',
    difficulty: 3,
    generatorKind: 'geoGeoLinesMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/parallel-perp-confuse'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  },
  {
    id: 'QF_GE004_001',
    skillId: 'GE004',
    name: 'Angle types (right, acute, obtuse) — Practice',
    description: 'Angle types (right, acute, obtuse) question.',
    difficulty: 3,
    generatorKind: 'geoGeoAngleIntro',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 3,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/angle-by-arm-length'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  },
  {
    id: 'QF_GE004_002',
    skillId: 'GE004',
    name: 'Angle types (right, acute, obtuse) — MCQ',
    description: 'Angle types (right, acute, obtuse) question.',
    difficulty: 3,
    generatorKind: 'geoGeoAngleIntroMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 3,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/angle-by-arm-length'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  },
  {
    id: 'QF_GE005_001',
    skillId: 'GE005',
    name: 'Measuring and drawing angles — Practice',
    description: 'Measuring and drawing angles question.',
    difficulty: 3,
    generatorKind: 'geoGeoAngleMeasure',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/protractor-scale'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE005_002',
    skillId: 'GE005',
    name: 'Measuring and drawing angles — MCQ',
    description: 'Measuring and drawing angles question.',
    difficulty: 3,
    generatorKind: 'geoGeoAngleMeasureMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/protractor-scale'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE006_001',
    skillId: 'GE006',
    name: 'Angles on a line and at a point — Practice',
    description: 'Angles on a line and at a point question.',
    difficulty: 3,
    generatorKind: 'geoGeoAngleLinePoint',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/angle-relationship'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE006_002',
    skillId: 'GE006',
    name: 'Angles on a line and at a point — MCQ',
    description: 'Angles on a line and at a point question.',
    difficulty: 3,
    generatorKind: 'geoGeoAngleLinePointMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/angle-relationship'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE007_001',
    skillId: 'GE007',
    name: 'Types of triangles — Practice',
    description: 'Types of triangles question.',
    difficulty: 3,
    generatorKind: 'geoGeoTriangleTypes',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/triangle-by-look'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  },
  {
    id: 'QF_GE007_002',
    skillId: 'GE007',
    name: 'Types of triangles — MCQ',
    description: 'Types of triangles question.',
    difficulty: 3,
    generatorKind: 'geoGeoTriangleTypesMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/triangle-by-look'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  },
  {
    id: 'QF_GE008_001',
    skillId: 'GE008',
    name: 'Angle properties of triangles — Practice',
    description: 'Angle properties of triangles question.',
    difficulty: 3,
    generatorKind: 'geoGeoTriangleAngles',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/angle-sum-wrong'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE008_002',
    skillId: 'GE008',
    name: 'Angle properties of triangles — MCQ',
    description: 'Angle properties of triangles question.',
    difficulty: 3,
    generatorKind: 'geoGeoTriangleAnglesMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/angle-sum-wrong'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE009_001',
    skillId: 'GE009',
    name: 'Types of quadrilaterals and their properties — Practice',
    description: 'Types of quadrilaterals and their properties question.',
    difficulty: 3,
    generatorKind: 'geoGeoQuadTypes',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/square-not-rectangle'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  },
  {
    id: 'QF_GE009_002',
    skillId: 'GE009',
    name: 'Types of quadrilaterals and their properties — MCQ',
    description: 'Types of quadrilaterals and their properties question.',
    difficulty: 3,
    generatorKind: 'geoGeoQuadTypesMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/square-not-rectangle'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  },
  {
    id: 'QF_GE010_001',
    skillId: 'GE010',
    name: 'Angles in special quadrilaterals — Practice',
    description: 'Angles in special quadrilaterals question.',
    difficulty: 3,
    generatorKind: 'geoGeoAngleQuad',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/quad-angle-relationship'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE010_002',
    skillId: 'GE010',
    name: 'Angles in special quadrilaterals — MCQ',
    description: 'Angles in special quadrilaterals question.',
    difficulty: 3,
    generatorKind: 'geoGeoAngleQuadMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/quad-angle-relationship'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE011_001',
    skillId: 'GE011',
    name: 'Line symmetry — Practice',
    description: 'Line symmetry question.',
    difficulty: 3,
    generatorKind: 'geoGeoSymmetry',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/diagonal-symmetry-miss'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  },
  {
    id: 'QF_GE011_002',
    skillId: 'GE011',
    name: 'Line symmetry — MCQ',
    description: 'Line symmetry question.',
    difficulty: 3,
    generatorKind: 'geoGeoSymmetryMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/diagonal-symmetry-miss'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  },
  {
    id: 'QF_GE012_001',
    skillId: 'GE012',
    name: 'Completing symmetric figures — Practice',
    description: 'Completing symmetric figures question.',
    difficulty: 3,
    generatorKind: 'geoGeoSymmetryComplete',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/reflect-not-translate'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE012_002',
    skillId: 'GE012',
    name: 'Completing symmetric figures — MCQ',
    description: 'Completing symmetric figures question.',
    difficulty: 3,
    generatorKind: 'geoGeoSymmetryCompleteMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/reflect-not-translate'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE013_001',
    skillId: 'GE013',
    name: 'Identifying 3D solids (faces, edges, vertices) — Practice',
    description: 'Identifying 3D solids (faces, edges, vertices) question.',
    difficulty: 3,
    generatorKind: 'geoGeo3dShapes',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/faces-edges-confuse'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  },
  {
    id: 'QF_GE013_002',
    skillId: 'GE013',
    name: 'Identifying 3D solids (faces, edges, vertices) — MCQ',
    description: 'Identifying 3D solids (faces, edges, vertices) question.',
    difficulty: 3,
    generatorKind: 'geoGeo3dShapesMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/faces-edges-confuse'],
    assessmentRelevant: true,
    mentalMathEligible: true,
    workingRequired: false,
  },
  {
    id: 'QF_GE014_001',
    skillId: 'GE014',
    name: 'Nets and views of solids — Practice',
    description: 'Nets and views of solids question.',
    difficulty: 3,
    generatorKind: 'geoGeoNetsViews',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/net-folding'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE014_002',
    skillId: 'GE014',
    name: 'Nets and views of solids — MCQ',
    description: 'Nets and views of solids question.',
    difficulty: 3,
    generatorKind: 'geoGeoNetsViewsMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/net-folding'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE015_001',
    skillId: 'GE015',
    name: 'Position and compass directions — Practice',
    description: 'Position and compass directions question.',
    difficulty: 3,
    generatorKind: 'geoGeoPosition',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/compass-confuse'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE015_002',
    skillId: 'GE015',
    name: 'Position and compass directions — MCQ',
    description: 'Position and compass directions question.',
    difficulty: 3,
    generatorKind: 'geoGeoPositionMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/compass-confuse'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE016_001',
    skillId: 'GE016',
    name: 'Drawing and constructing figures — Practice',
    description: 'Drawing and constructing figures question.',
    difficulty: 3,
    generatorKind: 'geoGeoConstruct',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/construction-precision'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE016_002',
    skillId: 'GE016',
    name: 'Drawing and constructing figures — MCQ',
    description: 'Drawing and constructing figures question.',
    difficulty: 3,
    generatorKind: 'geoGeoConstructMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/construction-precision'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE017_001',
    skillId: 'GE017',
    name: 'Perimeter foundations (distance around) — Practice',
    description: 'Perimeter foundations (distance around) question.',
    difficulty: 3,
    generatorKind: 'geoGeoPerimeter',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 6,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/perimeter-vs-area'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE017_002',
    skillId: 'GE017',
    name: 'Perimeter foundations (distance around) — MCQ',
    description: 'Perimeter foundations (distance around) question.',
    difficulty: 3,
    generatorKind: 'geoGeoPerimeterMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 6,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/perimeter-vs-area'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE018_001',
    skillId: 'GE018',
    name: 'Area foundations (covering; rectangles) — Practice',
    description: 'Area foundations (covering; rectangles) question.',
    difficulty: 3,
    generatorKind: 'geoGeoAreaRect',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 6,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/area-add-sides'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE018_002',
    skillId: 'GE018',
    name: 'Area foundations (covering; rectangles) — MCQ',
    description: 'Area foundations (covering; rectangles) question.',
    difficulty: 3,
    generatorKind: 'geoGeoAreaRectMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 6,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/area-add-sides'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE019_001',
    skillId: 'GE019',
    name: 'Area of triangles — Practice',
    description: 'Area of triangles question.',
    difficulty: 3,
    generatorKind: 'geoGeoAreaTriangle',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 7,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/triangle-no-half', 'geo/wrong-height'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE019_002',
    skillId: 'GE019',
    name: 'Area of triangles — MCQ',
    description: 'Area of triangles question.',
    difficulty: 3,
    generatorKind: 'geoGeoAreaTriangleMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 7,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/triangle-no-half', 'geo/wrong-height'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE020_001',
    skillId: 'GE020',
    name: 'Circumference and area of a circle — Practice',
    description: 'Circumference and area of a circle question.',
    difficulty: 3,
    generatorKind: 'geoGeoCircle',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/radius-diameter-confuse', 'geo/circumference-area-formula'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE020_002',
    skillId: 'GE020',
    name: 'Circumference and area of a circle — MCQ',
    description: 'Circumference and area of a circle question.',
    difficulty: 3,
    generatorKind: 'geoGeoCircleMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/radius-diameter-confuse', 'geo/circumference-area-formula'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE021_001',
    skillId: 'GE021',
    name: 'Perimeter and area of circle parts — Practice',
    description: 'Perimeter and area of circle parts question.',
    difficulty: 3,
    generatorKind: 'geoGeoCircleParts',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/forgot-straight-edges'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE021_002',
    skillId: 'GE021',
    name: 'Perimeter and area of circle parts — MCQ',
    description: 'Perimeter and area of circle parts question.',
    difficulty: 3,
    generatorKind: 'geoGeoCirclePartsMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/forgot-straight-edges'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE022_001',
    skillId: 'GE022',
    name: 'Composite figures: area and perimeter — Practice',
    description: 'Composite figures: area and perimeter question.',
    difficulty: 3,
    generatorKind: 'geoGeoComposite',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/double-count-edges', 'geo/missing-region'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },
  {
    id: 'QF_GE022_002',
    skillId: 'GE022',
    name: 'Composite figures: area and perimeter — MCQ',
    description: 'Composite figures: area and perimeter question.',
    difficulty: 3,
    generatorKind: 'geoGeoCompositeMCQ',
    recommendedQuestionCount: 20,
    fluencyTargetSeconds: 10,
    masteryTargetAccuracy: 88,
    masteryQuestionCount: 12,
    misconceptionTags: ['geo/double-count-edges', 'geo/missing-region'],
    assessmentRelevant: true,
    mentalMathEligible: false,
    workingRequired: true,
  },

  // ── Word-problem families (_003): one per skill, real-world contexts ──────────
  { id: 'QF_GE001_003', skillId: 'GE001', name: '2D Shapes — Real-World Context', description: 'Identify how many sides a 2D shape found in a real object has.', difficulty: 3, generatorKind: 'geoGeo2dShapesWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 5, masteryTargetAccuracy: 88, masteryQuestionCount: 12, misconceptionTags: ['geo/orientation-changes-shape'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE002_003', skillId: 'GE002', name: '2D Shape Properties — Real-World Context', description: 'Count sides or vertices of a 2D shape in a real-world context.', difficulty: 3, generatorKind: 'geoGeo2dPropertiesWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 5, masteryTargetAccuracy: 88, masteryQuestionCount: 12, misconceptionTags: ['geo/side-vertex-count'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE003_003', skillId: 'GE003', name: 'Parallel and Perpendicular — Real-World Context', description: 'Identify parallel or perpendicular lines in everyday settings.', difficulty: 3, generatorKind: 'geoGeoLinesWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 6, masteryTargetAccuracy: 88, masteryQuestionCount: 12, misconceptionTags: ['geo/parallel-perp-confuse'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE004_003', skillId: 'GE004', name: 'Angle Types — Real-World Context', description: 'Classify the angle formed when a real object is opened or tilted.', difficulty: 3, generatorKind: 'geoGeoAngleIntroWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 5, masteryTargetAccuracy: 88, masteryQuestionCount: 12, misconceptionTags: ['geo/angle-by-arm-length'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE005_003', skillId: 'GE005', name: 'Measuring Angles — Real-World Context', description: 'Find the complementary angle in a ramp-and-wall scenario.', difficulty: 3, generatorKind: 'geoGeoAngleMeasureWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 8, masteryTargetAccuracy: 85, masteryQuestionCount: 12, misconceptionTags: ['geo/protractor-scale'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE006_003', skillId: 'GE006', name: 'Angles on a Line/Point — Real-World Context', description: 'Find a missing angle using the angles-on-a-line or at-a-point rule.', difficulty: 3, generatorKind: 'geoGeoAngleLinePointWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 8, masteryTargetAccuracy: 85, masteryQuestionCount: 12, misconceptionTags: ['geo/angle-relationship'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE007_003', skillId: 'GE007', name: 'Triangle Types — Real-World Context', description: 'Classify a triangle by its side lengths in a real-world setting.', difficulty: 3, generatorKind: 'geoGeoTriangleTypesWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 6, masteryTargetAccuracy: 88, masteryQuestionCount: 12, misconceptionTags: ['geo/triangle-by-look'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE008_003', skillId: 'GE008', name: 'Triangle Angles — Real-World Context', description: 'Find the third angle of a triangle described in a real-world context.', difficulty: 3, generatorKind: 'geoGeoTriangleAnglesWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 8, masteryTargetAccuracy: 85, masteryQuestionCount: 12, misconceptionTags: ['geo/angle-sum-wrong'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE009_003', skillId: 'GE009', name: 'Quadrilateral Types — Real-World Context', description: 'Identify a quadrilateral from its properties in a real-world object.', difficulty: 3, generatorKind: 'geoGeoQuadTypesWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 6, masteryTargetAccuracy: 88, masteryQuestionCount: 12, misconceptionTags: ['geo/square-not-rectangle'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE010_003', skillId: 'GE010', name: 'Quadrilateral Angles — Real-World Context', description: 'Find the co-interior angle in a real parallelogram-shaped object.', difficulty: 3, generatorKind: 'geoGeoAngleQuadWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 8, masteryTargetAccuracy: 85, masteryQuestionCount: 12, misconceptionTags: ['geo/quad-angle-relationship'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE011_003', skillId: 'GE011', name: 'Line Symmetry — Real-World Context', description: 'Count lines of symmetry for a real-world object.', difficulty: 3, generatorKind: 'geoGeoSymmetryWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 6, masteryTargetAccuracy: 88, masteryQuestionCount: 12, misconceptionTags: ['geo/diagonal-symmetry-miss'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE012_003', skillId: 'GE012', name: 'Symmetry Completion — Real-World Context', description: 'Find the mirror position of a point in a symmetric real-world pattern.', difficulty: 3, generatorKind: 'geoGeoSymmetryCompleteWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 8, masteryTargetAccuracy: 85, masteryQuestionCount: 12, misconceptionTags: ['geo/reflect-not-translate'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE013_003', skillId: 'GE013', name: '3D Solids — Real-World Context', description: 'Count faces, edges or vertices of a 3D solid found in everyday objects.', difficulty: 3, generatorKind: 'geoGeo3dShapesWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 6, masteryTargetAccuracy: 88, masteryQuestionCount: 12, misconceptionTags: ['geo/faces-edges-confuse'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE014_003', skillId: 'GE014', name: 'Nets and Views — Real-World Context', description: 'Determine how many faces a 3D object has from a description of its net.', difficulty: 3, generatorKind: 'geoGeoNetsViewsWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 8, masteryTargetAccuracy: 85, masteryQuestionCount: 12, misconceptionTags: ['geo/net-folding'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE015_003', skillId: 'GE015', name: 'Compass Directions — Real-World Context', description: 'Find the direction a moving object faces after a clockwise turn.', difficulty: 3, generatorKind: 'geoGeoPositionWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 8, masteryTargetAccuracy: 85, masteryQuestionCount: 12, misconceptionTags: ['geo/compass-confuse'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE016_003', skillId: 'GE016', name: 'Construction Facts — Real-World Context', description: 'Apply a key angle fact needed for accurate construction in a practical scenario.', difficulty: 3, generatorKind: 'geoGeoConstructWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 6, masteryTargetAccuracy: 85, masteryQuestionCount: 12, misconceptionTags: ['geo/construction-precision'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE017_003', skillId: 'GE017', name: 'Perimeter — Real-World Context', description: 'Find the perimeter of a square real-world object given its side length.', difficulty: 3, generatorKind: 'geoGeoPerimeterWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 6, masteryTargetAccuracy: 88, masteryQuestionCount: 12, misconceptionTags: ['geo/perimeter-vs-area'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE018_003', skillId: 'GE018', name: 'Rectangle Area — Real-World Context', description: 'Find the area of a real rectangular surface given its length and width.', difficulty: 3, generatorKind: 'geoGeoAreaRectWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 6, masteryTargetAccuracy: 88, masteryQuestionCount: 12, misconceptionTags: ['geo/area-add-sides'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE019_003', skillId: 'GE019', name: 'Triangle Area — Real-World Context', description: 'Find the area of a triangular real-world object given its base and height.', difficulty: 3, generatorKind: 'geoGeoAreaTriangleWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 8, masteryTargetAccuracy: 85, masteryQuestionCount: 12, misconceptionTags: ['geo/triangle-no-half'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE020_003', skillId: 'GE020', name: 'Circle — Real-World Context', description: 'Find the circumference of a real circular object given its radius.', difficulty: 3, generatorKind: 'geoGeoCircleWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 10, masteryTargetAccuracy: 85, masteryQuestionCount: 12, misconceptionTags: ['geo/circumference-area-formula'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE021_003', skillId: 'GE021', name: 'Circle Parts — Real-World Context', description: 'Find the perimeter of a semicircular real-world object.', difficulty: 3, generatorKind: 'geoGeoCirclePartsWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 10, masteryTargetAccuracy: 85, masteryQuestionCount: 12, misconceptionTags: ['geo/forgot-straight-edges'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
  { id: 'QF_GE022_003', skillId: 'GE022', name: 'Composite Figures — Real-World Context', description: 'Find the area of an L-shaped real-world space.', difficulty: 4, generatorKind: 'geoGeoCompositeWord', recommendedQuestionCount: 20, fluencyTargetSeconds: 12, masteryTargetAccuracy: 83, masteryQuestionCount: 12, misconceptionTags: ['geo/missing-region'], assessmentRelevant: true, mentalMathEligible: false, workingRequired: true },
];

const familyById = new Map(families.map((family) => [family.id, family]));
const familiesBySkill = families.reduce((acc, family) => {
  if (!acc[family.skillId]) acc[family.skillId] = [];
  acc[family.skillId].push(family);
  return acc;
}, {});

export function getQuestionFamily(familyId) {
  return familyById.get(familyId) || null;
}

export function getQuestionFamiliesBySkill(skillId) {
  return familiesBySkill[skillId] ? [...familiesBySkill[skillId]] : [];
}

export function getAllQuestionFamilies() {
  return [...families];
}

export const geometryQuestionFamilies = families;
export default geometryQuestionFamilies;
