// Reads the four Science content JSONs + the legacy question bank and emits
// an authoring-backlog report at docs/dev/science-content-coverage.md.
//
// Output: one row per (topic, level) pair with question count, mind-map and
// structured-lesson presence, and the share of questions that carry a diagram.
// Sorted worst-covered first so the gaps are obvious at a glance.
//
//   node scripts/scienceCoverageReport.mjs
//
// Re-run after editing any of the source JSONs (notes, lessons, diagrams,
// question-diagrams) or the legacy bank.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA = path.join(__dirname, '../data');
const OUT = path.join(__dirname, '../docs/dev/science-content-coverage.md');

const read = (rel) => JSON.parse(fs.readFileSync(path.join(DATA, rel), 'utf8'));

const LEGACY = read('p6Science.json');
const NOTES = read('scienceNotes.json');           // topic name → mermaid mind map
const LESSONS = read('scienceLessons.json');       // topic name → structured lesson
const DIAGRAMS = read('scienceDiagrams.json');     // key → svg
const Q_DIAGRAMS = read('scienceQuestionDiagrams.json'); // "topic::heading" → diagram key

const LEVEL_ORDER = { P3: 0, P4: 1, P5: 2, P6: 3 };

// Group legacy questions by (topic, level).
const groups = new Map();
for (const q of LEGACY) {
  const key = `${q.level}::${q.topic}`;
  if (!groups.has(key)) groups.set(key, { level: q.level, topic: q.topic, qs: [] });
  groups.get(key).qs.push(q);
}

const rows = [...groups.values()].map((g) => {
  const total = g.qs.length;
  // Question-diagram map is keyed by `${topic}::${heading}` (no level).
  // Count this group's questions that have an entry whose diagram key
  // resolves to an actual SVG in DIAGRAMS.
  let withDiagram = 0;
  for (const q of g.qs) {
    const dKey = Q_DIAGRAMS[`${q.topic}::${q.heading}`];
    if (dKey && DIAGRAMS[dKey]) withDiagram++;
  }
  return {
    level: g.level,
    topic: g.topic,
    questions: total,
    hasNotes: !!NOTES[g.topic],
    hasLesson: !!(LESSONS[g.topic] && Array.isArray(LESSONS[g.topic].sections) && LESSONS[g.topic].sections.length),
    diagramQs: withDiagram,
    diagramPct: total ? Math.round((withDiagram / total) * 100) : 0,
  };
});

// Coverage score: lower is worse. Weight: lesson (3) + notes (2) + 1 point per
// 25% of diagram coverage. So a topic with no notes, no lesson, no diagrams
// scores 0 — that's the top of the authoring backlog.
const score = (r) => (r.hasLesson ? 3 : 0) + (r.hasNotes ? 2 : 0) + Math.min(4, Math.floor(r.diagramPct / 25));
rows.sort((a, b) => {
  if (score(a) !== score(b)) return score(a) - score(b);
  return (LEVEL_ORDER[a.level] - LEVEL_ORDER[b.level]) || a.topic.localeCompare(b.topic);
});

// Summary headlines.
const totalTopics = rows.length;
const totalQuestions = rows.reduce((s, r) => s + r.questions, 0);
const totalWithDiagram = rows.reduce((s, r) => s + r.diagramQs, 0);
const withNotes = rows.filter((r) => r.hasNotes).length;
const withLesson = rows.filter((r) => r.hasLesson).length;
// Mind maps are keyed by topic name only (no level), so unique topic-names
// with notes is the meaningful denominator.
const uniqueTopicsWithNotes = new Set(rows.filter((r) => r.hasNotes).map((r) => r.topic)).size;

const tick = (b) => (b ? '✓' : '—');
const lines = [];
lines.push('# Science content coverage');
lines.push('');
lines.push('> Generated by `node scripts/scienceCoverageReport.mjs`. Re-run after editing any of the');
lines.push('> source JSONs (`data/scienceNotes.json`, `data/scienceLessons.json`,');
lines.push('> `data/scienceDiagrams.json`, `data/scienceQuestionDiagrams.json`) or the legacy bank.');
lines.push('');
lines.push('## Headline');
lines.push('');
lines.push(`- **${totalTopics}** topic+level pairs · **${totalQuestions}** questions`);
lines.push(`- **${withNotes}** of ${totalTopics} rows have a topic mind-map (covering **${uniqueTopicsWithNotes}** unique topic names — notes are level-agnostic and shared across P3–P6)`);
lines.push(`- **${withLesson}** of ${totalTopics} rows have a curated structured lesson`);
lines.push(`- **${totalWithDiagram}** of ${totalQuestions} questions carry an inline diagram (~${Math.round((totalWithDiagram / totalQuestions) * 100)}%)`);
lines.push('');
lines.push('## Per-topic backlog');
lines.push('');
lines.push('Sorted worst-covered first. Lesson + Notes columns: a topic without a structured lesson still gets an auto-built lesson from its questions, but the structured one is the curated experience.');
lines.push('');
lines.push('| # | Level | Topic | Questions | Mind map | Structured lesson | Diagrams |');
lines.push('|---|-------|-------|-----------|----------|-------------------|----------|');
rows.forEach((r, i) => {
  const diag = r.diagramQs > 0 ? `${r.diagramQs} / ${r.questions} (${r.diagramPct}%)` : `0 / ${r.questions}`;
  lines.push(`| ${i + 1} | ${r.level} | ${r.topic} | ${r.questions} | ${tick(r.hasNotes)} | ${tick(r.hasLesson)} | ${diag} |`);
});
lines.push('');

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, lines.join('\n'));

console.log(`✅ Wrote ${path.relative(path.join(__dirname, '..'), OUT)}`);
console.log(`   ${totalTopics} rows · ${totalQuestions} questions · ${withNotes} with notes · ${withLesson} with structured lesson · ${totalWithDiagram} questions with diagrams`);
