const FRACTION_UNIVERSAL_SKILL_ROWS = [
  {
    frameworkSkillId: 'F001',
    skillId: 'fractions.understanding_equal_parts',
    title: 'Understanding Equal Parts',
    description: 'Recognise a fraction as equal parts of a whole.',
    prerequisites: [],
    difficultyBand: 'beginner',
    questionTypes: ['visual_model', 'mcq', 'short_answer'],
    mistakeTypes: ['M003'],
    pathwayOrder: 1,
  },
  {
    frameworkSkillId: 'F002',
    skillId: 'fractions.numerator_denominator',
    title: 'Numerator and Denominator',
    description: 'Interpret numerator and denominator accurately in fraction notation.',
    prerequisites: ['F001'],
    difficultyBand: 'beginner',
    questionTypes: ['mcq', 'short_answer', 'matching'],
    mistakeTypes: ['M003'],
    pathwayOrder: 2,
  },
  {
    frameworkSkillId: 'F003',
    skillId: 'fractions.unit_fractions',
    title: 'Unit Fractions',
    description: 'Identify and represent unit fractions in visual and symbolic forms.',
    prerequisites: ['F001', 'F002'],
    difficultyBand: 'beginner',
    questionTypes: ['visual_model', 'short_answer'],
    mistakeTypes: ['M001', 'M003'],
    pathwayOrder: 3,
  },
  {
    frameworkSkillId: 'F004',
    skillId: 'fractions.fractions_of_shapes',
    title: 'Fractions of Shapes',
    description: 'Represent fractions as part of shaded and partitioned shapes.',
    prerequisites: ['F003'],
    difficultyBand: 'beginner',
    questionTypes: ['visual_model', 'mcq', 'short_answer'],
    mistakeTypes: ['M003'],
    pathwayOrder: 4,
  },
  {
    frameworkSkillId: 'F005',
    skillId: 'fractions.number_line',
    title: 'Fractions on a Number Line',
    description: 'Place and read fractions on equal-part number lines.',
    prerequisites: ['F004'],
    difficultyBand: 'basic',
    questionTypes: ['number_line', 'short_answer', 'mcq'],
    mistakeTypes: ['M003', 'M001'],
    pathwayOrder: 5,
  },
  {
    frameworkSkillId: 'F006',
    skillId: 'fractions.compare_simple_visual',
    title: 'Comparing Simple Fractions Visually',
    description: 'Compare simple fractions using visual and model-based reasoning.',
    prerequisites: ['F003', 'F005'],
    difficultyBand: 'basic',
    questionTypes: ['visual_model', 'comparison', 'mcq'],
    mistakeTypes: ['M001', 'M002'],
    pathwayOrder: 6,
  },
  {
    frameworkSkillId: 'F007',
    skillId: 'fractions.equivalent_models',
    title: 'Equivalent Fractions Using Models',
    description: 'Recognise equivalent fractions from model representations.',
    prerequisites: ['F006'],
    difficultyBand: 'basic',
    questionTypes: ['visual_model', 'matching', 'short_answer'],
    mistakeTypes: ['M004'],
    pathwayOrder: 7,
  },
  {
    frameworkSkillId: 'F008',
    skillId: 'fractions.equivalent_multiplication',
    title: 'Equivalent Fractions Using Multiplication',
    description: 'Generate equivalent fractions by multiplying numerator and denominator.',
    prerequisites: ['F007'],
    difficultyBand: 'basic',
    questionTypes: ['short_answer', 'fill_blank', 'equation'],
    mistakeTypes: ['M004', 'M005'],
    pathwayOrder: 8,
  },
  {
    frameworkSkillId: 'F009',
    skillId: 'fractions.equivalent_division',
    title: 'Equivalent Fractions Using Division',
    description: 'Generate equivalent fractions by dividing by a common factor.',
    prerequisites: ['F008'],
    difficultyBand: 'basic',
    questionTypes: ['short_answer', 'fill_blank', 'equation'],
    mistakeTypes: ['M004', 'M005'],
    pathwayOrder: 9,
  },
  {
    frameworkSkillId: 'F010',
    skillId: 'fractions.simplify_fractions',
    title: 'Simplifying Fractions',
    description: 'Reduce fractions to simplest form correctly.',
    prerequisites: ['F009'],
    difficultyBand: 'standard',
    questionTypes: ['short_answer', 'mcq', 'equation'],
    mistakeTypes: ['M005'],
    pathwayOrder: 10,
  },
  {
    frameworkSkillId: 'F011',
    skillId: 'fractions.compare_same_denominator',
    title: 'Comparing Fractions with Same Denominator',
    description: 'Compare fractions that share a denominator using numerator size.',
    prerequisites: ['F004'],
    difficultyBand: 'basic',
    questionTypes: ['comparison', 'mcq', 'short_answer'],
    mistakeTypes: ['M003'],
    pathwayOrder: 11,
  },
  {
    frameworkSkillId: 'F012',
    skillId: 'fractions.compare_same_numerator',
    title: 'Comparing Fractions with Same Numerator',
    description: 'Compare fractions with same numerator using denominator reasoning.',
    prerequisites: ['F006'],
    difficultyBand: 'basic',
    questionTypes: ['comparison', 'mcq', 'short_answer'],
    mistakeTypes: ['M002'],
    pathwayOrder: 12,
  },
  {
    frameworkSkillId: 'F013',
    skillId: 'fractions.compare_unlike',
    title: 'Comparing Unlike Fractions',
    description: 'Compare unlike fractions using equivalent forms or benchmarks.',
    prerequisites: ['F010', 'F011', 'F012'],
    difficultyBand: 'standard',
    questionTypes: ['comparison', 'short_answer', 'number_line'],
    mistakeTypes: ['M004', 'M007'],
    pathwayOrder: 13,
  },
  {
    frameworkSkillId: 'F014',
    skillId: 'fractions.order_fractions',
    title: 'Ordering Fractions',
    description: 'Arrange fractions in ascending or descending order.',
    prerequisites: ['F013'],
    difficultyBand: 'standard',
    questionTypes: ['ordering', 'short_answer', 'number_line'],
    mistakeTypes: ['M004', 'M002'],
    pathwayOrder: 14,
  },
  {
    frameworkSkillId: 'F015',
    skillId: 'fractions.add_like_fractions',
    title: 'Adding Like Fractions',
    description: 'Add fractions with the same denominator accurately.',
    prerequisites: ['F011'],
    difficultyBand: 'basic',
    questionTypes: ['symbolic', 'visual_model', 'short_answer'],
    mistakeTypes: ['M007'],
    pathwayOrder: 15,
  },
  {
    frameworkSkillId: 'F016',
    skillId: 'fractions.subtract_like_fractions',
    title: 'Subtracting Like Fractions',
    description: 'Subtract fractions with the same denominator accurately.',
    prerequisites: ['F015'],
    difficultyBand: 'basic',
    questionTypes: ['symbolic', 'visual_model', 'short_answer'],
    mistakeTypes: ['M007'],
    pathwayOrder: 16,
  },
  {
    frameworkSkillId: 'F017',
    skillId: 'fractions.add_unlike_fractions',
    title: 'Adding Unlike Fractions',
    description: 'Add unlike fractions by finding a common denominator.',
    prerequisites: ['F010', 'F015'],
    difficultyBand: 'standard',
    questionTypes: ['symbolic', 'word_problem', 'short_answer'],
    mistakeTypes: ['M004', 'M007'],
    pathwayOrder: 17,
  },
  {
    frameworkSkillId: 'F018',
    skillId: 'fractions.subtract_unlike_fractions',
    title: 'Subtracting Unlike Fractions',
    description: 'Subtract unlike fractions with common-denominator strategy.',
    prerequisites: ['F010', 'F016'],
    difficultyBand: 'standard',
    questionTypes: ['symbolic', 'word_problem', 'short_answer'],
    mistakeTypes: ['M004', 'M007'],
    pathwayOrder: 18,
  },
  {
    frameworkSkillId: 'F019',
    skillId: 'fractions.improper_fractions',
    title: 'Improper Fractions',
    description: 'Interpret and represent improper fractions greater than one.',
    prerequisites: ['F004', 'F010'],
    difficultyBand: 'standard',
    questionTypes: ['visual_model', 'short_answer', 'mcq'],
    mistakeTypes: ['M006'],
    pathwayOrder: 19,
  },
  {
    frameworkSkillId: 'F020',
    skillId: 'fractions.mixed_numbers',
    title: 'Mixed Numbers',
    description: 'Represent mixed numbers and interpret whole-plus-fraction values.',
    prerequisites: ['F019'],
    difficultyBand: 'standard',
    questionTypes: ['symbolic', 'visual_model', 'short_answer'],
    mistakeTypes: ['M006'],
    pathwayOrder: 20,
  },
  {
    frameworkSkillId: 'F021',
    skillId: 'fractions.convert_mixed_improper',
    title: 'Converting Between Mixed Numbers and Improper Fractions',
    description: 'Convert mixed numbers and improper fractions in both directions.',
    prerequisites: ['F019', 'F020'],
    difficultyBand: 'standard',
    questionTypes: ['symbolic', 'short_answer', 'equation'],
    mistakeTypes: ['M006', 'M005'],
    pathwayOrder: 21,
  },
  {
    frameworkSkillId: 'F022',
    skillId: 'fractions.add_subtract_mixed_numbers',
    title: 'Adding and Subtracting Mixed Numbers',
    description: 'Perform mixed-number operations with proper conversion and simplification.',
    prerequisites: ['F017', 'F018', 'F021'],
    difficultyBand: 'advanced',
    questionTypes: ['symbolic', 'word_problem', 'short_answer'],
    mistakeTypes: ['M006', 'M007'],
    pathwayOrder: 22,
  },
  {
    frameworkSkillId: 'F023',
    skillId: 'fractions.fraction_of_quantity_set',
    title: 'Fraction of a Quantity / Set',
    description: 'Find fractional parts of a set or quantity in numeric and context forms.',
    prerequisites: ['F010', 'F015'],
    difficultyBand: 'standard',
    questionTypes: ['symbolic', 'word_problem', 'table'],
    mistakeTypes: ['M008'],
    pathwayOrder: 23,
  },
  {
    frameworkSkillId: 'F024',
    skillId: 'fractions.remainder_concept',
    title: 'Remainder Concept',
    description: 'Apply remainder reasoning in fraction-based quantity problems.',
    prerequisites: ['F023'],
    difficultyBand: 'advanced',
    questionTypes: ['word_problem', 'multi_step', 'short_answer'],
    mistakeTypes: ['M008', 'M010'],
    pathwayOrder: 24,
  },
  {
    frameworkSkillId: 'F025',
    skillId: 'fractions.word_problems_basic',
    title: 'Basic Fraction Word Problems',
    description: 'Solve one-step and straightforward two-step fraction word problems.',
    prerequisites: ['F017', 'F018', 'F023'],
    difficultyBand: 'advanced',
    questionTypes: ['word_problem', 'short_answer', 'diagram'],
    mistakeTypes: ['M008', 'M010'],
    pathwayOrder: 25,
  },
  {
    frameworkSkillId: 'F026',
    skillId: 'fractions.word_problems_multi_step',
    title: 'Multi-Step Fraction Word Problems',
    description: 'Solve complex multi-step fraction word problems with clear reasoning.',
    prerequisites: ['F022', 'F024', 'F025'],
    difficultyBand: 'challenge',
    questionTypes: ['multi_step', 'word_problem', 'open_response'],
    mistakeTypes: ['M008', 'M010'],
    pathwayOrder: 26,
  },
];

const universalByFrameworkId = new Map(
  FRACTION_UNIVERSAL_SKILL_ROWS.map((row) => [row.frameworkSkillId, row])
);

const universalBySkillId = new Map(
  FRACTION_UNIVERSAL_SKILL_ROWS.map((row) => [row.skillId, row])
);

export const fractionUniversalSkills = FRACTION_UNIVERSAL_SKILL_ROWS.map((row) => ({
  ...row,
  domain: 'fractions',
}));

export function getUniversalSkillByFrameworkId(frameworkSkillId) {
  return universalByFrameworkId.get(String(frameworkSkillId || '').toUpperCase()) || null;
}

export function getUniversalSkillBySkillId(skillId) {
  return universalBySkillId.get(String(skillId || '')) || null;
}

export default fractionUniversalSkills;
