export const FRACTIONS_PILOT_SCOPE_LABEL = 'Fractions intervention pilot';

export const FRACTION_CANONICAL_SKILL_ROWS = [
  {
    frameworkSkillId: 'F001',
    slug: 'fractions.recognise_fractions',
    displayName: 'Recognise Fractions',
    studentName: 'Recognising fractions',
    parentName: 'Recognising fractions as equal parts',
    topic: 'Understanding Fractions',
    strand: 'Foundations',
    introducedLevel: 'P2',
    masteryLevel: 'P2',
    levelBand: ['P2'],
    prerequisites: [],
    questionFamilies: ['QF_F001_001', 'QF_F001_002', 'QF_F001_003', 'QF_F001_004', 'QF_F001_005', 'QF_F001_006'],
    syllabusOutcome: 'Identify fractions as equal parts of a whole using simple models.',
    syllabusRef: 'P2 Fractions foundations',
    description: 'Identify fractions as equal parts of a whole using simple models.',
  },
  {
    frameworkSkillId: 'F002',
    slug: 'fractions.numerator_denominator',
    displayName: 'Numerator and Denominator',
    studentName: 'Understanding top and bottom numbers',
    parentName: 'Understanding numerator and denominator',
    topic: 'Understanding Fractions',
    strand: 'Foundations',
    introducedLevel: 'P2',
    masteryLevel: 'P2',
    levelBand: ['P2'],
    prerequisites: ['F001'],
    questionFamilies: ['QF_F002_001', 'QF_F002_002', 'QF_F002_003', 'QF_F002_004', 'QF_F002_005'],
    syllabusOutcome: 'Explain the meaning of numerator and denominator in a fraction.',
    syllabusRef: 'P2 Fractions notation',
    description: 'Explain the meaning of numerator and denominator in a fraction.',
  },
  {
    frameworkSkillId: 'F003',
    slug: 'fractions.fraction_of_whole',
    displayName: 'Fraction of a Whole',
    studentName: 'Finding fractions of a whole',
    parentName: 'Representing a fraction of one whole',
    topic: 'Understanding Fractions',
    strand: 'Foundations',
    introducedLevel: 'P2',
    masteryLevel: 'P3',
    levelBand: ['P2', 'P3'],
    prerequisites: ['F001', 'F002'],
    questionFamilies: ['QF_F003_001', 'QF_F003_002', 'QF_F003_003'],
    syllabusOutcome: 'Represent and interpret a fraction as part of one whole.',
    syllabusRef: 'P2-P3 Part-whole fractions',
    description: 'Represent and interpret a fraction as part of one whole.',
  },
  {
    frameworkSkillId: 'F004',
    slug: 'fractions.unit_fractions',
    displayName: 'Unit Fractions',
    studentName: 'Understanding unit fractions',
    parentName: 'Understanding unit fractions',
    topic: 'Understanding Fractions',
    strand: 'Foundations',
    introducedLevel: 'P2',
    masteryLevel: 'P3',
    levelBand: ['P2', 'P3'],
    prerequisites: ['F003'],
    questionFamilies: ['QF_F004_001', 'QF_F004_002', 'QF_F004_003'],
    syllabusOutcome: 'Identify and compare fractions with numerator 1 as unit fractions.',
    syllabusRef: 'P2-P3 Unit fractions',
    description: 'Identify and compare fractions with numerator 1 as unit fractions.',
  },
  {
    frameworkSkillId: 'F005',
    slug: 'fractions.number_line',
    displayName: 'Fractions on Number Line',
    studentName: 'Fractions on a number line',
    parentName: 'Placing fractions on a number line',
    topic: 'Representing Fractions',
    strand: 'Representation',
    introducedLevel: 'P3',
    masteryLevel: 'P4',
    levelBand: ['P3', 'P4'],
    prerequisites: ['F003'],
    questionFamilies: ['QF_F005_001', 'QF_F005_002', 'QF_F005_003', 'QF_F005_004', 'QF_F005_005'],
    syllabusOutcome: 'Locate and read fractions on number lines with equal partitions.',
    syllabusRef: 'P3-P4 Number-line fractions',
    description: 'Locate and read fractions on number lines with equal partitions.',
  },
  {
    frameworkSkillId: 'F006',
    slug: 'fractions.compare_unit_fractions',
    displayName: 'Compare Unit Fractions',
    studentName: 'Comparing unit fractions',
    parentName: 'Comparing unit fractions',
    topic: 'Comparing Fractions',
    strand: 'Comparison',
    introducedLevel: 'P3',
    masteryLevel: 'P4',
    levelBand: ['P3', 'P4'],
    prerequisites: ['F004', 'F005'],
    questionFamilies: ['QF_F006_001', 'QF_F006_002', 'QF_F006_003'],
    syllabusOutcome: 'Compare unit fractions by reasoning about denominator size.',
    syllabusRef: 'P3-P4 Unit fraction comparison',
    description: 'Compare unit fractions by reasoning about denominator size.',
  },
  {
    frameworkSkillId: 'F007',
    slug: 'fractions.compare_same_denominator',
    displayName: 'Compare Same Denominator',
    studentName: 'Comparing fractions with the same denominator',
    parentName: 'Comparing fractions with the same denominator',
    topic: 'Comparing Fractions',
    strand: 'Comparison',
    introducedLevel: 'P3',
    masteryLevel: 'P4',
    levelBand: ['P3', 'P4'],
    prerequisites: ['F003'],
    questionFamilies: ['QF_F007_001', 'QF_F007_002', 'QF_F007_003'],
    syllabusOutcome: 'Compare fractions that share the same denominator.',
    syllabusRef: 'P3-P4 Same-denominator comparison',
    description: 'Compare fractions that share the same denominator.',
  },
  {
    frameworkSkillId: 'F008',
    slug: 'fractions.compare_same_numerator',
    displayName: 'Compare Same Numerator',
    studentName: 'Comparing fractions with the same numerator',
    parentName: 'Comparing fractions with the same numerator',
    topic: 'Comparing Fractions',
    strand: 'Comparison',
    introducedLevel: 'P4',
    masteryLevel: 'P4',
    levelBand: ['P4'],
    prerequisites: ['F004', 'F006'],
    questionFamilies: ['QF_F008_001', 'QF_F008_002', 'QF_F008_003'],
    syllabusOutcome: 'Compare fractions with the same numerator by denominator relationship.',
    syllabusRef: 'P4 Same-numerator comparison',
    description: 'Compare fractions with same numerator by denominator relationship.',
  },
  {
    frameworkSkillId: 'F009',
    slug: 'fractions.order_fractions',
    displayName: 'Order Fractions',
    studentName: 'Ordering fractions',
    parentName: 'Ordering fractions',
    topic: 'Comparing Fractions',
    strand: 'Comparison',
    introducedLevel: 'P4',
    masteryLevel: 'P5',
    levelBand: ['P4', 'P5'],
    prerequisites: ['F006', 'F007', 'F008'],
    questionFamilies: ['QF_F009_001', 'QF_F009_002', 'QF_F009_003', 'QF_F009_004'],
    syllabusOutcome: 'Arrange fractions in ascending or descending order.',
    syllabusRef: 'P4-P5 Ordering fractions',
    description: 'Arrange fractions in ascending or descending order.',
  },
  {
    frameworkSkillId: 'F010',
    slug: 'fractions.equivalent_fractions',
    displayName: 'Equivalent Fractions',
    studentName: 'Recognising equivalent fractions',
    parentName: 'Recognising equivalent fractions',
    topic: 'Equivalent Fractions',
    strand: 'Equivalence',
    introducedLevel: 'P3',
    masteryLevel: 'P4',
    levelBand: ['P3', 'P4'],
    prerequisites: ['F003', 'F007'],
    questionFamilies: ['QF_F010_001', 'QF_F010_002', 'QF_F010_003', 'QF_F010_004'],
    syllabusOutcome: 'Recognise fractions that represent the same value.',
    syllabusRef: 'P3-P4 Equivalent fractions',
    description: 'Recognise fractions that represent the same value.',
  },
  {
    frameworkSkillId: 'F011',
    slug: 'fractions.generate_equivalent_fractions',
    displayName: 'Generate Equivalent Fractions',
    studentName: 'Making equivalent fractions',
    parentName: 'Generating equivalent fractions',
    topic: 'Equivalent Fractions',
    strand: 'Equivalence',
    introducedLevel: 'P4',
    masteryLevel: 'P5',
    levelBand: ['P4', 'P5'],
    prerequisites: ['F010'],
    questionFamilies: ['QF_F011_001', 'QF_F011_002', 'QF_F011_003', 'QF_F011_004', 'QF_F011_005', 'QF_F011_006'],
    syllabusOutcome: 'Create equivalent fractions through scaling by common factors.',
    syllabusRef: 'P4-P5 Equivalent fraction generation',
    description: 'Create equivalent fractions through scaling by common factors.',
  },
  {
    frameworkSkillId: 'F012',
    slug: 'fractions.simplify_fractions',
    displayName: 'Simplify Fractions',
    studentName: 'Simplifying fractions',
    parentName: 'Simplifying fractions',
    topic: 'Equivalent Fractions',
    strand: 'Equivalence',
    introducedLevel: 'P4',
    masteryLevel: 'P5',
    levelBand: ['P4', 'P5'],
    prerequisites: ['F011'],
    questionFamilies: ['QF_F012_001', 'QF_F012_002', 'QF_F012_003', 'QF_F012_004', 'QF_F012_005', 'QF_F012_006'],
    syllabusOutcome: 'Reduce fractions to simplest form using highest common factors.',
    syllabusRef: 'P4-P5 Simplest form',
    description: 'Reduce fractions to simplest form using highest common factors.',
  },
  {
    frameworkSkillId: 'F013',
    slug: 'fractions.improper_fractions',
    displayName: 'Improper Fractions',
    studentName: 'Understanding improper fractions',
    parentName: 'Understanding improper fractions',
    topic: 'Improper Fractions and Mixed Numbers',
    strand: 'Conversion',
    introducedLevel: 'P4',
    masteryLevel: 'P4',
    levelBand: ['P4'],
    prerequisites: ['F003', 'F010'],
    questionFamilies: ['QF_F013_001', 'QF_F013_002', 'QF_F013_003', 'QF_F013_004', 'QF_F013_005'],
    syllabusOutcome: 'Interpret and represent improper fractions greater than or equal to 1.',
    syllabusRef: 'P4 Improper fractions',
    description: 'Interpret and represent improper fractions greater than or equal to 1.',
  },
  {
    frameworkSkillId: 'F014',
    slug: 'fractions.mixed_numbers',
    displayName: 'Mixed Numbers',
    studentName: 'Understanding mixed numbers',
    parentName: 'Understanding mixed numbers',
    topic: 'Improper Fractions and Mixed Numbers',
    strand: 'Conversion',
    introducedLevel: 'P4',
    masteryLevel: 'P5',
    levelBand: ['P4', 'P5'],
    prerequisites: ['F013'],
    questionFamilies: ['QF_F014_001', 'QF_F014_002', 'QF_F014_003', 'QF_F014_004', 'QF_F014_005'],
    syllabusOutcome: 'Represent mixed numbers and connect them to improper fractions.',
    syllabusRef: 'P4-P5 Mixed numbers',
    description: 'Represent mixed numbers and connect them to improper fractions.',
  },
  {
    frameworkSkillId: 'F015',
    slug: 'fractions.convert_mixed_improper',
    displayName: 'Convert Mixed to/from Improper',
    studentName: 'Changing mixed numbers and improper fractions',
    parentName: 'Converting between mixed numbers and improper fractions',
    topic: 'Improper Fractions and Mixed Numbers',
    strand: 'Conversion',
    introducedLevel: 'P4',
    masteryLevel: 'P5',
    levelBand: ['P4', 'P5'],
    prerequisites: ['F013', 'F014'],
    questionFamilies: ['QF_F015_001', 'QF_F015_002', 'QF_F015_003', 'QF_F015_004', 'QF_F015_005'],
    syllabusOutcome: 'Convert between mixed numbers and improper fractions accurately.',
    syllabusRef: 'P4-P5 Mixed/improper conversion',
    description: 'Convert between mixed numbers and improper fractions accurately.',
  },
  {
    frameworkSkillId: 'F016',
    slug: 'fractions.add_same_denominator',
    displayName: 'Add Same Denominator',
    studentName: 'Adding fractions with the same denominator',
    parentName: 'Adding fractions with the same denominator',
    topic: 'Fraction Operations',
    strand: 'Operations',
    introducedLevel: 'P3',
    masteryLevel: 'P4',
    levelBand: ['P3', 'P4'],
    prerequisites: ['F007', 'F010'],
    questionFamilies: ['QF_F016_001', 'QF_F016_002', 'QF_F016_003', 'QF_F016_004', 'QF_F016_005'],
    syllabusOutcome: 'Add fractions that share a common denominator.',
    syllabusRef: 'P3-P4 Like-denominator addition',
    description: 'Add fractions that share a common denominator.',
  },
  {
    frameworkSkillId: 'F017',
    slug: 'fractions.subtract_same_denominator',
    displayName: 'Subtract Same Denominator',
    studentName: 'Subtracting fractions with the same denominator',
    parentName: 'Subtracting fractions with the same denominator',
    topic: 'Fraction Operations',
    strand: 'Operations',
    introducedLevel: 'P3',
    masteryLevel: 'P4',
    levelBand: ['P3', 'P4'],
    prerequisites: ['F007', 'F016'],
    questionFamilies: ['QF_F017_001', 'QF_F017_002', 'QF_F017_003', 'QF_F017_004'],
    syllabusOutcome: 'Subtract fractions with the same denominator while preserving denominator.',
    syllabusRef: 'P3-P4 Like-denominator subtraction',
    description: 'Subtract fractions with same denominator while preserving denominator.',
  },
  {
    frameworkSkillId: 'F018',
    slug: 'fractions.add_different_denominators',
    displayName: 'Add Different Denominators',
    studentName: 'Adding fractions with different denominators',
    parentName: 'Adding fractions with different denominators',
    topic: 'Fraction Operations',
    strand: 'Operations',
    introducedLevel: 'P5',
    masteryLevel: 'P5',
    levelBand: ['P5'],
    prerequisites: ['F011', 'F012', 'F016'],
    questionFamilies: ['QF_F018_001', 'QF_F018_002', 'QF_F018_003', 'QF_F018_004', 'QF_F018_005', 'QF_F018_006'],
    syllabusOutcome: 'Add unlike fractions by finding common denominators first.',
    syllabusRef: 'P5 Unlike-denominator addition',
    description: 'Add unlike fractions by finding common denominators first.',
  },
  {
    frameworkSkillId: 'F019',
    slug: 'fractions.subtract_different_denominators',
    displayName: 'Subtract Different Denominators',
    studentName: 'Subtracting fractions with different denominators',
    parentName: 'Subtracting fractions with different denominators',
    topic: 'Fraction Operations',
    strand: 'Operations',
    introducedLevel: 'P5',
    masteryLevel: 'P5',
    levelBand: ['P5'],
    prerequisites: ['F011', 'F012', 'F017'],
    questionFamilies: ['QF_F019_001', 'QF_F019_002', 'QF_F019_003', 'QF_F019_004', 'QF_F019_005'],
    syllabusOutcome: 'Subtract unlike fractions by converting to common denominators.',
    syllabusRef: 'P5 Unlike-denominator subtraction',
    description: 'Subtract unlike fractions by converting to common denominators.',
  },
  {
    frameworkSkillId: 'F020',
    slug: 'fractions.fraction_of_quantity',
    displayName: 'Fraction of Quantity',
    studentName: 'Finding a fraction of a quantity',
    parentName: 'Finding a fraction of a quantity',
    topic: 'Fraction Applications',
    strand: 'Applications',
    introducedLevel: 'P4',
    masteryLevel: 'P5',
    levelBand: ['P4', 'P5'],
    prerequisites: ['F003', 'F010', 'F016'],
    questionFamilies: ['QF_F020_001', 'QF_F020_002', 'QF_F020_003', 'QF_F020_004', 'QF_F020_005', 'QF_F020_006', 'QF_F020_007'],
    syllabusOutcome: 'Find a fraction of a discrete or continuous quantity.',
    syllabusRef: 'P4-P5 Fraction of quantity',
    description: 'Find a fraction of a discrete or continuous quantity.',
  },
  {
    frameworkSkillId: 'F021',
    slug: 'fractions.multiply_fractions',
    displayName: 'Multiply Fractions',
    studentName: 'Multiplying fractions',
    parentName: 'Multiplying fractions',
    topic: 'Fraction Operations',
    strand: 'Operations',
    introducedLevel: 'P6',
    masteryLevel: 'P6',
    levelBand: ['P6'],
    prerequisites: ['F012', 'F015'],
    questionFamilies: ['QF_F021_001', 'QF_F021_002', 'QF_F021_003', 'QF_F021_004', 'QF_F021_005'],
    syllabusOutcome: 'Multiply fractions and simplify results where appropriate.',
    syllabusRef: 'P6 Fraction multiplication',
    description: 'Multiply fractions and simplify results where appropriate.',
  },
  {
    frameworkSkillId: 'F022',
    slug: 'fractions.divide_fractions',
    displayName: 'Divide Fractions',
    studentName: 'Dividing fractions',
    parentName: 'Dividing fractions',
    topic: 'Fraction Operations',
    strand: 'Operations',
    introducedLevel: 'P6',
    masteryLevel: 'P6',
    levelBand: ['P6'],
    prerequisites: ['F021'],
    questionFamilies: ['QF_F022_001', 'QF_F022_002', 'QF_F022_003', 'QF_F022_004', 'QF_F022_005'],
    syllabusOutcome: 'Divide fractions using reciprocal relationships.',
    syllabusRef: 'P6 Fraction division',
    description: 'Divide fractions using reciprocal relationships.',
  },
  {
    frameworkSkillId: 'F023',
    slug: 'fractions.word_problems',
    displayName: 'Fraction Word Problems',
    studentName: 'Solving fraction word problems',
    parentName: 'Solving fraction word problems',
    topic: 'Fraction Applications',
    strand: 'Applications',
    introducedLevel: 'P5',
    masteryLevel: 'P6',
    levelBand: ['P5', 'P6'],
    prerequisites: ['F018', 'F019', 'F020'],
    questionFamilies: ['QF_F023_001', 'QF_F023_002', 'QF_F023_003', 'QF_F023_004', 'QF_F023_005', 'QF_F023_006', 'QF_F023_007'],
    syllabusOutcome: 'Apply fraction operations in one-step contextual problems.',
    syllabusRef: 'P5-P6 Fraction word problems',
    description: 'Apply fraction operations in one-step contextual problems.',
  },
  {
    frameworkSkillId: 'F024',
    slug: 'fractions.multi_step_problems',
    displayName: 'Multi-Step Fraction Problems',
    studentName: 'Solving multi-step fraction problems',
    parentName: 'Solving multi-step fraction problems',
    topic: 'Fraction Applications',
    strand: 'Applications',
    introducedLevel: 'P6',
    masteryLevel: 'P6',
    levelBand: ['P6'],
    prerequisites: ['F023', 'F021'],
    questionFamilies: ['QF_F024_001', 'QF_F024_002', 'QF_F024_003', 'QF_F024_004'],
    syllabusOutcome: 'Solve multi-step fraction tasks involving conversion and operations.',
    syllabusRef: 'P6 Multi-step fraction problems',
    description: 'Solve multi-step fraction tasks involving conversion and operations.',
  },
  {
    frameworkSkillId: 'F025',
    slug: 'fractions.exam_style_applications',
    aliases: ['fractions.word_problems_basic'],
    displayName: 'Exam-Style Fraction Applications',
    studentName: 'Solving exam-style fraction questions',
    parentName: 'Solving exam-style fraction applications',
    topic: 'Fraction Applications',
    strand: 'Assessment Prep',
    introducedLevel: 'P6',
    masteryLevel: 'P6',
    levelBand: ['P6'],
    prerequisites: ['F024', 'F022'],
    questionFamilies: ['QF_F025_001', 'QF_F025_002', 'QF_F025_003', 'QF_F025_004', 'QF_F025_005'],
    syllabusOutcome: 'Handle school-style fraction items in mixed formats and contexts.',
    syllabusRef: 'P6 Exam-style fraction applications',
    description: 'Handle school-style fraction items in mixed formats and contexts.',
  },
  {
    frameworkSkillId: 'F026',
    slug: 'fractions.mastery_challenge',
    aliases: ['fractions.word_problems_multi_step'],
    displayName: 'Fractions Mastery Challenge',
    studentName: 'Putting fraction skills together',
    parentName: 'Consolidating fraction skills',
    topic: 'Fraction Applications',
    strand: 'Mastery',
    introducedLevel: 'P6',
    masteryLevel: 'P6',
    levelBand: ['P6'],
    prerequisites: ['F025'],
    questionFamilies: ['QF_F026_001', 'QF_F026_002', 'QF_F026_003', 'QF_F026_004', 'QF_F026_005'],
    syllabusOutcome: 'Demonstrate consolidated mastery across all fraction strands.',
    syllabusRef: 'P6 Fractions mastery challenge',
    description: 'Demonstrate consolidated mastery across all fraction strands.',
  },
];

const byFrameworkId = new Map(FRACTION_CANONICAL_SKILL_ROWS.map((row) => [row.frameworkSkillId, row]));
const bySlug = new Map(FRACTION_CANONICAL_SKILL_ROWS.map((row) => [row.slug, row]));

export function getCanonicalFractionSkill(frameworkSkillId = '') {
  return byFrameworkId.get(String(frameworkSkillId || '').toUpperCase()) || null;
}

export function getCanonicalFractionSkillBySlug(slug = '') {
  return bySlug.get(String(slug || '')) || null;
}

export function listCanonicalFractionSkills() {
  return FRACTION_CANONICAL_SKILL_ROWS.map((row) => ({ ...row }));
}

export default FRACTION_CANONICAL_SKILL_ROWS;
